### ISSUE TITLE
zfits LST1 MC simulation

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#1]
Hi.
I know that people are working on reading zfits with ctapipe and low-level calibration.
Do we have MC simulations (e.g. from prod3b) converted in zfits?
If so, (where) are they available?
For now ctapipe is reading files event-wise, I think it would be good to start working on reading them telescope-wise and then apply the different reconstruction steps.

**Comment by moralejo** [comment]
Hi,
we do not have any MC in the provisional R1/DL0 zfits format of LST. And to my knowledge nobody is working on such simtelarray->DL0 format converter. 
I understand it would be helpful for some developments, but on the other hand the idea of EventFileReader is that the actual format of the data is transparent to the users, right?  Wouldn't it be enough to be able to select a single telescope id to be read by EventFileReader from the standard MC files? Is such an option available already?

**Comment by vuillaut** [comment]
Hi Abelardo.
I see. Yes the EventFileReader *should* work seamlessly no matter the data format on disk but to actually **test** this before getting real data, I think it would be useful. I thought it was something existing already. However I have no idea how much work this would represent and if it's worth doing it or if we should just wait to get zfits files and debug at this point.
Sure the option to select a single telescope exists and that's where we should start.

**Comment by moralejo** [comment]
For testing we do have some real test data  with few clusters, and soon we will have data with full camera. Please join the lst-daq mailing list through the sharepoint if you want to get updates on this.

**Comment by rlopezcoto** [comment]
I'll close this one and will add some test files either to the `cta-lstchain-extra` repo or to the cluster in la Palma as soon as they are ready
