### ISSUE TITLE
Doubt about `sin_az_tel` feature in `lstchain_standard_config.json`

### ISSUE THREAD

**Issue by aaguasca** [cta-observatory/cta-lstchain#1019]
Currently, the feature `sin_az_tel` is used in the `lstchain_standard_config.json` file to train the RFs.

Should the azimuth telescope information be given as  `sin_az_tel` or `az_tel`?

**Comment by moralejo** [comment]
Hi, the reason is that for sources culminating in the south az_tel would jump from 180 to -180 deg at culmination, which is not a good feature for a variable to be used as RF input. Given that sin_az_tel does not have such discontinuity, it was chosen instead.

**Comment by aaguasca** [comment]
Thank you very much!
