### ISSUE TITLE
lstchain_create_dl3_index_files does not work correctly if it is executed in the same directory as DL3 data

### ISSUE THREAD

**Issue by katagirihide** [cta-observatory/cta-lstchain#1021]
If it is executed in the same directory, it reads only one file. The same situation was confirmed by Seiya.

(lst-dev) [hideaki.katagiri@cp02 22091601_lst1_crab]$ lstchain_create_dl3_index_files --input-dl3-dir ./ --file-pattern dl3_LST-1.Run*.gz --overwrite
2022-10-04 06:51:30,212 WARNING [ctapipe.FITSIndexWriter] (lstchain_create_dl3_index_files.setup): Overwriting /fefs/aswg/workspace/hideaki.katagiri/work/22091601_lst1_crab/hdu-index.fits.gz
2022-10-04 06:51:30,214 WARNING [ctapipe.FITSIndexWriter] (lstchain_create_dl3_index_files.setup): Overwriting /fefs/aswg/workspace/hideaki.katagiri/work/22091601_lst1_crab/obs-index.fits.gz
Run 2929 does not contain HDU BACKGROUND
Run 2929 does not contain HDU PSF
(lst-dev) [hideaki.katagiri@cp02 22091601_lst1_crab]$ mkdir tmp
(lst-dev) [hideaki.katagiri@cp02 22091601_lst1_crab]$ cd tmp/
(lst-dev) [hideaki.katagiri@cp02 tmp]$ lstchain_create_dl3_index_files --input-dl3-dir ../ --file-pattern dl3_LST-1.Run*.gz --overwrite
2022-10-04 08:49:46,607 WARNING [ctapipe.FITSIndexWriter] (lstchain_create_dl3_index_files.setup): Overwriting /fefs/aswg/workspace/hideaki.katagiri/work/22091601_lst1_crab/tmp/../hdu-index.fits.gz
2022-10-04 08:49:46,608 WARNING [ctapipe.FITSIndexWriter] (lstchain_create_dl3_index_files.setup): Overwriting /fefs/aswg/workspace/hideaki.katagiri/work/22091601_lst1_crab/tmp/../obs-index.fits.gz
Run 2929 does not contain HDU BACKGROUND
Run 2929 does not contain HDU PSF
Run 2930 does not contain HDU BACKGROUND
Run 2930 does not contain HDU PSF
Run 2931 does not contain HDU BACKGROUND
Run 2931 does not contain HDU PSF
Run 2950 does not contain HDU BACKGROUND
Run 2950 does not contain HDU PSF
Run 2970 does not contain HDU BACKGROUND
Run 2970 does not contain HDU PSF
Run 2971 does not contain HDU BACKGROUND
Run 2971 does not contain HDU PSF
Run 2972 does not contain HDU BACKGROUND
Run 2972 does not contain HDU PSF
Run 2973 does not contain HDU BACKGROUND
Run 2973 does not contain HDU PSF
Run 2988 does not contain HDU BACKGROUND
Run 2988 does not contain HDU PSF
Run 3095 does not contain HDU BACKGROUND
Run 3095 does not contain HDU PSF
Run 3096 does not contain HDU BACKGROUND
Run 3096 does not contain HDU PSF
Run 3273 does not contain HDU BACKGROUND
Run 3273 does not contain HDU PSF
Run 3274 does not contain HDU BACKGROUND
Run 3274 does not contain HDU PSF
Run 3275 does not contain HDU BACKGROUND
Run 3275 does not contain HDU PSF
Run 3318 does not contain HDU BACKGROUND
Run 3318 does not contain HDU PSF
Run 3319 does not contain HDU BACKGROUND
Run 3319 does not contain HDU PSF
Run 3320 does not contain HDU BACKGROUND
Run 3320 does not contain HDU PSF
Run 3338 does not contain HDU BACKGROUND
Run 3338 does not contain HDU PSF
(lst-dev) [hideaki.katagiri@cp02 tmp]$

**Comment by chaimain** [comment]
Thank you for reporting this! I reproduced the problem and will resolve it soon.

**Comment by maxnoe** [comment]
@katagirihide 

> `--file-pattern dl3_LST-1.Run*.gz`

You need to add quotes to the pattern, otherwise the shell will already expand the `*` to matching files, pass the option like this:

 `--file-pattern 'dl3_LST-1.Run*.gz'`

This is not a bug, this is how shells work....
