### ISSUE TITLE
Define Observation Mode (Wobble or Mispointing) for DL3

### ISSUE THREAD

**Issue by chaimain** [cta-observatory/cta-lstchain#1038]
I had made a temporary classification of the Observation Mode of "WOBBLE" and "UNDETERMINED" pointing here https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/high_level/hdu_table.py#L282-L292. We should define it properly, now that we have started extensively analyzing different DL3 files.

GADF also does not provide a concrete definition for us to use https://gamma-astro-data-formats.readthedocs.io/en/latest/events/events.html#obs-mode.

**Comment by maxnoe** [comment]
Please note that GADF 0.3, which we will release soon™ (we are sorting out zenodo issues only, everything else should be ready) defines OBS_MODE very clearly and this is already implemented in gammapy.

> GADF also does not provide a concrete definition for us to use

For observations that track a single ra/dec position, you must use `POINTING`. It should be made clearer in that docs page, but that's how it is defined from OGIP:

> OBS_MODE='POINTING'
> for data when a three-axes stabilized satellite is *pointing in a particular direction of the sky*,
> and a 'mean' pointing position can be given. 

That is almost all LST observations, independent of ON / OFF or wobble.

**Comment by maxnoe** [comment]
So, you should just use `POINTING`

**Comment by chaimain** [comment]
Ok! Thanks for the clarification @maxnoe. I will make a PR to make that change and merge when GADF v0.3 is released
