### ISSUE TITLE
use_flatfield_heuristic command line vs config file disagreement

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#1040]
Not setting the `use_flatfield_heuristic` option via command line overrules this variable if set in the config file

https://github.com/cta-observatory/cta-lstchain/blob/0a4ceac95c5e362bc202912527553a865c34e96d/lstchain/scripts/lstchain_data_r0_to_dl1.py#L224

Shouldn't it check first if `args.use_flatfield_heuristic` is not None (not specifying anything in the command line) before assigning it to the `lst_event_source` settings?

**Comment by rlopezcoto** [comment]
not sure how this was intended to be used from `ctapipe_io_lst`, maybe @maxnoe has more info, but not setting the `use_flatfield_heuristic` option should not override anything given in the config file

**Comment by maxnoe** [comment]
Yes, not giving an option should not result in the config being overwritten.

The option in `ctapipe_io_lst` use a three-way logic (True, None / not giving means "use date", False).

So if the config file has this option and the command line did not have any, the value from the config file should be used.

However, this is just one more symptom of not using `Tool` / `Component` properly.
