### ISSUE TITLE
Update to ctapipe 0.19

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#1053]
We should / need to update to a newer version, preferably the current release 0.17.

Breaking changes I foresee:

- [ ] Instrument Data Model changed, old files will not be readable
- [ ] Bokeh updated to 2.x, will likely break bokeh plots (@moralejo)
- [ ] CameraGeometry now has both effective focal length as well es equivalent one, this means we can properly convert to telescope frame and need to remove all the different hacks for having hillas parameters in degrees / correcting co
- [ ] ...

# Proposed procedure

* Update ctapipe_io_lst to support 0.17
* Create a branch ctapipe 0.17 here, so that multiple people can work
* Create PRs to fix issue to that 0.17 branch
* Further test / review 0.17 branch once unit tests run
* If everything looks ok, merge 0.17 branch

**Comment by chaimain** [comment]
This update is essential for #711 but maybe it might require some changes in the DL2 to DL3 stages. Will try to make follow-up specific PRs once the need appears.

**Comment by moralejo** [comment]
I am trying the DL1 check (the last part, that uses bokeh)
Since I am using already existing DL1 datacheck files the problem I encounter is the expected:

```
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/bin/lstchain_longterm_dl1_check", line 8, in <module>
    sys.exit(main())
  File "/Users/moralejo/CTA/ctasoft/cta-lstchain/lstchain/scripts/lstchain_longterm_dl1_check.py", line 795, in main
    subarray_info = SubarrayDescription.from_hdf(files[0])
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.10/site-packages/ctapipe/instrument/subarray.py", line 593, in from_hdf
    raise IOError(f"Unsupported version of subarray table: {version}")
OSError: Unsupported version of subarray table: 1.0
```

So, what is the best way to deal with this? I think in some cases we would like to be able to keep using existing DL1 files, right?

**Comment by maxnoe** [comment]
> Since I am using already existing DL1 datacheck files the problem I encounter is the expected:

Yes, unfortunately we have to bootstrap from scratch... I am currently trying to recreate the calibration files, fixing issues until I succeed. Once we have the calibration file creation working, we can work on running dl1 again, then the datacheck.

The datachek is probably something we can look into only last....

**Comment by maxnoe** [comment]
Good news is that I got the `lstchain_create_runsummary` already working again and it seems no changes were required for the `onsite_create_drs4_pedestal_file` script.

This is currently running.

**Comment by maxnoe** [comment]
Ok, update:

I was able to produce calibration files (drs4 baseline, drs4 time, calibration file (no systematics correction).

Anyone who wants to help, please, clone both `ctapipe_io_lst` and `lstchain`:

```
$ git clone git@github.com:cta-observatory/cta-lstchain
$ git clone git@github.com:cta-observatory/ctapipe_io_lst
```

Switch to the 0.17.0 branches in both repos:

```
$ cd ctapipe_io_lst
$ git checkout ctapipe_0.17
$ cd ../cta-lstchain
$ git checkout ctapipe_0.17
```

Create a new env from the environment.yml in the lstchain repo:
```
$ mamba env create -f environment.yml -n lstchain-ctapipe-0.17
$ mamba activate lstchain-ctapipe-0.17
```

Install ctapipe_io_lst and lstchain in development mode, currently that needs:

```
$ SETUPTOOLS_ENABLE_FEATURES="legacy-editable" pip install -e ../ctapipe_io_lst
$ pip install -e .
```

**Comment by maxnoe** [comment]
> I think in some cases we would like to be able to keep using existing DL1 files, right?

In most cases, yes. But unfortunately, this is not possible with the changes in ctapipe this time. We fundamentally changed the way ctapipe stores metadata that is required for the reading into containers / tables. So this time, we cannot keep compatibility.
