### ISSUE TITLE
R0 to R1 calibration

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#106]
Hi,
This entry is more for @pawel21 but I put it here to be sure we agree all on the proposal.

I realise that the low level calibrator in R0.py is changing the R0 waveform. Actually it should calibrate the R0 and fill the R1 (keeping the R0 unchanged).

Actually, we should have  NullR0Calibrator (for EvB3) that just fill the R1 with the element of R0 keeping only the [2:38] samples, like this : 

`
class NullR0Calibrator(CameraR0Calibrator):
    """
    A dummy R0 calibrator that simply fills the r1 container with the samples
    from the r0 container.

    Parameters
    ----------
    config : traitlets.loader.Config
        Configuration specified by config file or cmdline arguments.
        Used to set traitlet values.
        Set to None if no configuration to pass.
    tool : ctapipe.core.Tool or None
        Tool executable that is calling this component.
        Passes the correct logger to the component.
        Set to None if no Tool to pass.
    kwargs
    """

    def __init__(self, config=None, parent=None, **kwargs):
        super().__init__(config, parent, **kwargs)
        self.log.info("Using NullR0Calibrator, if event source is at "
                      "the R0 level, then r1 samples will equal r0 samples")

    def calibrate(self, event):
        for telid in event.r0.tels_with_data:
            samples = event.r0.tel[telid].waveform[:,:,2:38]
            event.r1.tel[telid].waveform = samples.astype('float32')

`

and,  in the case of not corrections from EvB, we need a LSTR0Corrections.calibrate(event) function that call all the corrections and fill the R1  waveform with the [2:38] samples. 

I can create the functions but as the code is done now, it modifies directly the R0. 

@Pawel,  is it complicated to keep the original R0 and just fill the R1 with the corrected [2:38] samples of R0? 

Are there objection on this?

PS: When this is done I will change the calibration modules to act on the R1 data and not on the R0 data as it is done now.

**Comment by pawel21** [comment]
Hi @FrancaCassol ,

No objection from my side.

>  is it complicated to keep the original R0 and just fill the R1 with the corrected [2:38] samples of R0?
No, this seems be simple.

I agree, we can fill R1 container.

**Comment by FrancaCassol** [comment]
Very nice.

Then, @pawel21 you can have a look at the R0,py module my branch calib_camera_dev
[https://github.com/FrancaCassol/cta-lstchain/blob/calib_camera_dev/lstchain/calib/camera/r0.py](url)

I made already some of the changes I mentioned (in order to continue my developments) and also some updates to make the module more conform to the ctapipe master. However, probably it is better that you merge  all changes together and make the PR of the new r0.py (please do not hesitate to suggest other solutions if you think).

You can see in the tools how the R0 calibrator is then used (e.g [https://github.com/FrancaCassol/cta-lstchain/blob/calib_camera_dev/lstchain/tools/calc_pedestals.py](url))

**Comment by pawel21** [comment]
Thank you very much @FrancaCassol 

I've change my code, now calibrations methods fill R1 container.
@FrancaCassol Could you look on my code?: https://github.com/pawel21/cta-lstchain/blob/low_level_calib_drs4/lstchain/calib/camera/r0.py

Example notebook: https://github.com/pawel21/cta-lstchain/blob/low_level_calib_drs4/notebooks/low_level_corrections.ipynb

**Comment by FrancaCassol** [comment]
Hi @pawel21,

It works! But I did still some changes, have again a look at 
[https://github.com/FrancaCassol/cta-lstchain/blob/calib_camera_dev/lstchain/calib/camera/r0.py](https://github.com/FrancaCassol/cta-lstchain/blob/calib_camera_dev/lstchain/calib/camera/r0.py )

I had to change the __init__ arguments to be compatible with catpipe master.
Also I added two arguments to select the length of the r1 waveform. 

r1_sample_start = Int(0, help='Start sample for r1 waveform').tag(config=True)
r1_sample_end = Int(0, help='End sample for r1 waveform').tag(config=True)

But  I am not really happy with it because I wanted to have as default the r0 length, but I could not use the None as default for the Int trailet and it is not clear to me which other trailet I could use otherwise

Has somebody a clever idea on how to keep as default the slice  [:]  or [None:None] ?
(@dneise? @MaxNoe ?)

**Comment by dneise** [comment]
I am lost ... 

This issue seems to discuss a development branch by @FrancaCassol (for which no PR exists, so this branch seems not to be ready at all ... otherwise one would maybe have opened a PR) and at the same time this issue discusses a branch by @pawel21. 

Francas branch is this one: https://github.com/pawel21/cta-lstchain/tree/low_level_calib_drs4
Pawels branch is this one: https://github.com/FrancaCassol/cta-lstchain/tree/calib_camera_dev

Both branches are somehow behind the master... 

I think, if the features, which Franca is working on, form somehow a basis for Pawels work, then it would be good to merge Francas branch into the master (or at least open a PR) and then Pawels PR can be nicely reviewed in the context of the new master, which by then contains Francas new features. Does that sound feasible?

**Comment by MaxNoe** [comment]
> But I am not really happy with it because I wanted to have as default the r0 length, but I could not use the None as default for the Int trailet and it is not clear to me which other trailet I could use otherwise

Does this not work?
```
Integer(default=None, allow_none=True)
```

**Comment by FrancaCassol** [comment]
> 
> I think, if the features, which Franca is working on, form somehow a basis for Pawels work, then it would be good to merge Francas branch into the master (or at least open a PR) and then Pawels PR can be nicely reviewed in the context of the new master, which by then contains Francas new features. Does that sound feasible?

Hi Dominik, you are totally right, the problem is that I am waiting that my PR [https://github.com/cta-observatory/cta-lstchain/pull/92](https://github.com/cta-observatory/cta-lstchain/pull/92) is accepted (@rlopezcoto are there news about the review?) and in the meanwhile I want to go further with the code development which demands some changes in Pawel's code ... I know, surely mine here is not the most orthodox procedure ...

**Comment by rlopezcoto** [comment]
Hi @FrancaCassol, yes, sorry I'll have a deeper review before the end of the week, but I was hoping also somebody else would do it, any volunteers?
In the meantime, I still see conflicts in #92 due to`lstchain/io/lsteventsource.py`, so I could not merge it either way, could you please correct this? Thanks

**Comment by FrancaCassol** [comment]
Thanks Max, it works! :-)
 
> ```
> Integer(default_value=None, allow_none=True)
> ```

**Comment by FrancaCassol** [comment]
@pawel21 please have a look at the last r0.py version of my git, it allows None as default for the R0CameraCalibration arguments

**Comment by pawel21** [comment]
@FrancaCassol 
I will look and test last r0.py
Thank you

**Comment by vuillaut** [comment]
Hi
@FrancaCassol and @pawel21 
I think this can be closed, right?

**Comment by FrancaCassol** [comment]
Yes for me

**Comment by pawel21** [comment]
Yes

**Comment by vuillaut** [comment]
Thanks.
