### ISSUE TITLE
longterm dl1 check shows pedestal charge std dev twice (missing mean)

### ISSUE THREAD

**Issue by Hckjs** [cta-observatory/cta-lstchain#1073]
https://github.com/cta-observatory/cta-lstchain/blob/52bdb741e8da40d5e1f8359843c407fcf3b2d098/lstchain/scripts/lstchain_longterm_dl1_check.py#L1119

should be `'ped_pix_charge_mean'`

**Comment by moralejo** [comment]
Thanks, what a blunder.  I guess it went unnoticed because only the std dev is really checked.
