### ISSUE TITLE
Defined range of az_tel for real data and simulation data

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/cta-lstchain#1079]
I realized the defined range of az_tel is different between real data (-90 < az_tel < 270) and simulation data (0 < az_tel < 360). Is it a known feature? I think it is not good when using `az_tel` (instead of `sin_az_tel`) for random forest training.

**Comment by rlopezcoto** [comment]
@SeiyaNozaki did you (or anybody) seen anything worrying back when we were using `az_tel` instead of `sin_az_tel` apart from the discontinuity in 0,360 that you reported some time ago? I think we are safe now that we are using `sin_az_tel`, but to be on the safe side we could wrap the angles to 360 deg as @maxnoe is suggesting

**Comment by moralejo** [comment]
@SeiyaNozaki shall we give a try at the wrapping? Or perhaps better, we could make the calculation of the sin(az) inside the DL1 to DL2 stage (for DL1 files where it does not exist, i.e. all our standard ones now), and stop using az in the RFs.

**Comment by SeiyaNozaki** [comment]
yeah, at least it would be better to wrap azimuth to avoid any confusion. It is also good to calculate sin(az) inside the DL1 to DL2 stage, but if you want to know if sin(az) is really needed, I can check.

**Comment by moralejo** [comment]
Well, depends on what you mean by "really needed". I am pretty sure the difference will be small, but considering how RF works, using an azimuth with a discontinuity at 0/360 is not the best you can do. It will treat events at, say, 359.9 and 0.1 as "maximally different" in that variable, while they are in reality the same.
