### ISSUE TITLE
Need for specific scipy version installation

### ISSUE THREAD

**Issue by chaimain** [cta-observatory/cta-lstchain#1093]
@moralejo found an import error for `QhullError` from `scipy.spatial` from the new merger of PR #711  https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/high_level/interpolate.py#L21 while having scipy 1.7 installed in the conda environment. We do not have any constraints on scipy version currently. This might be essential for the forthcoming major release with major updated dependencies, to avoid any such issues for individual users.

The particular import worked on my system which has scipy 1.9.3 and it also did not create any warnings for this import in the CI. 

I tried to use `scipy~=1.8` but it had various inconsistencies with a list of other dependencies (pydantic, ctapipe, gammapy, iminuit, etc). With this change, it allows me to make the above import of `QhullError` but the issue with other dependencies is a problem.

**Comment by gabemery** [comment]
Is it possible to install scipy 1.7 with current dependencies? If everything worked with 1.9.3 why did you try 1.8?

**Comment by chaimain** [comment]
Working with Gammapy, I just know that there was an issue with v1.10, which was resolved in the bugfix v1.10.1.

**Comment by gabemery** [comment]
SciPy 1.7.0 : Jun 20, 2021
ENH: make QhullError public (https://github.com/scipy/scipy/pull/15003) : Nov 8, 2021
SciPy 1.8.0:Feb 4th 2022

It seems the change of QhullError implementation which is compatible with you way of importing it is implemented since release 1.8.0. So you should add scipy>=1.8

**Comment by chaimain** [comment]
It does work and I get scipy 1.9.3 installed and all tests pass. Also checked with the fix in #1092 to be certain. I will make a PR for this change.
