### ISSUE TITLE
IRF metadata floating point precision

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/cta-lstchain#1098]
Apparently the `create_irf_file` tool uses the mean offset position of the gammas to determine the offset used in the simulation:

https://github.com/cta-observatory/cta-lstchain/blob/4cc8bce8bd1efd4bb9860b6e6341c165ebe03b0b/lstchain/tools/lstchain_create_irf_files.py#L379-L381

https://github.com/cta-observatory/cta-lstchain/blob/4cc8bce8bd1efd4bb9860b6e6341c165ebe03b0b/lstchain/tools/lstchain_create_irf_files.py#L522-L525

This creates an issue in my case where most produced irfs have offset 0.4 deg, but one has 0.3999 making them "incompatible" for interpolation. There are 2 questions arising:
- This used to round to 3 digits, but was changed a year ago by @chaimain in this commit: https://github.com/cta-observatory/cta-lstchain/commit/d75ee4554927455018de9b8d8d8dfd6bcfedac6c
Was there any deeper reason for that? 3 digits already seems excessive to me in this case
- Is this needed at all? Clearly this information should be stored in the simtel files.

**Comment by chaimain** [comment]
The `{true,reco}_source_fov_offset` is evaluated for each MC events, by evaluating the angular separation from `{true,reco}_{alt,az}` and `pointing_{alt,az}` and thus it cannot be in simtel files.

Fixing the precision of the various angular parameters in the IRF Tool was indeed not a trivial thing as we do not have a standard yet. I think I just tried to add more significant digits to accommodate the new `ring_wobble` type of MC. Can you check for which MC nodes (maybe zenith-based) these differences arise?

**Comment by LukasNickel** [comment]
It is the `theta_82.155_az_79.122` node. All other ones are 0.4. (20230127 production with lstchain master)

**Comment by chaimain** [comment]
Just for a sanity check, can you confirm if this node is 'good' compared with other nodes of the same zenith/theta and of an earlier production for the same declination line? It could be that this particular node is an anomaly. If not, then yes, the precision levels have to be revisited properly.

**Comment by LukasNickel** [comment]
Why do you need the `reco_fov_offset` here?
My impression is that you only need the simulation information for this and indeed @maxnoe told me this is exactly what is done to distinguish the mc types aswell here:
https://github.com/cta-observatory/cta-lstchain/blob/58a12a358b3680b6b7824b7f05adcc16f65a07a2/lstchain/io/io.py#L1174-L1200

Can we not do the same thing for the irfs and take the mean of `max_viewcone` and `min_viewcone`?
