### ISSUE TITLE
Transparent file reading/writing

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#11]
Make the intermediate data (DL1) writing/reading transparent to the user. This is related to issue #10.

**Comment by vuillaut** [comment]
hi @rlopezcoto 
My idea was to wait for the last PR from @misabelber and to work from there.
Next week I'll focus on:
- making all the code more pep8 compliant
- getting the code more in-line with ctapipe functionalities and in particular, the files writing/reading (this issue)
- merging my work with the one from @misabelber 

How does that sound for both of you?

**Comment by rlopezcoto** [comment]
it sounds verty good and helpful, thanks!

**Comment by misabelber** [comment]
Yes! Thank you very much. Any help with this is very welcomed

**Comment by vuillaut** [comment]
Solved by #30
