### ISSUE TITLE
Lstchain v0.9.13 is not compatible with latest pandas release

### ISSUE THREAD

**Issue by Kenta2076** [cta-observatory/cta-lstchain#1101]
I have encountered a certain issue when I executed `lstchain_dl1_to_dl2.py` in a lstchain v0.9.13 environment. After some investigation, I realized that `filter_events()` function in `lstchain.reco.utils.py` is using an pandas option key that does not exist any longer in the latest pandas release [(link)](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html):
```python
if finite_params is not None:
        _finite_params = list(set(finite_params).intersection(list(events_df.columns)))
        with pd.option_context('mode.use_inf_as_null', True):
            not_finite_mask = events_df[_finite_params].isnull()
        filter &= ~(not_finite_mask.any(axis=1))
``` 
`mode.use_inf_as_null` is the one that does no longer exist. Maybe it should be `mode.use_inf_as_na`?

**Comment by maxnoe** [comment]
This is already fixed in the current master, see [#pandas](https://github.com/cta-observatory/cta-lstchain/pull/1084)
