### ISSUE TITLE
easier collaboration?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/cta-lstchain#112]
Hello, I was wondering if you maybe would like to collaborate easier and quicker on PRs in this project?

Currently you are using the same workflow as ctapipe is doing, i.e.:
 - make a (somehow private) fork
 - work in a branch of that fork
 - open a PR, discuss ... merge

So far so good, but what if two people would like to collaborate on a PR, say one person has a good idea for a new feature, but is not good with style (no tests, short variable names, no docu) and another person likes to write tests and docu. In that case, instead of reviewing the PR and saying things like: "there is a test missing" and "this variable name is confusing" one could just work together. (Of course those two people would probably want to work very closely together using chats on voice-calls all the time).

This kind of "highly collaborative" workflow is most easily achieved if everybody who wants to contribute gets **write access** to the repo (not admin access, just write). This might *feel* dangerous, since everybody having write access could just push wrong stuff into the master branch, therefore in addition the master branch can be protected.

Here is a quick (<1min) video showing how to do that: https://youtu.be/GOvJRoBUS-M

So you see, there is absolutely no danger in opening a project to everybody who wants to contribute. Examples of projects working like this in our field are: pyfact and pyeventio, both are in the order of <10 developers. As soon as one gets more than 10 regular developers, one can maybe think about PRs needing 2 reviews... before that this is overkill. 

If the group of developers is so small, that nobody has time to review each others commits, one can even decide to need no review at all, so people can open a PR ... and then after 1sec they can click the merge button. This is still good, since there will be a formal merge commit, which can be easily found and reverted in case a PR turns out to be bad. This is still much better than having everybody pushing into the master all the time.

I think this kind of approach could be beneficial here.

**Comment by vuillaut** [comment]
Hi @dneise.

I have been requesting that for a while and I fully agree with you.
It would indeed make things easier I think and I could have done some things way earlier, such as setting up Travis or #55 ...
But I think that only @kosack has the admin rights on the repo and could change the setup and writing right here.

**Comment by dneise** [comment]
Oh ... I think this repo **should belong** to LST people maybe 2 or 3 of them, so it is easier to reach an admin if needed.

**Comment by rlopezcoto** [comment]
Hi all,

Just to clarify, @kosack has *owner* rights on this repo, additionally, I am *admin* and @moralejo has *write* permission in case I am not available. 
At the beginning, I decided to open the repo and give write permission to everybody that was contributing, which resulted exactly on what @dneise mentioned: direct commits into the master branch without a PR to track them down, so the current system is the second stage of the repo :D
I am open to a trade-off solution in which the master branch is protected, but I would still keep that at least one person revises the code. It would probably be better if we discuss this next week in person,what do you think?

**Comment by dneise** [comment]
You can even require that the person which is reviewing the code has to be an admin. This is for example needed if you have a team of N+1 trolls. One person opens a malicious PR and then N other persons review and approve even though that PR is clearly bad. 
But I assume, this did not happen here ... it was more a case of carelessness not of malicious intend, no?

So protecting the master branch and requiring 1 approving review is typically fine in our field....
If it does not work and teams of trolls form, one just removes their access rights and reverts the master to the time before their malicious PR was merged and goes on with the rest of the people who know how to behave. Costs 10 minutes.

**Comment by dneise** [comment]
What also helps to keep to improve the quality of PRs is using automatic tools to ensure some basic things: 
 - executing the tests on travis: -> ensure no existing features were broken by accident
 - executing a linter on the code -> ensure at least some coding style used. (can even find typos, and saved my ass a couple of times, where typos where in untested branches)

**Comment by rlopezcoto** [comment]
No trolls here, too boring place to troll the code :)
We should talk about these options in person in Montpellier

**Comment by vuillaut** [comment]
I am closing this issue.
A few people (core developers let's say) have write access or enough rights to contribute to a PR directly.
Such rights can be attributed upon request in the future to contributors.
