### ISSUE TITLE
discussion: write modified images after dl1ab

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#1127]
Hi,

I think modified images should be written (unless `--no-image` is passed of course) when running dl1ab with an image modifier. At the moment, the original images (unmodified) are written.

For two reasons:
- files should be consistent: I would expect that the parameters in a file have been computed on the images in the same file
- it would very much ease other analyses starting at DL1a level

I remember we quickly discussed this when creating the dl1ab script, but I can't remember if (and which one) there was a good/specific reason for the current behaviour?

@rlopezcoto @moralejo @maxnoe

**Comment by rlopezcoto** [comment]
@vuillaut you mean for MC, right?

**Comment by vuillaut** [comment]
> @vuillaut you mean for MC, right?

Yes indeed. Is there a DL1 image modifier pour Real data ?

**Comment by rlopezcoto** [comment]
we are at the moment mor storage-starved, although in any case I do not think that DL1 MC files are occupying a significant amount of space

**Comment by maxnoe** [comment]
At the moment, lstchain also stores the images using very inefficient, losless compression on the float32 data.

The size could be reduced roughly by half using the fixed width transformation (storing the images and charges as scaled, rounded integers) instead.

**Comment by vuillaut** [comment]
> I think the main argument against storing the modified images is that you can't restart the processing from the modified images if you want to change the settings of the modifier.
> 
> This means , if we now store the modified images, either:
> a) have to restart from simtel in that case
> b) Running r0_to_dl1 without modification to store unmodified images, then dl1ab with modifier keeping both
> 
> So it's a trade-off between CPU and storage resources. 
> 

I think the modifier only happens in the dl1ab process. So unmodified DL1 images are there already.
Most of the time we run dl1ab without writing again the images of course (because most of the time we don't need it and because they are available in the source DL1). 
So these new images would be written only if needed, but in that case I think the modified ones are more useful.

**Comment by maxnoe** [comment]
> So unmodified DL1 images are there already.

I think they were removed after the dl1ab step by lstmcpipe...

**Comment by vuillaut** [comment]
> > So unmodified DL1 images are there already.
> 
> I think they were removed after the dl1ab step by lstmcpipe...

In the output, yes by default there are removed (but any option of lstchain scripts can be passed).
In the input DL1 there are of course present.
I am not sure if everything is clear?

**Comment by maxnoe** [comment]
No, I meant that in previous processing, of I remember correctly, the r0_to_dl1 output was removed after dl1ab had run.

But maybe I am confusing that with the latosa processing of the observed data.

**Comment by moralejo** [comment]
> in lstosa we keep the DL1b files post dl1ab (with the original DL1a images) and remove the output of the r0 to dl1 script

That is all right because for real data there is no image modifying, hence no inconsistency.
