### ISSUE TITLE
docs build fialing due to seaborn style in mc sensitivity

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#1161]
```
 Failed to import lstchain.scripts.lstchain_mc_sensitivity.
Possible hints:
* OSError: 'seaborn-deep' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
* AttributeError: module 'lstchain.scripts' has no attribute 'lstchain_mc_sensitivity'
```

**Comment by morcuended** [comment]
Recent matplotlib release 3.8.0 (2023-09-13) dropped support for the `seaborn-<foo>` styles -> use `seaborn-v0_8-<foo>` instead, or directly use the seaborn API.

**Comment by morcuended** [comment]
I propose pinning matplotlib to ~=3.7.0 to avoid jumping to 3.8 for the time being. I think this anyway has to be fixed in ctaplot

**Comment by rlopezcoto** [comment]
> I propose pinning matplotlib to ~=3.7.0 to avoid jumping to 3.8 for the time being. I think this anyway has to be fixed in ctaplot

sounds good as a temporary solution, let's in any case leave this open or open a new Issue to remember to unpin matplotlib whenever this is fixed in ctaplot (@vuillaut)

**Comment by maxnoe** [comment]
@vuillaut is fixing this in ctaplot, so we could also just update once ready.

**Comment by maxnoe** [comment]
https://github.com/cta-observatory/ctaplot/pull/201
