### ISSUE TITLE
Confusing error message in DL3 creation using interpolation if not using alpha cuts

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#1180]
https://github.com/cta-observatory/cta-lstchain/blob/644e43b9b688603c3892cc963b520be9b17fa9f3/lstchain/high_level/interpolate.py#L626-L652

I'm confused by this error here. I think that if I'm not using alpha cuts at all for the DL3 creation, there should not be a log error here in that regard. IMO, logging an error would imply that the tool actually fails, which does not in case this happens.

**Comment by maxnoe** [comment]
@morcuended Your code snipped does not contain any error...

**Comment by morcuended** [comment]
that's the piece of code logging the following error due to the `KeyError` caught
```
The metadata are comparable
The other parameter axes data are comparable
2023-11-14 12:55:56,178 ERROR [lstchain.high_level.interpolate] (interpolate.interpolate_irf): AL CUTS not present for IRF interpolation
```

**Comment by maxnoe** [comment]
No, AL_CUTS is only relevant for source dependent analysis.
