### ISSUE TITLE
How to cite lstchain?

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#1205]
I think we should decide whether we should update the instructions given in the README:
 - Cite the ICRC 2021 proceedings?
 - Cite the LST performance paper?
 - There is also the ADASS XXX "lstchain: An Analysis Pipeline for LST-1, the First Prototype
Large-Sized Telescope of CTA"

I would cite the LST performance paper and the zenodo of the version used. Opinions?

**Comment by rlopezcoto** [comment]
Hi, 
>Cite the ICRC 2021 proceedings?

this was a contribution about the physics, not the software

>Cite the LST performance paper?

this should be included in every LST paper :D 
but if we want to give a reference about the software and where it is cited, we can also include the:

>ADASS XXX "lstchain: An Analysis Pipeline for LST-1, the First Prototype
Large-Sized Telescope of CTA"

that is, as far as I know, the only reference to lstchain. zenodo for me is complementary, to know exactly which version of the software we used, but does not give a description of the software.

**Comment by morcuended** [comment]
I agree. Right now the README suggests citing the ICRC 2021 proceedings. There is no mention of the ADASS XXX reference or the LST-1 performance paper. I think this should be changed and add a `CITATION.cff` file with all this information

**Comment by vuillaut** [comment]
Closing @morcuended as I think it was solved in #1265.
Feel free to reopen otherwise.
