### ISSUE TITLE
Absurd muon ring results because of few misbehaving pixels

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#1213]
https://github.com/cta-observatory/cta-lstchain/blob/1517320040f107bc8a44deb61a6a1d713334cf1a/lstchain/reco/r0_to_dl1.py#L673-L684

The unusable pixels information used by the muon ring analysis is based only on the pedcal file.

On the night 20240129 one cluster was systematically misbehaving (large pixel signals of 100's of p.e. for all events). The data were calibrated (because of problems with the calibox) with a pedcal file from an earlier night, which showed no issues. 
The muon ring analysis is completely messed up, because the bad pixels do not show up as "unusable" (since they are ok in the pedcal). The shower analysis seems less affected, probably because the pedestal cleaning is removing those pixels in most of the events.

**Comment by rlopezcoto** [comment]
were there problems with the calibox only for the pedcal run data taking or for the whole night? If the calibration box cannot be used, then these data will not be very useful anyways. Otherwise, and since there will not be many nights like this one, I am not sure if it is worth it the implementation of a different way to calculate the unusable pixels only in the case of using a pedcal file from a different night.

**Comment by moralejo** [comment]
The interleaved FF charges and times look legit except for the pixels in the bad cluster. 

Besides the huge effect on muons, some showers are also affected (slight concentration of CoGs close to the bad cluster), but, other than that, the bulk of the shower images seem ok judging from cosmics intensity spectra and other distributions.

Once we have the Cat-B calibration in place, the behaviour of the pixels *during* the run (and not just in the used pedcal) will be used to determine which ones are unusable. This will solve the problem, so I do not think we need to do anything specific for this night. I just wanted to leave some record of this.

**Comment by moralejo** [comment]
I hope so, please @FrancaCassol keep this night in mind for the testing of Cat-B (remember the pedcal from the night itself is useless).
