### ISSUE TITLE
About global baseline subtraction for R1 data

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#125]
Hi @moralejo, @rlopezcoto, @pawel21 

data coming form EvB 3 (after the low level correction) will be aligned to a baseline value of 400 (that, by the way, is for the moment written no where). In order to have waveforms with pedestal around zero,  I would like to subtract this fixed baseline value at the ctapipe_io_lst reader level and also perform the suppression of the first and last two samples (that are unusable). That is, the reader will:
1) fill the R0.waverform with the waveform as it comes from EvB (shape 40)
2) fill the R1.waveform with (R0.waverform - 400) and  shape 36 (samples 0,1,38,39 are suppressed)

For EvB2, we will add this subtraction in the R0Calibration module, which is in this case responsible of filling R1 from R0  

What do you think?

**Comment by pawel21** [comment]
Hi @FrancaCassol,

Good idea.
To my knowledge, EVB3 now can subtract baseline and perform delta_t correction, still we need interpolate spikes offline. So, we should keep in mind it.

**Comment by FrancaCassol** [comment]
Hi @Pawel, 
thinking again at this point, I suggest for the moment that the baseline ("offset" in the R0Calibrator) is subtracted from the r1 waveform inside the calibrate() function of the CameraR0Calibrator, so that the r1 waveform is around zero in the case of no signal. I can add this change in my next PR (which is coming soon). Is this ok for you?

**Comment by pawel21** [comment]
Yes, this is ok. 
Let's do it and looks how it works.

**Comment by vuillaut** [comment]
Hi @FrancaCassol and @pawel21 
Is this still under discussion or shall I close?

**Comment by FrancaCassol** [comment]
We can close
