### ISSUE TITLE
Randomly (?) failing test

### ISSUE THREAD

**Issue by gabemery** [cta-observatory/cta-lstchain#1275]
The following test : lstchain/tools/tests/test_tools.py::test_add_scale_true_energy_in_irfs 
Failed once during CI of an unrelated PR : https://github.com/cta-observatory/cta-lstchain/actions/runs/9890700906/job/27319513170?pr=1274

Re-launching the test worked so it may be a randomly occurring issue.

**Comment by chaimain** [comment]
That is random indeed...
@deborahDOR Can you check with the test MC file being used, the exact values of the shifted Energy Migration matrix? Maybe you can try to make a large shift by using `scale_true_energy=1.3` or something similar, so as to be certain to avoid such random test fails?
