### ISSUE TITLE
Choosing a licence

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#129]
Hi.

I think we should add a license to this repo.
I would propose MIT but I think the decision belongs to the LST collaboration.

**Comment by rlopezcoto** [comment]
Hi,

there is a license right now, would you want us to choose a different one? In ctapipe there is even a placeholder at the moment

**Comment by vuillaut** [comment]
Ho sorry for that, my bad!
I overlooked the LICENSE directory and was mislead by GitHub stating there is none in https://github.com/cta-observatory/cta-lstchain/community.

Closing the issue.
