### ISSUE TITLE
Problems with python-blocs2 installation

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#1306]
Fresh lstchain installation on MacOS (ARM-based M2 chip) gave me problems recently.

```
mamba create -c conda-forge -n lstchain-v0.10.12 python=3.11 lstchain=0.10.12
```

```
...
Could not solve for environment specs
The following package could not be installed
└─ lstchain 0.10.12**  is uninstallable because it requires
   └─ python-blosc2  , which does not exist (perhaps a missing channel).
```
Indeed python-blosc2 (https://anaconda.org/conda-forge/python-blosc2) supports osx-64 but not arm arquitechture.
I could install however c-blosc2 (https://anaconda.org/conda-forge/c-blosc2) on a new environment and then install lstchain.

I think we should include an additional note in the installation section warning about this.

**Comment by maxnoe** [comment]
I think we can just remove the pin to python blocks in the conda recipe, it was a fox for a missing dependency in tables, which I think got updatet in the mean time. I will have a look

**Comment by maxnoe** [comment]
There is now a new version of the conda package without the python-blosc2 dependency, could you check again?

**Comment by morcuended** [comment]
`mamba create -c conda-forge -n lstchain-v0.10.2 python=3.11 lstchain=0.10.12` works (but not with python 3.12 though)

**Comment by maxnoe** [comment]
This is a conflict with matplotlib now. And this is a real requirement in lstchain here:

>         'matplotlib~=3.7.0',

**Comment by morcuended** [comment]
I think we can free that requirement (see #1161)

**Comment by morcuended** [comment]
I think this can be closed. The problem of supporting python 3.12 is a different matter. Thanks for the help with the conda recipe.
