### ISSUE TITLE
Wrong Camera Coordinate Frame in LST Camera defintion

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/cta-lstchain#138]
As discussed with @FrancaCassol and @rlopezcoto in Lugano,
the file `LSTCam-002.camgeom.fits.gz` in ctapipe-extra
has the pixel coordinates in the wrong cordinate frame.
The coordinates are in MAGIC/FACT/EngineeringFrame not in the 
HESS/sim_telarray/ctapipe frame.

`ctapipe` at the moment requires that the pixel coordinates are given in the sim_telarray frame, otherwise coordinate transformations will not work.

![lstcams](https://user-images.githubusercontent.com/5488440/59022090-6c290e00-884d-11e9-8dfe-fab7127794a8.png)

```python
from ctapipe.instrument import CameraGeometry
from ctapipe.visualization import CameraDisplay
import matplotlib.pyplot as plt
import numpy as np

fig, axs = plt.subplots(1, 2, constrained_layout=True, figsize=(6, 3))

d1 = CameraDisplay(CameraGeometry.from_name('LSTCam', version=2), ax=axs[0])
d2 = CameraDisplay(CameraGeometry.from_name('LSTCam'), ax=axs[1])
d1.image = np.arange(1855)
d2.image = np.arange(1855)


fig.savefig('lstcams.png', dpi=300)
```

**Comment by MaxNoe** [comment]
See the documentation of `CameraFrame`: 
https://cta-observatory.github.io/ctapipe/api/ctapipe.coordinates.CameraFrame.html#ctapipe.coordinates.CameraFrame

Discussion here https://github.com/cta-observatory/ctapipe/issues/255

**Comment by MaxNoe** [comment]
I opened a PR here: https://github.com/cta-observatory/ctapipe/pull/1085

If that is merged, you could do:

```python
cam = CameraGeometry.from_name('LSTCam', version=2)
cam.frame = EngineeringCameraFrame()
cam = cam.transform_to(CameraFrame())
```

To get the camera geometry in the correct coordinate system.

**Comment by rlopezcoto** [comment]
Great @MaxNoe, thanks!
Since we are not in a very big hurry because we are still not taking data in which we use the pointing information, I think by now we will wait to see if the PR gets merged, otherwise we can consider other actions

**Comment by MaxNoe** [comment]
I would suggest the file as well. So x → -y, y → -x, and cam and pix rotation → 90° - rotation

**Comment by MaxNoe** [comment]
cta-observatory/ctapipe#1085 is merged now, the `EngineeringCameraFrame` is available and can be used for plotting. However, the geometry files needs to have coordinates given in the `CameraFrame`, so this should be updated

**Comment by rlopezcoto** [comment]
This was solved with [this ctapipe-extra PR](https://github.com/cta-observatory/ctapipe-extra/pull/25) and we later moved them to ctapipe_io_lst:
https://github.com/cta-observatory/ctapipe_io_lst/pull/19
https://github.com/cta-observatory/ctapipe_io_lst/pull/20
https://github.com/cta-observatory/ctapipe_io_lst/pull/23
