### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#143]
The repository size is currently ~50MB.
This is way too much and probably due to some old data file in the history.

**Comment by vuillaut** [comment]
notebooks are way oversized, probably due to a lot of images dumped there.
```
1,7M	notebooks/Calculate_sensitivity.ipynb
296K	notebooks/Calculate_sensitivity_eventio.ipynb
648K	notebooks/Plot_muon_parameters.ipynb
800K	notebooks/RF-performance.ipynb
4,8M	notebooks/RFcls_GH.sav
1,6M	notebooks/RFreg_Disp.sav
1,6M	notebooks/RFreg_Energy.sav
7,6M	notebooks/Read_and_plot_LST_Data.ipynb
964K	notebooks/Step_by_Step_dl0_to_dl1.ipynb
424K	notebooks/Tests_on_Impact_parameter.ipynb
2,3M	notebooks/calculate_calibration_coefficients.ipynb
1,8M	notebooks/calculate_pedestals.ipynb
216K	notebooks/data_vis.ipynb
172K	notebooks/disp.ipynb
 68K	notebooks/example_container.ipynb
688K	notebooks/gain_estimation.ipynb
188K	notebooks/low_level_corrections.ipynb
476K	notebooks/lstchain.ipynb
 56K	notebooks/mc_energy_distr.ipynb
304K	notebooks/read_LST1_data.ipynb
8,0K	notebooks/tutorial_gammalearn.ipynb
 20K	notebooks/utils_coords
```

A possible solution would be to accept only notebooks with striped output as done in another repo.

**Comment by rlopezcoto** [comment]
I agree, we could do also some cleanup on the already existing notebooks, I'm sure we can reduce their size more than one order of magnitude...

**Comment by rlopezcoto** [comment]
Reduced notebook size in #377. Please do not upload notebooks with size > 1 MB unless there is a good reason for it.

**Comment by vuillaut** [comment]
Sorry but the repo is still 90MB (try a git clone right now).
Cleaning the notebooks was required but does not erase the git history.

**Comment by rlopezcoto** [comment]
yeah, we discussed that in #377. To reduce the repo size we would need to delete the history and one would have to be very selective and careful about that... not sure if it is the way to go.

**Comment by MaxNoe** [comment]
> Sorry but the repo is still 90MB (try a git clone right now).

Repo sizes only ever increase unless you remove things from history, which will prevent any open merge requsts to be merged and people working on stuff will need to start over from the rewritten history.

Rewriting the history of the master branch in a repository like this, is a non-option I think.

Is 90 MB really a problem for cloning?

I see we want to minimize conda package / wheel / tar ball size, but the repo should not be such a great issue right?

If you have issues, you can always try with `git clone --depth=10` to only load info about the last 10 commits.

**Comment by vuillaut** [comment]
Yes, I was afraid the (only?) solution would be to rewrite the history.
I thought that maybe something like setting a limited depth was possible for the cloning.
If there is no acceptable solution, we can move on with this issue.

**Comment by rlopezcoto** [comment]
Since no actions are going to be taken, I'd propose to close this issue, is that ok with everybody?
