### ISSUE TITLE
AtributeError when running create_pedestal_file.py

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#168]
When trying to use create_pedestal_file.py I get this error:

```
Traceback (most recent call last):
  File "create_pedestal_file.py", line 60, in <module>
    pedestal = DragonPedestal(tel_id=telid, n_module=n_modules)
  File "/fefs/home/daniel.morcuende/software/cta-lstchain/lstchain/calib/camera/drs4.py", line 24, in __init__
    self.meanped = np.zeros((self.n_gain, self.n_pixels, self.size4drs))
AttributeError: 'DragonPedestal' object has no attribute 'size4drs'
```
Am I doing something wrong or the variable "size4drs" should be defined somewhere else?

**Comment by rlopezcoto** [comment]
Thanks for reporting @morcuended. It seems that with the global definition of `size4drs` the call inside `DragonPedestal` was not updated. Could you make a quick fix it @pawel21 or should I do it?

**Comment by pawel21** [comment]
Thank you @morcuended. I will fix it.

**Comment by rlopezcoto** [comment]
Solved in #169 by @pawel21

**Comment by rlopezcoto** [comment]
@morcuended can you confirm that the problem was solved? Thanks!

**Comment by morcuended** [comment]
Yes, now it's working properly
