### ISSUE TITLE
lstchain for real data analysis

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#181]
In its current state, a lot of MC information is used in several places to perform the reconstruction (e.g. telescope focal, pointing direction).
I will start looking more precisely into this.
In order to have a transparent use of the chain, the least bad option I see for now is to introduce `try/except` in required places depending on whether the data is MC or not.
To be discussed.

**Comment by misabelber** [comment]
Great Thomas! I've been thinking that this issue is becoming very necessary so it's a good idea to start working on it right away. Let me know if you need any help. Probably we will need also some notebooks & scripts which work with real data.

**Comment by rlopezcoto** [comment]
currently adapted and running on real data at all data levels. Probably some unification of scripts should be done, but since we would like to move them to `Tools` when the new ctapipe version comes out, it can be done at that time.
