### ISSUE TITLE
Low level calibration code not compatible with missing modules

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#182]
Hi,

it seems that the present low level calibrator is not compatible with missing modules (as in the data since a week). In the loops over modules one should not use the index over the global number of modules "range(0, n_modules)" but the number of the modules stored in event.lst.tel[1].svc.module_ids.

@pawel21 could you take care of the correction? (otherwise I can try to do it) 
This is necessary to get low level calibration files for the present data.

**Comment by pawel21** [comment]
Hi,
This is error in my code (works only for 265 modules)
I will fix it.

**Comment by pawel21** [comment]
I have checked my code using data from Run 1413 and I have discovered that code should work for less than 265 modules.
I have already implemented (in r0.py) to use correct number of modules (event.lst.tel[telid].svc.num_modules).

What kind of problem did you find?

**Comment by pawel21** [comment]
I found one possible scenario, when We can have problem with low level calib. 
This can happen when the number of module using to create pedestal file don't agree with number of modules from data run.

I have created PR #183

**Comment by rlopezcoto** [comment]
Solved in #209
