### ISSUE TITLE
CameraR0Calibrator not compatible with gain selection in EvB

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#191]
Hi,
this issue is just to notice that the present CameraR0Calibrator is not compatible with the EvB gain selection.  In order to make it compatible the code should verify at each event in the `event.lst.tel[tel_id].evt.pixel_status` which gain was selected for each pixel  (4=low-gain, 8=high-gain) and apply the correspondent baseline correction. @pawel21, I would say that this is not high priority but we must add it in the "to do" list

**Comment by maxnoe** [comment]
This is now implemented in ctapipe_io_lst
