### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#193]
Now that it will also be used by users, we should start including some documentation of the code, at the moment there is nothing.

**Comment by vuillaut** [comment]
Damn users... that's when things start falling apart.

**Comment by rlopezcoto** [comment]
what about retaking this issue and work on it a bit before the next release? 
We can get sphinx installed and add some documentation, even if it is not ready for the next release

**Comment by maxnoe** [comment]
Sphinx was setup
