### ISSUE TITLE
Pointing

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#195]
after #159 :
- update scripts to use `event.pointing` in reconstruction
- add required containers in DL1 file writing

**Comment by labsaha** [comment]
@morcuended has already a working script for using `event.pointing` for real data. He may think making a PR on that.

**Comment by vuillaut** [comment]
> @morcuended has already a working script for using `event.pointing` for real data. He may think making a PR on that.

Please consider contributing to #201 directly so we converge together to a working real data analysis :)

**Comment by labsaha** [comment]
Sure!
@morcuended Could you please see #201 how you can incorporate the `event.pointing` there?

**Comment by morcuended** [comment]
Working on it

**Comment by labsaha** [comment]
@morcuended Great! thanks.

**Comment by labsaha** [comment]
@vuillaut Drive report files are not being generated for each night separately. One drive report file may consist of data for several days. Perhaps shifters may need to close the application associated with the drive after the data taking to create a drive report for each night. In general, the application should save and dump the data automatically at 12 noon or after the data taking is over. Could you please talk to people at LAPP responsible for the drive to provide a suitable solution for this problem?

**Comment by vuillaut** [comment]
Seems solved, right @labsaha @morcuended ?

**Comment by labsaha** [comment]
Yes, Solved :)
