### ISSUE TITLE
Gain Selection

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#197]
gain selection is probably wrong.
See https://github.com/cta-observatory/ctapipe/issues/1166

Quick fix: go back to the manual gain selection that is still in lstchain but noted as deprecated.

**Comment by rlopezcoto** [comment]
Current threshold from the [config file](https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/data/lstchain_standard_config.json) should be 20.9 (phe) instead of 4094 (counts) until next ctapipe version is realeased (currently following v0.7.0)

**Comment by rlopezcoto** [comment]
this should be solved in `lstchain >= v0.6` that uses `ctapipe v0.8`
