### ISSUE TITLE
Bug in create_pedestal_file.py?

### ISSUE THREAD

**Issue by misabelber** [cta-observatory/cta-lstchain#204]
Hi @pawel21 ! I've been playing with real data and I've noticed that the current version of this script uses an old version of the function "time_lapse_corr" from LSTR0Corrections, the function now asks for two arguments  (event, tel_id), but the script is giving only the (event) and so is giving an error. I can correct this myself and do a PR but first I wanted to be sure that it makes sense.

**Comment by vuillaut** [comment]
Fixed in #203 but if you want to make a specific PR that's good.

**Comment by misabelber** [comment]
Thank you @vuillaut ! No problem, it can wait untl #203 is merged :)

**Comment by pawel21** [comment]
Hi @misabelber and @vuillaut , I was just working on it, but great that @vuillaut fixed it. I will also wait until #203 is merged :) After that, I would like add one small modification to create pedestal file.
