### ISSUE TITLE
AttributeError: 'NullR0Calibrator' object has no attribute 'tel_id'

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#207]
When using `calc_camera_calibration.py`, if no config file is passed, `NullR0Calibrator` is used by default.
In this case, the script fails because `'NullR0Calibrator' object has no attribute 'tel_id'`.

In some way, this is good, it reminded me I did not pass a config file.
However, the config file is optional and thus this is a bug.

I don't know if the best way to solve this issue is fixing `NullR0Calibrator`, having `LSTR0Corrections` as default or force the use of a config file.

**Comment by FrancaCassol** [comment]
Hi @vuillaut,
yes, in my version of the code I moved already the tel_id to the mother class, this is useful also when using MC data which do not need the corrections. Are you doing the change? @pawel21 ? me?

**Comment by pawel21** [comment]
Hi @FrancaCassol ,
If you already have this code, you can do it  or Could you show me your code? I also can do it
What do you prefer? :)

**Comment by FrancaCassol** [comment]
Hi @pawel21,
it is very simple, just move the tel_id trailet form the class  `LSTR0Corrections` to the mother class `CameraR0Calibrator`, so that it is seen bei all daughter classes

**Comment by rlopezcoto** [comment]
Was this solved by the latest commits of #167 @pawel21, @FrancaCassol?

**Comment by FrancaCassol** [comment]
Hi @rlopezcoto,
yes, this is solve
