### ISSUE TITLE
`torch` call from gammalearn breaking all builds

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#212]
?
very strange, nothing has changed... @mikael10j, @vuillaut, any idea? 
Otherwise we will need to comment it out since it is not needed for the working of the repo.

**Comment by vuillaut** [comment]
Funny (or not), it seems `pytest` behaviour has changed between v5.1 and v5.2 and is now finding modules that are not in the package... see #213

**Comment by rlopezcoto** [comment]
Perfect, thanks!

**Comment by rlopezcoto** [comment]
Solved in #214
