### ISSUE TITLE
Use uproot for reading root files

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/cta-lstchain#22]
You don't need root for that, just `pip install uproot`.

See https://github.com/scikit-hep/uproot/ and https://github.com/cta-observatory/mars_dl2_to_json/blob/master/mars_to_hdf5.py

**Comment by rlopezcoto** [comment]
I guess you are referring to the magic-lst scripts by @labsaha, right?

**Comment by labsaha** [comment]
@MaxNoe Good to know that `uproot` can be used to read mars classes.

**Comment by MaxNoe** [comment]
I just wanted to drop the info here that uproot can read MARS root trees efficiently into numpy arrrays and is a pure-python library.

That would remove the need for any conversion, you could just create a MAGIC `EventSource`
