### ISSUE TITLE
Open DL1a images with pandas

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#220]
I've been trying to open dl1a images which correspond to the `key="dl1/event/telescope/image/LST_LSTCam"`, like:
```
pandas.read_hdf(file, key="dl1/event/telescope/image/LST_LSTCam")
```
but it fails saying:
```
ValueError: Wrong number of items passed 1855, placement implies 1
```
So instead I have to use 
```
file = tables.open_file(file).root 
group = file.dl1.event.telescope.image.LST_LSTCam
images = [x['image'] for x in group.iterrows()]  
```

Do you know any workaround for this error and how to directly open this table in pandas?

**Comment by vuillaut** [comment]
You can't read images with pandas.

**Comment by vuillaut** [comment]
The only table you can open with pandas to my knowledge are the parameters and the simluation/run_config.

The rest is accessible using pytables.

**Comment by morcuended** [comment]
Thank Thomas! Something to bear in mind
