### ISSUE TITLE
Keep all events

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#237]
At the moment, only events passing the cleaning are kept.

We might prefer to keep all the calibrated images, regardless of cuts.
- Advantage: being able to reprocess images with other cleaning options + keeping these images for other purposes.
- Drawback: Usage is more prone to error. If a user loads images tables and parameters tables, they won't correspond to each other anymore and he'll need to use a `join` method on `event_id` (given than `event_id` are unique, which is not necessarily the case in case of merged files...)

**Comment by jsitarek** [comment]
If you keep all the images also the files gets considerably larger. 
Some way of keeping track or removed events might be however useful. Either a (reduced) header of the event, which however can still take considerably amount of space if we do it for all the events and push it until late stages of analysis, or some number of rejected events (but then we need one number for each step of analysis, and becomes really messy when information from different telescopes is merged)

**Comment by vuillaut** [comment]
Hi @jsitarek. Thanks for the input.

> If you keep all the images also the files gets considerably larger.

Yes that's true 

> Some way of keeping track or removed events might be however useful. Either a (reduced) header of the event, which however can still take considerably amount of space if we do it for all the events and push it until late stages of analysis, or some number of rejected events (but then we need one number for each step of analysis, and becomes really messy when information from different telescopes is merged)

Keeping only mc information of the not kept events will not take so much more space and should definitely be there imho.
Although, if you want general information about simulated events (such as total number), you may find already a lot in the `simulation/run_config` and `/simulation/thrown_event_distribution` datasets.

**Comment by vuillaut** [comment]
I believe this is not relevant anymore
