### ISSUE TITLE
Wrong order of cleaning levels in muon analysis

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#242]
https://github.com/cta-observatory/cta-lstchain/blob/4a8732d2d7789cf8af2a123e97153dcd0c424b92/lstchain/image/muon/muon_analysis.py#L131

It seems to me (looking at the code in fit_muon) that the picture and boundary thresholds are exchanged here.

**Comment by rlopezcoto** [comment]
right, soved in #244 
Thanks!
