### ISSUE TITLE
Write only images table (DL1a) if cleaning levels are set to 0

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#246]
Related to #237 

Provided cleaning levels are set to 0 in order to keep all the events, it does not make sense to calculate Hillas parameters. Thus DL1 output file should contain only images and pulse times tables in these cases.

**Comment by vuillaut** [comment]
Part of  https://github.com/cta-observatory/cta-lstchain/projects/1#card-30110590

Once this refactoring is done, DL1a and b will be done in different steps and thus the event selection by cleaning will be done after DL1a .
Although I was inclined to wait a bit to see things settling in ctapipe concerning DL1 processing tools and DL1 format to start this.

**Comment by morcuended** [comment]
Thanks for the clarification @vuillaut. Then, for the time being, should we implement in the `dl0_to_dl1.py` script the possibility of not storing the parameters table? Or do we just wait for ctapipe?
I thought we could add just a line before writing the table checking whether cleaning levels are 0 or not as we discussed in the past call.
