### ISSUE TITLE
Calculation of Alt Az from RA & DEC

### ISSUE THREAD

**Issue by labsaha** [cta-observatory/cta-lstchain#250]
I have an issue with the pointing positions in the **drive log** files. 
I tried to calculate the Altitude & Azimuth of the source from RA & DEC. I did it for the Crab. However, the value given in the drive log file is not matching with what I am getting. 
This is one of the lines from the drive report file
`Sun Nov 24 23:36:36 2019 1574638630 Az 88.3918 88.2437 88.7697 0.161279 El 42.6984 42.3357 42.8346 0.151659 RA 83.6296 Dec 22.0144`
**RA = 83.6296 deg
DEC = 22.0144 deg
Azimuth = 88.3918 deg
Altitude = 42.6984 deg ( if Elevation == Altitude)
Time:  24th November 23:36:36  2019 UTC**

Now using LaPalma site information 
Latitude: 28° 45′ 43″ N (28.761944 deg)
Longitude: 17° 53′ 24″ W (−17.89 deg)
Elevation: 2231.28 m
I am getting 
**Azimuth: 89.27785783 deg
Altitude:  49.87609883 deg**
You can see that they are not matching with what is mentioned in the drive report file. I am not sure if I am doing something wrong. I also checked with some online calculators as well and they are consistent with what I am getting with my script. Hence I have doubts about the numbers. 
If others can check this as well, that would be really great.

**Comment by morcuended** [comment]
It seems also that the date + hour time does not correspond to the given timestamp:

```
obs_time = Time('2019-11-24 23:36:36')
obs_time.unix
1574638596.0
```
wrt 1574638630 there are 34 secs difference

In addition, some times elevation goes above 90 deg. I guess it is a matter of how you define coordinates, but we should take it into account when handling these coordinates with astropy.

```
Mon Nov 25 02:18:31 2019 1574648340 Az -0.87099 -0.870999 -0.870999 0.00252021 El 94.7284 94.7226 94.7343 0 RA 83.6296 Dec 22.0144
```

**Comment by labsaha** [comment]
Yes, there is also an issue with the NTP time. I tried with also NTP time and that is not giving consistent results as well.

**Comment by morcuended** [comment]
According to the Drive team, the elevation coordinate values stored in the drive logs is actually the zenith angle, not the altitude itself. So this needs to be taken into account and corrected in the reco scripts

**Comment by vuillaut** [comment]
> So this needs to be taken into account and corrected in the reco scripts

Hi. Correct when reading the files please, don't change all the reco chain.

**Comment by labsaha** [comment]
Yes, we will wait for the drive team to provide more information such that we don't need to change the script quite often.

**Comment by morcuended** [comment]
> > So this needs to be taken into account and corrected in the reco scripts
> 
> Hi. Correct when reading the files please, don't change all the reco chain.

Yes, sure. Much better :)

**Comment by labsaha** [comment]
To avoid further confusion in the future, we may request the drive team to replace "El" with "Zd" in the drive file. We have to update this information in the `cta_io_lst` as well.

**Comment by rlopezcoto** [comment]
@labsaha @morcuended, just to make sure, you are working on a solution, right?

**Comment by labsaha** [comment]
@rlopezcoto  Yes. We are just waiting to get further information from drive people. We are in contact with them.

**Comment by morcuended** [comment]
The situation is quite unclear: we could change the definition to take into account that we are reading zenith angle, but still, sometimes there are values above 90 deg in Zd whose RA Dec coordinates point to a given source. When transforming the RA Dec coordinates to Alt Az (now considering the Zd instead) there is still a ~1deg offset.

What to do for the time being? We could fill the columns with zeros, write the interpolated values even knowing that the values might be not correct or not storing those columns at all.

What do you think?

**Comment by kosack** [comment]
> wrt 1574638630 there are 34 secs difference

Note that you have to be sure you are in the correct time scale (Time assumes UTC by default, if you don't specify it), for example TAI is currently ahead of UTC by 37 seconds, so are you sure you are not using TAI in ISO format in your logs?

**Comment by labsaha** [comment]
> Note that you have to be sure you are in the correct time scale (Time assumes UTC by default, if you don't specify it), for example TAI is currently ahead of UTC by 37 seconds, so are you sure you are not using TAI in ISO format in your logs?

Good to know this. Perhaps the drive team is using TAI. They may need to confirm what they are writing in the drive log.

**Comment by kosack** [comment]
Looking in the docs for White Rabbit, it seems to use TAI internally, if I understand correctly (not sure if the drives get their clock from white rabbit though)

**Comment by mdpunch** [comment]
> Looking in the docs for White Rabbit, it seems to use TAI internally, if I understand correctly (not sure if the drives get their clock from white rabbit though)

Hi Karl,

I commented this already in https://github.com/cta-observatory/cta-lstchain/issues/227

To quote myself from there:
> Okay, so to clarify, the White Rabbit is an extension of PTP, so it would use the same conventions as PTP. From https://en.wikipedia.org/wiki/Precision_Time_Protocol :
>>    PTP typically uses the same epoch as Unix time (start of 1 January 1970).[note 1] While the Unix time is based on Coordinated Universal Time (UTC) and is subject to leap seconds, PTP is based on International Atomic Time (TAI). The PTP grandmaster communicates the current offset between UTC and TAI, so that UTC can be computed from the received PTP time.

So yes, WR uses TAI.

**Comment by kosack** [comment]
Yes, I think it's best to always use TAI for times in CTA (except when needing to be human-readable perhaps), since requiring the hardware to do leap-second corrections is error-prone.  So in this case, if the drives are in TAI, it's the right thing - you should just read them correctly. Better yet, since these are logs (text?) you can even put the time scale in the output, like "2019-12-10 18:23:34.34 TAI", or call the field `time_tai_iso` (to show that it's a TAI in ISO string format)

**Comment by morcuended** [comment]
> Granted, it does say "UTC" in the log shown above, so something is not consistent...

UTC is not written in the log, it was just our interpretation. This needs to be clarified by Drive people

**Comment by moralejo** [comment]
> 
> UTC is not written in the log, it was just our interpretation. This needs to be clarified by Drive people

Daniel, could you clarify with the Drive team what exactly is written in their reports? We need to fix this as soon as possible to produce a new version of the Crab campaign DL1 data - other things (related to calibration) are also pending, but on their way to be solved.

**Comment by labsaha** [comment]
Hi @moralejo I wrote to the drive team before the holiday break. I didn't get any response yet if they fixed the problem. I'll write to them again to get the latest status.

**Comment by sliusar** [comment]
Since such "elevation" misuse persists also in the control software of the drive, on behalf of the TCU team I've also already sent few requests to the drive team (last time in mid-december) to rename el->zd everywhere to remove any confusion. It is better to make it ASAP so that people don't get use to it :)

**Comment by maxnoe** [comment]
Reading of drive files is now done in `ctapipe_io_lst` and there don't seem to be problems anymore since analysis works.
