### ISSUE TITLE
Getting DL1 for proton MC 

### ISSUE THREAD

**Issue by andres-baquero** [cta-observatory/cta-lstchain#251]
I'm trying to get DL1 files for MC protons using lstchain_mc_r0_to_dl1.py script. It works fine for gammas and gammas diffuse. But for protons I don't get the dl1_params_lstcam_key in the h5 files.

I must use the lstchain_mc_dl1ab.py script to get dl1_b ?

Thanks.

Best.

**Comment by andres-baquero** [comment]
The issue apparently is occurring writing metada:

AttributeErrorTraceback (most recent call last)
<ipython-input-6-2da714c0549d> in <module>
      4 config = {}
      5 
----> 6 r0_to_dl1(infile, output_filename=output_filename, custom_config=config)

<ipython-input-5-91be3d458868> in r0_to_dl1(input_filename, output_filename, custom_config, pedestal_path, calibration_path, pointing_file_path)
     42 
     43     metadata = global_metadata(source)
---> 44     write_metadata(metadata, output_filename)
     45 
     46     cal = load_calibrator_from_config(config)

/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/io/io.py in write_metadata(metadata, output_filename)
    451         for k, item in metadata.as_dict().items():
    452             if k in file.root._v_attrs and type(item) is list:
--> 453                 attribute = file.root._v_attrs[k].extend(metadata[k])
    454                 file.root._v_attrs[k] = attribute
    455             else:

AttributeError: 'NoneType' object has no attribute 'extend'

**Comment by rlopezcoto** [comment]
Hi @andres-baquero, do you have all the libraries up to date (tables, pandas, astropy?)?
Could you please share what are the versions of these libraries?

**Comment by andres-baquero** [comment]
Hi @rlopezcoto. I'm using the cta environment and lstanalyzer user

The library versions are:

pandas: 0.25.1
tables: 3.6.0
astropy: 3.2.2

Best.

**Comment by rlopezcoto** [comment]
Hi @andres-baquero, did you get to solve this? Could you please also check that the output file that you have been trying to create does not exist?

**Comment by jay3guru** [comment]
Hi @rlopezcoto, I tried again and now I get well the DL1 files for protons.

Thank you.

**Comment by andres-baquero** [comment]
Hi @rlopezcoto, I tried again and now I get well the DL1 files for protons.

Thank you.
