### ISSUE TITLE
Zenith angle coordinate wrongly named as elevation/altitude in drive_log files

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#262]
As it has already been mentioned the values that appear in drive_log files as *Elevation* are actually the zenith angle coordinate. There are two options here:

- Either Drive team calculates the actual altitude coordinate and our code remains as it is now.
- Or we calculate altitude coordinate out of those zenith angle values and Drive time change the naming to Zenith in the drive_log files to avoid further confusion. 

What is the preferred option?

**Comment by rlopezcoto** [comment]
I would go for the second option. That would leave all the files with the same value reported and the drive team should just name it properly

**Comment by labsaha** [comment]
Yes, I agree with Ruben. The drive team just put Zd instead of El

**Comment by labsaha** [comment]
#264

**Comment by rlopezcoto** [comment]
Solved in #264
