### ISSUE TITLE
Update protozfitsreader?

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#265]
As suggested by @MaxNoe in [ctapipe_io_lst](https://github.com/cta-observatory/ctapipe_io_lst/pull/22), protozfitsreader is already in an [older version](https://github.com/cta-sst-1m/protozfitsreader/releases/tag/1.5.0) than the one we are using

**Comment by rlopezcoto** [comment]
This should be moves to `ctapipe_io_lst`

**Comment by MaxNoe** [comment]
You can actually move issues on github.
