### ISSUE TITLE
why two `version.py` ?

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#267]
There are two files `version.py`, one in main dir and one in `lstchain`.

**Comment by rlopezcoto** [comment]
the full explanation comes from [this PR in ctapipe_io_lst](https://github.com/cta-observatory/ctapipe_io_lst/pull/22).

**Comment by MaxNoe** [comment]
We could go back to one, if the `lstchain/__init__.py` would not import submodules
