### ISSUE TITLE
Missing trigger info in DL1?

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#275]
Hi,
I would like to play with interleaved events using the DL1 files, but I could not find the trigger info in the event parameters, is it missing or am I  just looking in the wrong place? If it is missing, I would strongly suggest to add it so as to able to easily select the correct type of events.

**Comment by morcuended** [comment]
Hi @FrancaCassol,
I would say that right now it is missing. We only store images and parameter tables. Additionally, a few tables with telescope and subarray metadata.  Where should we place this trigger info? There is also the LST camera config information that could be included as well in DL1 files.

**Comment by vuillaut** [comment]
Ha yes you are right @FrancaCassol .
This info is in the `R0.tel` container which is not entirely saved (to not save the waveform).
I'll take care of it.

**Comment by FrancaCassol** [comment]
Hi @morcuended,
I would add it in the event parameter table, close to the event_id

**Comment by morcuended** [comment]
@FrancaCassol, are we keeping the interleaved events at DL1 right now? If not, are we planning to do it?

**Comment by FrancaCassol** [comment]
Yes, at least the flat field are there, I guess also the pedestal of not cut on the event intensity is performed
