### ISSUE TITLE
Error in dl1 to dl2 step when pointing info is missing

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#285]
Sometimes UCTS timestamp is missing in the latest runs, hence pointing coordinates cannot be interpolated nor added to the data stream. In these cases, `alt_tel` and `az_tel` are set to `NaN`. Later on, when running `lstchain_mc_dl1_to_dl2.py` over those runs with missing pointing info I get this error:
```
Traceback (most recent call last):
  File "/home/daniel.morcuende/software/cta-lstchain/cta-lstchain/lstchain/scripts/lstchain_mc_dl1_to_dl2.py", line 89, in <module>
    main()
  File "/home/daniel.morcuende/software/cta-lstchain/cta-lstchain/lstchain/scripts/lstchain_mc_dl1_to_dl2.py", line 79, in main
    dl2 = dl1_to_dl2.apply_models(data, cls_gh, reg_energy, reg_disp_vector, custom_config=config)
  File "/fefs/home/daniel.morcuende/software/cta-lstchain/cta-lstchain/lstchain/reco/dl1_to_dl2.py", line 396, in apply_models
    alt_tel = dl2['alt_tel'].values
  File "/home/daniel.morcuende/.conda/envs/mycta/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/daniel.morcuende/.conda/envs/mycta/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'alt_tel'
```
How can we overcome this? Should we throw away those problematic events in this second step by checking first whether dl2['alt_tel'].values are NaN?
Any suggestion?

**Comment by morcuended** [comment]
Maybe just filter out those events when producing DL1 files?

**Comment by morcuended** [comment]
Actually, there are cases in which `ucts_time` is available but `alt_tel` and `az_tel` are `NaN` either way:

![Screenshot_2020-02-14_17-17-59](https://user-images.githubusercontent.com/32680689/74548426-22510580-4f4e-11ea-99e8-df3143a15353.png)

While in lstchain_data_r0_to_dl1.py script pointing coordinates are interpolated if `ucts_time > 0`
Could the reason be that if the first event has no ucts_time the alt_tel and az_tel containers are not created and the next events will not have interpolated pointing coordinates even if the event has a proper timestamp?

**Comment by morcuended** [comment]
What about filtering out events with NaN `alt_tel`  within the function `apply_models` in `lstchain_mc_dl1_to_dl2.py`?

```
dl2 = dl1.copy()
dl2 = dl2[dl2['alt_tel'].notnull()]
```

**Comment by vuillaut** [comment]
So the columns go missing because some events have NaN values. This can be addressed I thing, either by removing these events or interpolating the pointing for them.
We could have a "cleaning" part after r0 to dl1 to deal with these kinds of problems in a global way (I guess interpolating would be a pain at event level).

**Comment by vuillaut** [comment]
@morcuended could you point me to a file with `nan` values in the pointing values please?
I'd like to test.

**Comment by morcuended** [comment]
Hi @vuillaut, I've been checking trying to find a DL1 file (subrun-wise) in which there are valid `alt_tel` values along with nan `alt_tel` values, but there is none. All the subrun files from runs in which there are UCTS missing info (for some of the subruns) either have all `alt_tel` and `ucts_time` right values or `alt_tel` column does not exist at all and `ucts_time` are set to `-1.000000e-09`. I did not find such an intermediate case with right and wrong values in the same subrun file.

Only when I merged them like this:

```
files = glob.glob(f"/fefs/aswg/data/real/DL1/{obs_date}/v0.4.3_v00/dl1_LST-1.1.Run0{run_number}*h5")
dfs = [pd.read_hdf(filename, key=dl1_params_lstcam_key) for filename in files]
df = pd.concat(dfs)
df = df.sort_values('event_id')
```
when pandas add those `NaN` to the places where coordinates are missing.

It seems to me that whenever just *one* event does not have proper `ucts_time`, `alt_tel` column is not even created for the rest of the events, regardless `ucts_time` values are correct or not.

This makes me think that probably we should add those `NaN` for `alt_tel` at DL1 level for those subruns in which `ucts_time` is not available for at least one event.

What do you think?

**Comment by morcuended** [comment]
Here is an example:

![image](https://user-images.githubusercontent.com/32680689/75025907-4b1c5200-549c-11ea-8b56-15ef9de5e342.png)

The vertical line indicates the last event_id having `alt_tel` info

**Comment by morcuended** [comment]
Here is another example in which UCTS info comes back at the end of the run:

![image](https://user-images.githubusercontent.com/32680689/75030221-f1b82100-54a3-11ea-8668-144be8754ba4.png)
