### ISSUE TITLE
Error when reading a simtel file with no defined telescope or camera name

### ISSUE THREAD

**Issue by yrenier** [cta-observatory/cta-lstchain#294]
Hello,
I produced simtel files where the name of some of the telescopes, some of the cameras was not defined. When I tried to convert them to dl1 I got several errors such as
`OSError: Table /instrument/telescope/camera/UNKNOWN already exists`

adding in the function lstchain.io.io.write_array_info() the following lines before the call to camera.to_table().write() close to the line 360 fixes the issue. 
```
if str(camera) is 'UNKNOWN':
    continue
```

**Comment by rlopezcoto** [comment]
Hi @yrenier, thanks for reporting! Was this error appearing the first time that you run your script? This looks like an overwriting error. In any case, let us have a look and maybe you could open a PR working it out as you proposed.

**Comment by yrenier** [comment]
The problems comes that it writes the info of the first camera in /instrument/telescope/camera/UNKNOWN
As the second camera has also no name defined, it tries to put the info in the same place and crashes.

**Comment by rlopezcoto** [comment]
Solved in #296
