### ISSUE TITLE
Naming of DL1 files and dealing with data streams

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#301]
We are producing DL1 files that are called:
`dl1_LST-1.1.Run02032.0192.fits.h5`
from files called:
`LST-1.*.Run02032.0192.fits.fz`
Do we want to keep the `fits` part in the dl1 output? 
Also, the `.1.` part is a bit misleading. I understand that when we call the code for the input file `LST-1.1.Run02032.0192.fits.fz`, all four streams (`LST-1.1.*`, `LST-1.2.*` `LST-1.3.*` and `LST-1.4.*`) are included in the analysis, but it would be great to distinguish between the processing of all four streams `LST-1.Run02032.0192.fits.fz` and individual ones `LST-1.1.Run02032.0192.fits.fz`

**Comment by vuillaut** [comment]
- concerning the `fits` part, the positive part is that it is giving a kind of provenance of the file. But if you think it's misleading, we can remove it.
- completely agree on removing the `.1.` in case of  merged streams

**Comment by morcuended** [comment]
+1 to remove the `.1.` part in the naming of DL1 files. The `.fits.h5` part was somewhat strange every time I saw it but I got used to it. If it is for provenance why not keep the `.fz` part as well? I would be in favor of removing that part, but not a strong opinion, just cosmetics.

**Comment by rlopezcoto** [comment]
No strong opinion on the `fits` part. For dealing with substreams, I'm not sure if we should deal with it from lstchain or on the reader part...

**Comment by moralejo** [comment]
I would remove both .1. and "fits".  
As for using it for provenance, do you mean @vuillaut that we would replace that part in case a DL1 (e.g. different cleaning) was produced from another DL1, rather than from a fits.fz raw file? Or when it is eventually produced from DL0? Seems misleading to me, and this will anyway be addressed by proper provenance at some point.

**Comment by vuillaut** [comment]
> I would remove both .1. and "fits".
> As for using it for provenance, do you mean @vuillaut that we would replace that part in case a DL1 (e.g. different cleaning) was produced from another DL1, rather than from a fits.fz raw file? Or when it is eventually produced from DL0? Seems misleading to me, and this will anyway be addressed by proper provenance at some point.

It's what I meant but I agree it can be misleading (and I sure hope we'll have a proper provenance at some point). We can also remove it no problem.
