### ISSUE TITLE
Dataset for code test

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#314]
How do I test that I don't break anything?

Is there some kind of integration test somewhere I can run?

**Comment by vuillaut** [comment]
Hi @MaxNoe 
There are some yes (you would probably have a lot to say about them and the coverage is far from 100%... but a basic core exists).
`pytest lstchain`  ?

If you have improvements to propose, they are always welcome ;-)

**Comment by MaxNoe** [comment]
I saw the unit tests ;)

I meant something like running an analysis (muon analysis) on a well known run and check how physics results change. ( I have a pic account and I'm waiting for the onsite account)

**Comment by vuillaut** [comment]
There is a core analysis running on MC only (in `lstchain/tests/test_lstchain`).
We still need to create small files to test on real data.

**Comment by rlopezcoto** [comment]
Hi @MaxNoe , regarding muons, there are some files here:
https://github.com/cta-observatory/cta-lstchain-extra/tree/master/muons/sample_data

but will not be very useful for the checks you are willing to do since they are the products of the analysis (also MC).

**Comment by rlopezcoto** [comment]
can this be closed @MaxNoe or do you want us to leave it open to define some real dataset to test the code? This may take a while...

**Comment by MaxNoe** [comment]
Yes, sure this was the idea.  Take some crab run with well known properties and use that as a benchmark dataset.

**Comment by rlopezcoto** [comment]
ok, I'll leave this open then, just updated the title

**Comment by morcuended** [comment]
Does this mean we need a dataset of each data level: R0, DL1 and DL2?

**Comment by rlopezcoto** [comment]
Well, we could consider getting a couple of small R0/DL1a files, and then for DL1b and DL2 we can have something larger. It was already discussed to open release some data for the full ASWG group, so this goal could be merged with that of this Issue

**Comment by maxnoe** [comment]
We now download password protected lst data for unit tests
