### ISSUE TITLE
DL2: units mismatch between reco_energy and log_reco_energy

### ISSUE THREAD

**Issue by dipierr** [cta-observatory/cta-lstchain#320]
I'm looking at some preliminary DL2 (run 1835) and I have noticed that reco_energy is in TeV, while log_reco_energy was calculated with energies in GeV (see plots).

![reco_energy](https://user-images.githubusercontent.com/17765148/78365312-39f85200-75bf-11ea-8e57-64cb4556f004.png)

![log_reco_energy](https://user-images.githubusercontent.com/17765148/78365247-1c2aed00-75bf-11ea-8855-fae74b9dd894.png)

**Comment by vuillaut** [comment]
Yes, that's historical but we should probably change that...

**Comment by rlopezcoto** [comment]
Solved in #325
