### ISSUE TITLE
Request to add the "alpha" parameter as additional field in the DL1 and DL2 containers.

### ISSUE THREAD

**Issue by dipierr** [cta-observatory/cta-lstchain#321]
It would be useful to access directly the "alpha" image parameter instead of calculating it in a separate step.

**Comment by MaxNoe** [comment]
This is probably a broader discussion, but there should be no source dependent parameters in anything up to and including DL3.

Source dependent analysis in general is something that should be avoided in my opinion.

**Comment by vuillaut** [comment]
That's indeed a broader discussion that we already had (and still have) in LST.
See PR #247

**Comment by rlopezcoto** [comment]
source-dependent analysis should be avoided in the case of stereo analysis, but for single-telescope analysis it is very useful.
`alpha` can be calculated from the already existing parameters, but it will be easier if it is just included...

**Comment by MaxNoe** [comment]
> but for single-telescope analysis it is very useful.

From my experience with FACT in the last 5 years I can only whole heartedly disagree.

**Comment by dipierr** [comment]
> This is probably a broader discussion, but there should be no source dependent parameters in anything up to and including DL3.
> 
> Source dependent analysis in general is something that should be avoided in my opinion.

I see your point. However for standard analysis we assume to know the position of the source, so this would allow to skip one step. Anyway as you said is a broader discussion.

**Comment by rlopezcoto** [comment]
yes, but #247 was about using source-dependent parameters for training/estimating parameters.

@MaxNoe: I agree that we can disagree 😄 
Seriously, it may be that it is not the case anymore with newer machine learning models, but source-dependent analysis was more performant for MAGIC single-telescope in the past. In any case, this possibility should be given for people to test (#247) and it should not harm to add one additional parameter to the DL2 files

**Comment by vuillaut** [comment]
In any case, there is currently a PR for that.

**Comment by rlopezcoto** [comment]
but no `alpha` parameter is calculated and filled at the DL2 level, right?

**Comment by SeiyaNozaki** [comment]
Now `alpha` parameter is not calculated in #247.
But I can easily install `alpha` to fill it in DL2, and actually this will also make me happy!
Is it fine to install it?

**Comment by rlopezcoto** [comment]
in my opinion, it will be useful as it was requested here, but if anybody opposes to include source-dependent parameters in DL2 files, we can discuss it

**Comment by DirkHoffmann** [comment]
IMHO, you should check early with CTAO/DPPS, what they foresee in the data model.

**Comment by MaxNoe** [comment]
The thing is, CTA does not forsee  source dependent analysis at all I think.

So, If you want to try out source dependent analysis (or already doing it), I am in favor of adding these parameters to DL2, **but** into their own group `source_dependent_parameters`. 
Or even `parameters_on` and `parameters_off_<N>` with a group `positions` defining which on/off positions were chosen.

Like this, it is clear which parameters assume a source positions and which do not (so are safe to be used for a source independent analysis).

**Comment by rlopezcoto** [comment]
at the moment, since we are performing ON observations, the `alpha` will be calculated with respect to the center of the camera

**Comment by MaxNoe** [comment]
Yes, at the moment. 

But let's seperate source dependent and independent parameters from the start and get it right. What's the harm?

I think we can only gain from this. Looking at the `if` statements in #247 checking which columns are dependent and which not, it would be much clearer to just:

```
image_params = pd.read_hdf('dl2.hdf', 'parameters')
image_params_source = pd.read_hdf('dl2.hdf',  'parameters_on')
```

**Comment by rlopezcoto** [comment]
sure, @SeiyaNozaki could you please add that to #247?

**Comment by mdpunch** [comment]
Hi all,
As the inventor of "alpha", I would just say that there is probably no need to calculate it and to keep it in the DL1/2, especially since it is dependent on the assumed source position (which can change if searching for a source, or if the bending corrections are revised).
If you have the centre-of-mass of the Hillas ellipse (x_cm,y_cm) and the angle of the ellipse major axis, then it is quite easy to calculate the alpha_source for a given source position (x_source, y_source).
So, as long as those three variables are kept you should only need a well-tested helper function to give alpha for each event, which just has three subtractions, a couple of ifs, and a call to atan2.
Good Luck,
Michael.

**Comment by moralejo** [comment]
Hi,

alpha itself is indeed easily obtained, but at DL2 we will also have higher-level source-dependent parameters including energy and gammaness. A separate container (or containers) for source-dep things is the best solution. And at that point, no matter how easy the calculation of Alpha is, why not include it?

We are aware that source-dependent analysis is not part of the CTA requirements. But unless CTA is like one of those countries where whatever is not compulsory is forbidden, we can define these additional data containers to help us with the commissioning. I for one will be fine with trashing them as soon as LST becomes a stereoscopic system.

**Comment by mdpunch** [comment]
Hi Abelardo,
Okay, I understand then why you want to include alpha for a default source position, since it goes with other variables.  Still would be good to have (as well) a standard routine for calculating alpha for another given position!

**Comment by MaxNoe** [comment]
@mdpunch already exists in ctapipe, or at least is a two liner with two other classical source dependent parameters (miss and disp):

https://github.com/cta-observatory/ctapipe/issues/1188#issuecomment-558213685

**Comment by rlopezcoto** [comment]
Added in #247
