### ISSUE TITLE
lstchain_muon_reconstruction is broken

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/cta-lstchain#327]
The script does not run on the current master branch due to several errors. (more coming up after fixing some).

**Comment by rlopezcoto** [comment]
`lstchain_muon_reconstruction.py` was the script used for MC muon analysis adapted to LST from [muon_reconsctruction](https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/tools/muon_reconstruction.py) on ctapipe. 
Now to process muon MC one has to use `lstchain_mc_r0_to_dl1.py` and then `lstchain_data_muon_analysis_dl1.py`, so `lstchain_muon_reconstruction.py` can go away
