### ISSUE TITLE
Scripts with misleading names

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#329]
At the moment I could identify:
`lstchain_data_muon_analysis_dl1.py` that contains *data* and it is used for data and MC analysis
`lstchain_mc_dl1_to_dl2.py` that contains *mc* and it is used for data and MC analysis

any other? My proposal is to eliminate the data/mc part of the name. I'll open a PR if nobody opposes.

**Comment by morcuended** [comment]
Same happens with `lstchain_mc_dl1ab.py`

**Comment by rlopezcoto** [comment]
same meaning that it is used for MC and Data analysis or that it should be eliminated?

**Comment by morcuended** [comment]
It can be used for both MC and data. @vuillaut, may you confirm?

**Comment by vuillaut** [comment]
Hi.
Ok for the two you mention @rlopezcoto.
For `lstchain_mc_dl1ab.py` in theory yes, that's true but it's still buggy right? I really wanted to wait for the DL1 writer to address this issue but maybe I will have a look already. Leave it as `mc` at the moment.

**Comment by FrancaCassol** [comment]
Hi,
please, change also the name of the module [dl0_to_dl1.py](https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/reco/dl0_to_dl1.py)

And we should also change the name of the calibration script [lstchain_data_create_calibration_file.py](https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/tools/lstchain_data_create_calibration_file.py) which works also for MC now

**Comment by rlopezcoto** [comment]
Addressed in #334
