### ISSUE TITLE
Moving of dl0_to_dl1.py to be a ctapipe Tool?

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#340]
Hi @vuillaut, @ruben, @morcuended,  

I am looking for implementing the treatment of the interleaved events in the r0_to_dl1.py  module.
The script start to be a bit crowded in input and output. I wonder if it is the right moment to move it to be a ctapipe Tool so to profit from its trailets support and perform the optimisation of the configuration file that we already mentioned some time ago... What do you think?

**Comment by vuillaut** [comment]
Hi @FrancaCassol 
ctapipe v0.8 is about to get released (it's been discussed this week in the core dev team).
If we are going for a major refactoring of r0 to dl1, then I would definitely do it with the integration of the DL1 writer.
No need to wait for the release to start working, however, we can do that in https://github.com/cta-observatory/cta-lstchain/tree/ctapipe_master and using https://github.com/cta-observatory/cta-lstchain/projects/3 for the organisation.
Let me know.

**Comment by rlopezcoto** [comment]
I agree with @vuillaut that probably the best moment to get this done is when implementing the new DL1 writer, although we need to wait at least for [it](https://github.com/cta-observatory/ctapipe/pull/1163) to be merged.
The [ctapipe_master](https://github.com/cta-observatory/cta-lstchain/tree/ctapipe_master) branch had lagged a bit behind... I just solved all the conflicts and now it should be up to date with  lstchain master.

Other points to consider for this branch are including astropy 4 as discussed in #324

**Comment by FrancaCassol** [comment]
Hi @vuillaut, @rlopezcoto,

Ok, I agree. I will implement it in the present module. But after the next release, let move to the master of ctapipe and better integrate with the ctapipe developments.
