### ISSUE TITLE
Errors when running notebooks

### ISSUE THREAD

**Issue by misabelber** [cta-observatory/cta-lstchain#35]
Hi @vuillaut,
As I mentioned in the pull request, I tried to run your notebooks and got some errors:

- **compare_chains**: It asks for the import of numpy.
When I import numpy, blocks 6 and 7 don't print anything.
- **disp_visualisation**: Block 3 gives error:
_---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-5b2aa46cf4b1> in <module>()
     26             dl1_container.fill_event_info(event)
     27             dl1_container.set_mc_core_distance(event, telescope_id)
---> 28             dl1_container.set_disp(event, telescope_id, hillas)
     29             disp_v2 = dl1_container.disp
     30 

TypeError: set_disp() takes 3 positional arguments but 4 were given_

In my version of set_disp() it requires as arguments source_pos and hillas, but here is called differently, being given the event, telescope_id and hillas. 

-**example_container**: Block 4 gives the same error due to set_disp:
_---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-3f7f4d11aba5> in <module>()
     34                 dl1_container.fill_event_info(event)
     35                 dl1_container.set_mc_core_distance(event, telescope_id)
---> 36                 dl1_container.set_disp(event, telescope_id, hillas)
     37                 dl1_container.mc_type = guess_type(infile)
     38 

TypeError: set_disp() takes 3 positional arguments but 4 were given_

**Comment by vuillaut** [comment]
Hi.

Thank you, I'm patching this right away.

Do you have errors with others notebooks too?

**Comment by vuillaut** [comment]
The notebook `compare_chains.ipynb` was just there for you to see that both chains are giving the same results.
I think we can delete it afterwards.
I'm making a PR with patch anyway.

**Comment by misabelber** [comment]
I only had trouble with those three, the lstchain one I modified it myself and works fine. Thank you!

**Comment by rlopezcoto** [comment]
Solved in #36
