### ISSUE TITLE
Use temporary directory for unit tests

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#350]
I had issues concerning clean up of files when a test failed.

We should use a temporary directory for the unit tests, not a fixed one.

**Comment by vuillaut** [comment]
Well... I personally like having the files when unit tests are failing precisely.

**Comment by MaxNoe** [comment]
For me this created a false positive and I lost half an hour investigating the issue I already had fixed.

**Comment by maxnoe** [comment]
Fixed in multiple PRs I think over the last couple of months
