### ISSUE TITLE
lstchain_data_r0_to_dl1.py should output the used *_t0 and *_counter values used

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#359]
It would be very convenient that lstchain_data_r0_to_dl1.py reports (in the text output) which "*_t0_*" and "*_counter_*" values it is using to calculate timestamps. In this way, when running over the first subindex (for which it is not necessary to provide the values in the command line, since they can be obtained from the data), a user could get the values for subsequent running of other subindices with, perhaps, faulty ucts info (for example). As of now there is as far as I know no simple way of getting those values.

Also: fix two typos "timestmap" in script's help

**Comment by morcuended** [comment]
Hi @moralejo, do you mean just print the used values? Should I do it in `reco/r0_to_dl1.py`? These initial values are the same for a given entire run.

Anyway, these values are available in the NightSummary files produced by Isidro.

**Comment by moralejo** [comment]
> Hi @moralejo, do you mean just print the used values? Should I do it in `reco/r0_to_dl1.py`? These initial values are the same for a given entire run.

you can print them only in case they are not user-supplied.

> 
> Anyway, these values are available in the NightSummary files produced by Isidro.

Yes, I know OSA takes them from there. But printing them makes it easier for a user to process other subruns beyond the first one, without having to look for the info somewhere else.

**Comment by morcuended** [comment]
> you can print them only in case they are not user-supplied.

I've implemented what I think you're suggesting, but I don't know if I completely got you. These values can only be printed out if they are provided by the user (or OSA in this case). Otherwise, we do not have such info available. May you have a look, please?

**Comment by morcuended** [comment]
Addressed in #362
