### ISSUE TITLE
Can we remove the magic-lst folder?

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#364]
[magic-lst](https://github.com/cta-observatory/cta-lstchain/tree/master/lstchain/magic-lst) was originally thought to contain some of the tools to be develop to perform a joint analysis between LST and MAGIC to evaluate the LST performance.
The efforts have since some time ago moved to the creation of a separate [reader for MAGIC data](https://github.com/cta-observatory/ctapipe_io_magic) and a separate repo for the ctapipe-based analysis, so I would suggest removing this folder. @dipierr, @YusukeSuda, what do you think?

**Comment by YusukeSuda** [comment]
Hi @rlopezcoto, I don't see any problem. So, green light from my side.

**Comment by dipierr** [comment]
Yes @rlopezcoto, I agree, it can be removed to avoid confusion.

**Comment by rlopezcoto** [comment]
Soved in #374
