### ISSUE TITLE
DL2 files including images and DL1 parameters and tables

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#372]
By processing some DL1 files, I realized that the size was too large, when I checked their containment, they had the following datasets:
```
'dl1/event/subarray/mc_shower',
 'dl1/event/subarray/trigger',
 'dl1/event/telescope/image/LST_LSTCam',
 'dl1/event/telescope/parameters/LST_LSTCam',
 'dl2/event/telescope/parameters/LST_LSTCam',
...
```
All the `dl1/*` should have been removed at DL2 level, specially the images that are the ones increasing the size of these files by a large amount. I reproduced this with `v0.4.5` and `master`. I'll look into solving it.

**Comment by MaxNoe** [comment]
> All the dl1/* should have been removed at DL2 level

Removed? Or never written?

A new file is created, isn't it?

**Comment by vuillaut** [comment]
This is not actually a bug.
The DL2 files are created by entirely copying the DL1 files. Same goes for the parameters.
It was done this way for easier performance analysis and debugging but needs to be changed with the adoption of a consistent data model.

**Comment by rlopezcoto** [comment]
but in the past they were _not_ written, when did that change?

**Comment by vuillaut** [comment]
Hum no I think they always were if you started from DL1 files...
If not I kept track of the changes.

**Comment by vuillaut** [comment]
I think the difference is that you might have started from merged files DL1 before. And we usually striped the images at merging.

**Comment by morcuended** [comment]
> but in the past they were _not_ written, when did that change?

For the first production, we ran dl1ab script stripping away the images before run dl1_to_dl2 script

**Comment by rlopezcoto** [comment]
I produced DL2 files myself from DL1 full files (with images) using v0.3.1 and `lstchain_mc_dl1_to_dl2.py` (with the modification not to include the pointing info) and they do not have images...

**Comment by rlopezcoto** [comment]
I double checked and have the individual files processed from DL1 files with images. I had to do a modification of the `lstchain_mc_dl1_to_dl2.py` to be able to process them using real data, but it was very minor
Anyways... do we agree that DL2 files should *not* contain images?

**Comment by rlopezcoto** [comment]
@vuillaut or @morcuended since you have been working already with this part of the code, could you propose some changes there?

**Comment by MaxNoe** [comment]
> Anyways... do we agree that DL2 files should not contain images?

By definition, yes

**Comment by morcuended** [comment]
> @vuillaut or @morcuended since you have been working already with this part of the code, could you propose some changes there?

I don't have so much experience with that part of the code

**Comment by rlopezcoto** [comment]
> If that's a problem for debugging, we should add some code that makes merging data levels in memory easier, not creating files that contain both data levels.

I'd like to propose as temporary solution that the `lstchain_dl1_to_dl2` script does *not* write images by default (we can leave it as an option, although I would rather eliminate it)

**Comment by vuillaut** [comment]
I agree it should be removed from DL2, I personally won't have time to look into that before next week.
