### ISSUE TITLE
Missing import in io/__init__.py needed by the script lstchain_merge_hdf5_files.py

### ISSUE THREAD

**Issue by dipierr** [cta-observatory/cta-lstchain#373]
I'm using the script to merge hdf5 files and to get it working I had to add the line _'smart_merge_h5files'_, in the import list in lstchain/io/__init__.py , because before this I was getting the error: " _ImportError: cannot import name 'smart_merge_h5files' from 'lstchain.io'_ "

**Comment by MaxNoe** [comment]
Can you open a PR with the fix? And maybe add a test for this script?

It does not seem to be included in the `lstchain/scripts/tests/test_scripts` and this is likely why the function was missed during the refactoring in #127

**Comment by rlopezcoto** [comment]
It is actually tested, but the call is different:
https://github.com/cta-observatory/cta-lstchain/blob/98e270b2c9d8f37401722d1aacc0e3ca07f3833b/lstchain/io/tests/test_io.py#L37

**Comment by rlopezcoto** [comment]
@dipierr you can solve this by adding `smart_merge_h5files` to 
[lstchain/io/__init__.py](https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/io/__init__.py)

**Comment by MaxNoe** [comment]
@rlopezcoto I meant that it is not tested as command line script

**Comment by rlopezcoto** [comment]
Solved in #376
