### ISSUE TITLE
Why different formats for pedestal and calibration files?

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#379]
At the moment we write pedestal `fits` files and calibration/time_calibration `hdf5` files, is there any reason to be using different formats @FrancaCassol @pawel21?

**Comment by MaxNoe** [comment]
Also: why muon results in fits and image parameters in hdf5 for the same script?

**Comment by rlopezcoto** [comment]
Yeah, have to work on it...
#245

**Comment by pawel21** [comment]
@rlopezcoto 
No, there is no reason.
I agree, will be better to have one format of calibration file.
I can do it, I will improve code to use hdf5 file.

**Comment by DirkHoffmann** [comment]
Remember that the EVB (via ACTL library) is only able to read FITS files, no HDF5. Or you generate little-endian binary, which is much safer anyway.

**Comment by vuillaut** [comment]
> Remember that the EVB (via ACTL library) is only able to read FITS files, no HDF5. Or you generate little-endian binary, which is much safer anyway.

Why EVB should need to access offline reconstruction data?

**Comment by pawel21** [comment]
@DirkHoffmann Good point, I forgot.

@vuillaut EVB need this file to do online baseline correction (in fits file we store offset values for each capacitor).
We should update pedestal file in EVB, at least from time to time.
@DirkHoffmann is it possible to read HDF5 file in EVB using another library?

**Comment by MaxNoe** [comment]
HDF5 is a standardized file format. It shouldn't and doesn't matter which python library you use to write an hdf5 file for it to be readable by the libhdf5.

I don't know how easy it would be to add reading of hdf to the EVB, but which python library is used is not important for that.

Actually, both h5py and tables are wrappers around the libhdf5 C code.

**Comment by DirkHoffmann** [comment]
On Apr 28, Paweł Gliwny wrote:

> @DirkHoffmann is it possible to read HDF5 file in EVB using another library?

No, sorry, we do not want to introduce another library dependency in the online software.

**Comment by rlopezcoto** [comment]
Hi @DirkHoffmann, is there any strong reason for that? If I'm not wrong, to read FITS files you also need the dependency of `fitsio` (C++ ?) and hdf5 is becoming pretty standard for low level data in CTA.

**Comment by FrancaCassol** [comment]
Hi @pawel21,
 
> I agree, will be better to have one format of calibration file.
> I can do it, I will improve code to use hdf5 file.

I would even go further. Why having two files for the drs4 calibration? One could collect all the drs4 calibration coefficients in one single h5 file. They should be in separate tables: baseline correction, time lapse correction (now hardcoded in lstchain and not stored in the data), time flat-fielding.  
For the last, it should be possible to copy the values from a reference drs4 calibration file if no asked to calculate them (hopefully soon all this will be more efficiently stored in a data base)

**Comment by MaxNoe** [comment]
@FrancaCassol this could also be done with fits files, multiple binary table extensions.

**Comment by FrancaCassol** [comment]
yes @MaxNoe, but I agree with @rlopezcoto that is better to keep only one format

**Comment by pawel21** [comment]
@FrancaCassol good idea. Do you think, we should have one script to create file with coefficients for pedestal, time correction and flat-field correction or have script to merge those coefficients into one file?

I think we can leave the script to create pedestal file in `fits` format only for EVB.
Let's create new script to create pedestal file in hdf5 format and modify code in 'r0.py' to use 'hdf5' file. I can try do it.

**Comment by rlopezcoto** [comment]
having two different scripts to calculate the pedestal may be prone to more errors, I think that whatever solution we decide, we should stick to only one file. I'd still like to see what are the reasons not to be willing to include `libhdf5` into the EVB dependencies, @DirkHoffmann?
In any case, do we really need one new script to create pedestal files in `hdf5` or can you include it in the `lstchain_data_create_drs4_pedestal_file.py`, @pawel21 ?
@FrancaCassol I think it that is a good idea, but if we would like to move all these scripts to `Tools`, that might be the right moment to merge the different calibration files.

**Comment by DirkHoffmann** [comment]
I only wanted to make the point not to introduce incompatibilities with preexisting upstream software. 

If you want to propose an implementation change on EVB, please file a request [on LST-DAQ redmine](https://forge.in2p3.fr/projects/idaq/issues) with the developers. I anticipate (or remind you, from earlier discussions) that the ideal format for the pedestal configuration will be Intel (low-endian) binary. 
Thanks

**Comment by FrancaCassol** [comment]
I would not make deep modifications in the code flow. I would suggest to keep the pedestal script like it is, just add the writing of the output in h5 format (and keep the fit format if really the EvB can not read  h5 file,  @DirkHoffmann could you please verify this point?). Then, add to this script also the writing of the time lapses coefficients that can be given as trailets to the CameraR0Calibrator (you can put as default the current values).
Finally, just change the time flat-fielding script so that it writes its output in the same h5 file, the values are either calculated or copied from the given reference file (for easy book keeping I would suggest to add one parameter with the run number from which the values are calculated).

**Comment by pawel21** [comment]
I can modify script `lstchain_data_create_drs4_pedestal_file.py` to save file in `h5df` format (default option) and add option to save in `fits` format. OK?

**Comment by MaxNoe** [comment]
> I anticipate (or remind you, from earlier discussions) that the ideal format for the pedestal configuration will be Intel (low-endian) binary.

Nearly every binary format will be better suited for this than an non-self describing, non-standardized memory dump to disk.

 Especially for something that is read once and then kept in memory and where meta-information like which dataset and which software version was used to compile these calibration constants are as important as for low-level data calibration.

**Comment by MaxNoe** [comment]
Here is a small example, writing using pytables:

```python
import numpy as np
import pandas as pd
import tables


df = pd.DataFrame({
    'x': np.random.normal(size=10),
    'N': np.random.poisson(10, size=10)
})
print(df)

with tables.open_file('test.hdf5', 'w') as f:
    g = f.create_group('/', 'data')
    f.create_table(g, 'table', df.to_records(index=False))
```

Reading in cpp using the `libhdf5`, compile with:
```
$ g++ -lhdf5 -lhdf5_cpp -o read_hdf5 --std=c++11 read_hdf5.cpp 
```

```cpp
#include <iostream>
#include <string>
#include <vector>
#include <cstdint>
#include "H5Cpp.h"


// declare a struct with the fields in the hdf5 file
struct Data {
    double x;
    int64_t N;
};


int main() {
    // create an HDF5 data type for the struct
    H5::CompType h5_type(sizeof(Data));
    h5_type.insertMember("x", HOFFSET(Data, x), H5::PredType::NATIVE_DOUBLE);
    h5_type.insertMember("N", HOFFSET(Data, N), H5::PredType::NATIVE_INT64);

    // open the file in read only
    H5::H5File file{"test.hdf5", H5F_ACC_RDONLY};

    // open the dataset 
    H5::DataSet dataset = file.openDataSet("data/table");

    // get number of dimensions (should be 1)
    H5::DataSpace dataspace = dataset.getSpace();
    int n_dims = dataspace.getSimpleExtentNdims();
    std::cout << "n_dims: " << n_dims << std::endl;

    // get shape (should be (10, ))
    std::vector<hsize_t> shape(n_dims);
    dataspace.getSimpleExtentDims(shape.data());
    
    std::cout << "shape: (";
    for (const auto& l: shape) {
        std::cout << l << ", "; 
    }
    std::cout << ")" << std::endl;

    // get number of rows (should be 10 again)
    hsize_t n_selected = dataspace.getSelectNpoints();
    std::cout << "Selected points: " << n_selected << std::endl;

    // create a vector for the data to be read and read it
    std::vector<Data> data(n_selected);
    dataset.read(data.data(), h5_type, dataspace);

    // print data
    for (const Data& row: data) {
        std::cout << "x: " << row.x << ", N: " << row.N << std::endl;
    }

    return 0;
}
```

**Comment by jsitarek** [comment]
some thoughts from my side. Having to maintain two formats of pedestal files is certainly not preferable. But if we have to do it and have hdf5 for offline analysis and fits for EVB instead of recreating the file with one macro run in two different formats I think a better solution would be to have a macro that converts from one format to another. Otherwise you need to make sure that you run the pedestal macro in the same version, with the same settings and over the same data to create it in a different format. Either way if hdf5 cannot be used in EVB I'm not that convinced that it would make sense to use this format for pedestal values in offline analysis. The gain of having the same type of files for different corrections in offline analysis in my view does not win with the disadvantage of having two different formats for doing exactly the same.

**Comment by moralejo** [comment]
> Also: why muon results in fits and image parameters in hdf5 for the same script?

I agree it would be better to have more homogeneous  choices across lestchain. But probably it is better to postpone all this to the next-to-next major release (0.6), since some of the changes would have to be re-revised when we move to using ctapipe 0.8.

On the other hand: anyone can suggest a nice gui for exploring hdf5 which has plotting/histogramming capabilities? (something like TopCat for FITS).

**Comment by MaxNoe** [comment]
@moralejo I don't know of any tool with nice plotting support

I for myself just fire up a jupyter notebook and use pandas / matplotlib

**Comment by moralejo** [comment]
> @moralejo I don't know of any tool with nice plotting support
> 
> I for myself just fire up a jupyter notebook and use pandas / matplotlib

Yes, that is what I do as well. Not too complicated indeed, just wondered if there was something more intuitive for quick plotting.
