### ISSUE TITLE
Observed data test file

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#392]
Several issues in the last time were about stuff that was broken for observed data, although all tests were passing.

I think we desperately need a smallish test data file.

Is there something available? Can files be truncated to be small enough in a save way or are there subruns with only a couple of events?

**Comment by rlopezcoto** [comment]
I had a quick check and found e.g.:
`LST-1.3.Run02008.0201.fits.fz` -> `54.4 MB`. It is a data run and probably we can find some subrun with less events.

Also in the same run:
`LST-1.2.Run02006.0004.fits.fz ` -> `11.1 MB`. It is a calibration subrun.

They can be used, but *cannot* be made public. We need to have an approval for that

**Comment by rlopezcoto** [comment]
Related to #314?

**Comment by MaxNoe** [comment]
We don't need to make it public. If it would be reachable on a password protected server, we could download it on travis with their secrets management. (And skip the tests for if the file is not present, so users without the file don't see failures).

**Comment by rlopezcoto** [comment]
is 50 MB ok? (keep in mind that this is one stream, so test it properly we would need 4). If we find a suitable subrun, we can discuss about making it public

**Comment by MaxNoe** [comment]
50 MB should not be a problem for travis to download.

**Comment by MaxNoe** [comment]
Just to keep this up to date: I asked Jordi to setup a new endpoint at the lst pic data web server for this test data, so we can download it (password protected) on travis.

**Comment by maxnoe** [comment]
We have this setup since a long time
