### ISSUE TITLE
error converting MC files where IGNORE_TELESCOPEs option from simtel was used

### ISSUE THREAD

**Issue by yrenier** [cta-observatory/cta-lstchain#406]
I have corsika files with 7 telescopes and used IGNORE_TELESCOPEs=1,2,7 to keep only the LSTs (telescopes 3, 4, 5 and 6) during the sim_telarray simulations.
When I try to get dl1 datafiles using lstchain_mc_r0_to_dl1, I get an error:

```
/usr/bin/python3 /home/yves/ctasoft/cta-lstchain/lstchain/scripts/lstchain_mc_r0_to_dl1.py --infile /home/yves/Downloads/proton_run170_South.simtel.gz --outdir /home/yves/Downloads --config=lstchain/data/lstchain_own_prod_config_PMT.json
/home/yves/.local/lib/python3.7/site-packages/ctapipe/io/simteleventsource.py:164: UserWarning: Backseeking to start of file.
  warnings.warn('Backseeking to start of file.')
USING FILTERS:  Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None)
0
Traceback (most recent call last):
  File "/home/yves/ctasoft/cta-lstchain/lstchain/scripts/lstchain_mc_r0_to_dl1.py", line 48, in <module>
    main()
  File "/home/yves/ctasoft/cta-lstchain/lstchain/scripts/lstchain_mc_r0_to_dl1.py", line 44, in main
    r0_to_dl1.r0_to_dl1(args.infile, output_filename=output_filename, custom_config=config)
  File "/home/yves/ctasoft/cta-lstchain/lstchain/reco/r0_to_dl1.py", line 308, in r0_to_dl1
    write_subarray_tables(writer, event, metadata)
  File "/home/yves/ctasoft/cta-lstchain/lstchain/io/io.py", line 570, in write_subarray_tables
    writer.write(table_name="subarray/trigger", containers=[event.dl0, event.trig])
  File "/home/yves/.local/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 279, in write
    self._append_row(table_name, containers)
  File "/home/yves/.local/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 253, in _append_row
    value = self._apply_col_transform(table_name, colname, value)
  File "/home/yves/.local/lib/python3.7/site-packages/ctapipe/io/tableio.py", line 115, in _apply_col_transform
    value = tr(value)
  File "/home/yves/ctasoft/cta-lstchain/lstchain/reco/utils.py", line 370, in expand_tel_list
    pattern[tel_list] = 1
IndexError: index 5 is out of bounds for axis 0 with size 5
```

The problem come the r0_to_dl1() function in lstchain/reco/r0_to_dl1.py: 
```
tel_list_transform = partial(utils.expand_tel_list,
                                         max_tels = len(event.inst.subarray.tel) + 1,
                                         )
```
as event.inst.subarray.tel is [3, 4, 5, 6] so max_tels is at that point set to 4. and cause the error in  expand_tel_list when trying to set telescope 5 or 6:
```
    pattern = np.zeros(max_tels).astype(bool)
    pattern[tel_list] = 1
```
To fix it, one just hast to modifify the r0_to_dl1() function in lstchain/reco/r0_to_dl1.py to: 
```
tel_list_transform = partial(utils.expand_tel_list,
                                         max_tels = max(event.inst.subarray.tel) + 1,
                                         )
```
Should I create a PR for this snall change ? or would it be better to just add it in an on-going PR (I can include it in #338 ) ?

**Comment by MaxNoe** [comment]
Please open single PRs for single fixes, that makes it much easier to review them and get them merged fast.

**Comment by yrenier** [comment]
done

**Comment by MaxNoe** [comment]
I'm a little curious, as the same issue might also be in ctapipe somewhere.

How and why did you produce those corsika files? What are the seven telescopes?

**Comment by yrenier** [comment]
the corsika files are the one of the 2 Magic + 4 LST + 1 MST production at LaPalma (`/vo.cta.in2p3.fr/MC/PROD4/LaPalma/gamma/corsika/1897/Data`). 
I can upload somewhere a simtel file which triggers the problem if you want (~500Mo).

**Comment by MaxNoe** [comment]
Interesting. I will try to reproduce a small file with some telescopes set to ignore for testing, thanks.

**Comment by MaxNoe** [comment]
Just adding  `ignore_telescopes = 1, 4` to the simtel config, right?

**Comment by yrenier** [comment]
i used  `sim_telarray ...  -C ignore_telescopes=1,2,7 ...`, but I think `ignore_telescopes = 1, 4` in the config file should trigger the problem too

**Comment by yrenier** [comment]
but you need  `ignore_telescopes=1,2,7` if you want to keep only LST telescopes

**Comment by MaxNoe** [comment]
I was about to simulate a simple lst run and throw away to LSTs ;)

**Comment by yrenier** [comment]
I found a bug in ctapipe trigger when ignore_telescopes option has been used.
in SimTelEventSource.__generator() photo_electron_image is not filled properly. Once should use:
```
                mc.photo_electron_image = (
                    array_event
                    .get('photoelectrons', {})
                    .get(tel_id - 1, {})
                    .get('photoelectrons', np.zeros(n_pixels, dtype='float32'))
                )
```

**Comment by MaxNoe** [comment]
Could you open an issue over at ctapipe?

**Comment by yrenier** [comment]
I'm doing it now. Also, should I close the issue as the fix was merged ?
