### ISSUE TITLE
image extractor config

### ISSUE THREAD

**Issue by yrenier** [cta-observatory/cta-lstchain#422]
Looking at the default config ( in lstchain/data/lstchain_standard_config.json) we have:
```
  "image_extractor": "LocalPeakWindowSum",
  "image_extractor_for_muons": "GlobalPeakWindowSum",
  "image_extractor_config": {},
  "LocalPeakWindowSum":{
     "window_shift": 4,
     "window_width":8
    },
  "GlobalPeakWindowSum":{
     "window_shift": 4,
     "window_width":8
    },
```
In load_image_extractor_from_config() we have:
```
def load_image_extractor_from_config(custom_config):
    config = replace_config(get_standard_config(), custom_config)
    conf = Config({config['image_extractor']: config['image_extractor_config']})
    image_extractor = getattr(extractor, config['image_extractor'])
    return image_extractor(conf)
```
so the image extractor is loading the extractor settings from the `image_extractor_config` parameter in the config. Also changing `window_shift` or `window_width` in `LocalPeakWindowSum` has no effect to the calibrator obtained by load_calibrator_from_config() which I find very confusing.

What is the expected behavior:
- put the desired `window_shift` and/or `window_width` in `image_extractor_config` ? In that case ` LocalPeakWindowSum` and `GlobalPeakWindowSum`should be removed to avoid confusion.
- the settings of the extractor selected by `image_extractor` should be used ? In that case there is a bug and load_image_extractor_from_config() should be:
```
def load_image_extractor_from_config(custom_config):
    config = replace_config(get_standard_config(), custom_config)
    image_extractor_sel = config['image_extractor']:
    conf = Config({image_extractor_sel: config[image_extractor_sel]})
    image_extractor = getattr(extractor, config['image_extractor'])
    return image_extractor(conf)
```

**Comment by vuillaut** [comment]
Hi.
I agree, the config looks wrong.
I would expect (that's what was intended originally I think at least):
```
 "image_extractor": "LocalPeakWindowSum",
  "image_extractor_config": {
     "window_shift": 4,
     "window_width":8   
},
```

Plus, looking at the code, I don't see where the parameters of the `image_extractor_for_muons` can be adjusted. So the standard parameters are always used.
Actually, I think that the extractor itself is not read from the config.
```
        r1_dl1_calibrator_for_muon_rings = LSTCameraCalibrator(calibration_path = calibration_path,
                                                               time_calibration_path = time_calibration_path,
                                                               extractor_product = config['image_extractor_for_muons'],
                                                               gain_threshold = Config(config).gain_selector_config['threshold'],
                                                               config = Config(config),
                                                               allowed_tels = [1],)
```
the extractor_product should be extracted by a function similar to `load_image_extractor_from_config`

**Comment by moralejo** [comment]
I am pretty sure the muons are not extracted with Local Peak, I introduced a check of the mean charge in "a ring beyond the ring", and the values are pretty low, certainly not those from Local Peak extractor.  The (intended) Global Peak must have been used, or at most (by mistake), the Neighbor Peak, if that is the default and the config is not working. I can't tell if the window parameters are those in the input card or not.

**Comment by moralejo** [comment]
> 
> Plus, looking at the code, I don't see where the parameters of the `image_extractor_for_muons` can be adjusted. So the standard parameters are always used.
> Actually, I think that the extractor itself is not read from the config.

Do you mean that this does not work? :
https://github.com/cta-observatory/cta-lstchain/blob/44b90a44428e66ecff8a8383a5a305664f0d386a/lstchain/reco/r0_to_dl1.py#L252-L257

**Comment by moralejo** [comment]
I checked following the same steps as in r0_to_dl1 that the extractor type is properly passed (to the muons, but it is the same for showers)

Then, below, it seems the config is passed to ctapipe; the config contains the width a shift for the corresponding extractor _types_:

https://github.com/cta-observatory/cta-lstchain/blob/44b90a44428e66ecff8a8383a5a305664f0d386a/lstchain/calib/camera/calibrator.py#L72-L76

I do not understand if the issue is raised because of the somewhat strange syntax in the config file, or whether you have seen that the  config passed to ctapipe above won't be used

**Comment by yrenier** [comment]
The issue I initially reported is when using the load_calibrator_from_config() function which is used in r0_to_dl1() to analyze MC.
In that case `window_width` and `window_length` are presently taken from image_extractor_config which is very confusing given the config file which defines them elsewhere.

**Comment by moralejo** [comment]
Ah, ok, all I said applies to the real data. For the MC the muon analysis is separate from the shower analysis. 
So, can you tell what has been used for the processing of MC showers? Yesterday I saw a plot from A. Baquero at UCM showing an apparently worse correlation in 0.5.1 w.r.t. 0.3.1 of time gradient and impact parameter for gammas, and I am wondering if this may be related (e.g. if too wide a window is used in MC, pulse times would be less reliable)

**Comment by vuillaut** [comment]
Ok sorry, the `window_width` and `window_shift` is well read from the config
```
  "GlobalPeakWindowSum":{
     "window_shift": 4,
     "window_width":8
    },
```

However, the current config is very confusing (as commented by @yrenier) in my opinion. *And* bugged for the MC integration. I'm making a PR proposing changes.

**Comment by moralejo** [comment]
So the data with 0.5.1 have been processed as intended, true? 

And what were the used pulse integration settings for the MC?

**Comment by moralejo** [comment]
I agree it is clearer if each image extractor (not each image extractor _type_) has its own settings in the config file).

**Comment by vuillaut** [comment]
> So the data with 0.5.1 have been processed as intended, true?

yes 😅

> And what were the used pulse integration settings for the MC?

`{'LocalPeakWindowSum': {'window_shift': 4, 'window_width': 8}`

**Comment by vuillaut** [comment]
Sorry, I checked after making the corrections 🤦 
Actually, the MC have been analysed with an integration window of **(3,7)**
```
In [1]: from lstchain.calib import load_calibrator_from_config, load_image_extractor_from_config
In [2]: from lstchain.io.config import get_standard_config, read_configuration_file
In [3]: im = load_image_extractor_from_config(get_standard_config())
In [4]: im.window_shift
Out[4]: 3
In [5]: im.window_width
Out[5]: 7
In [6]: im
Out[6]: <ctapipe.image.extractor.LocalPeakWindowSum at 0x126cb3550>
```

**Comment by moralejo** [comment]
> Sorry, I checked after making the corrections 🤦
> Actually, the MC have been analysed with an integration window of **(3,7)**
> 
> ```
> In [1]: from lstchain.calib import load_calibrator_from_config, load_image_extractor_from_config
> In [2]: from lstchain.io.config import get_standard_config, read_configuration_file
> In [3]: im = load_image_extractor_from_config(get_standard_config())
> In [4]: im.window_shift
> Out[4]: 3
> In [5]: im.window_width
> Out[5]: 7
> In [6]: im
> Out[6]: <ctapipe.image.extractor.LocalPeakWindowSum at 0x126cb3550>
> ```

Ok, thanks! In principle, given the correction for window width which is present in the MC, this should hardly make any difference. And I doubt it can be connected to the noisier correlation between time gradient and impact parameter that I was mentioning.

**Comment by vuillaut** [comment]
Update: the issue also concerns real data calibration with lstchain 0.6.
The integration window is always (3,7) for real data and for MC.

```
from lstchain.calib.camera.calibrator import LSTCameraCalibrator
from lstchain.io.config import get_standard_config
config = get_standard_config()
from traitlets.config import Config
from ctapipe.instrument import SubarrayDescription, TelescopeDescription
subarray = SubarrayDescription(
    "LST-1",
    tel_positions={1: None},
    tel_descriptions={
        1: TelescopeDescription.from_name("LST", "LSTCam")
    },
)


calibration_path = 'calibration.Run2029.0000.hdf5'
time_calibration_path = 'time_calibration.Run2029.0000.hdf5'

r1_dl1_calibrator = LSTCameraCalibrator(calibration_path=calibration_path,
                                        time_calibration_path=time_calibration_path,
                                        extractor_product=config['image_extractor'],
                                        gain_threshold=Config(config).gain_selector_config['threshold'],
                                        charge_scale=config['charge_scale'],
                                        config=Config(config['image_extractor_config']),
                                        allowed_tels=[1],
                                        subarray=subarray
                                        )
r1_dl1_calibrator.image_extractor.window_shift
r1_dl1_calibrator.image_extractor.window_width
config
Out[18]: 
{
 'image_extractor': 'LocalPeakWindowSum',
 'image_extractor_for_muons': 'GlobalPeakWindowSum',
 'image_extractor_config': {},
 'LocalPeakWindowSum': {'window_shift': 4, 'window_width': 8},
 'GlobalPeakWindowSum': {'window_shift': 4, 'window_width': 8},
 'calibration_product': 'LSTCalibrationCalculator',
 'LSTCalibrationCalculator': {'minimum_hg_charge_median': 5000,
  'maximum_lg_charge_std': 300,
  'flatfield_product': 'FlasherFlatFieldCalculator',
  'pedestal_product': 'PedestalIntegrator',
  'PedestalIntegrator': {'sample_size': 10000,
   'sample_duration': 100000,
   'tel_id': 1,
   'charge_median_cut_outliers': [-10, 10],
   'charge_std_cut_outliers': [-10, 10],
   'charge_product': 'FixedWindowSum'},
  'FlasherFlatFieldCalculator': {'sample_size': 10000,
   'sample_duration': 100000,
   'tel_id': 1,
   'charge_product': 'LocalPeakWindowSum',
   'charge_median_cut_outliers': [-0.5, 0.5],
   'charge_std_cut_outliers': [-10, 10],
   'time_cut_outliers': [2, 38]},
  'LocalPeakWindowSum': {'window_shift': 5, 'window_width': 12},
  'FixedWindowSum': {'window_start': 12, 'window_width': 12}}
}
```
```
r1_dl1_calibrator.image_extractor.window_width
Out[19]: [('type', '*', 7)]
```
```
r1_dl1_calibrator.image_extractor.window_shift
Out[20]: [('type', '*', 3)]
```
