### ISSUE TITLE
pedestal images in DL1 file

### ISSUE THREAD

**Issue by pawel21** [cta-observatory/cta-lstchain#425]
Hi everybody,

I am working on cleaning issues. In order to check how cleaning works, I am using pedestal events.
I am a bit confused, because:
for example: Run 1627.0000 
when I processed data 'r0->dl1':
I got 1519 pedestal events `if ev.lst.tel[1].evt.tib_masked_trigger == 32`  

but, when I checked new dl1 file (v0.5.1_v03) dl1_LST-1.Run01627.0000.h5
I tried find pedestal images using function (inspired by @moralejo code from datachecks)
```
def get_pedestal_images(dl1_filename):
    file = tables.open_file(dl1_filename)
    parameters = pd.read_hdf(dl1_filename, key=dl1_params_lstcam_key)
    image_table = file.root.dl1.event.telescope.image.LST_LSTCam
    image = image_table.col('image')
    params_pedestal_mask = (parameters['trigger_type'] == 32) 
    ped_indices = np.array(parameters['event_id'][params_pedestal_mask])
    pedestal_mask = np.array([(True if evtid in ped_indices else False)
                              for evtid in image_table.col('event_id')])
    file.close()
    return image[pedestal_mask]
```
I got only 970 pedestal images (event). 

Are pedestal images stored in the DL1 file? 
Why I found only part of pedestal images in DL1 file? 
Anybody can explain/help? (@FrancaCassol , @moralejo , @rlopezcoto )

**Comment by pawel21** [comment]
Moreover,

I checked number of pedestal events in DL1 file:

```
f = tables.open_file("dl1_LST-1.Run01627.0000.h5")
ped = f.root['/dl1/event/telescope/monitoring/pedestal']
print(ped.cols.n_events)
```
I got: 1519

**Comment by rlopezcoto** [comment]
Hi @pawel21. I believe that the problem is that you are trying to access the DL1 parameters table, that contains only events that have survived the cleaning.

**Comment by moralejo** [comment]
Rubéns explanation sounds likely to me... and the fact that you find 970 pedestal cleaning-survivors shows clearly the need for the smarter cleaning!

**Comment by pawel21** [comment]
OK, it makes sense 
thank you for the explanation
