### ISSUE TITLE
merge_hdf5 appends instrument configuratation

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/cta-lstchain#426]
```
>>> len( pd.read_hdf('./dl1_gamma-diffuse_south_pointing_20200514_v0.5.1_v01_DL1_training.h5', key='instrument/telescope/optics') )           
>>> 499
```

I think it should only keep unique rows.

**Comment by vuillaut** [comment]
Right now, it keeps each row from each file.
What do you mean unique rows? something such as `set(rows)`?
If so, how do you attribute where the row is coming from after merging?

**Comment by MaxNoe** [comment]
I cannot determine this now, there is now obs / run id or similar. 
It is just 500 times the exact same lst optics configuration.

**Comment by MaxNoe** [comment]
```
        description name type  mirror_area  num_mirrors  num_mirror_tiles  equivalent_focal_length
0    LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
1    LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
2    LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
3    LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
4    LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
..              ...  ...  ...          ...          ...               ...                      ...
494  LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
495  LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
496  LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
497  LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
498  LST_LST_LSTCam  LST  LST   386.733246            1               198                     28.0
```

**Comment by vuillaut** [comment]
You actually can because there should be a list of filenames used to make the merged one.

**Comment by vuillaut** [comment]
```
import tables

with tables.open_file('dl1_gamma-diffuse_south_pointing_20200514_v0.5.1_v01_DL1_training.h5') as f:
file_list = f.root._v_attrs['SOURCE_FILENAMES']
```

**Comment by MaxNoe** [comment]
I see. But in general, we should only merge dl1 files with the same configuration, right?

**Comment by vuillaut** [comment]
By the way, `_v_attrs` is probably not the best place to write these metadata, and we run into issues where the filenames get too long. If you have a proposition to store them elsewhere that would be great.

**Comment by MaxNoe** [comment]
>  into issues where the filenames get too long

What does it mean, too long? don't the attributes support vlength strings?

You can get the run numbers from `/configuration/simulation/run_config/obs_id`

**Comment by vuillaut** [comment]
> I see. But in general, we should only merge dl1 files with the same configuration, right?

That's what the `--smart` was for - checking that the user is merging things that make sense. But you can pass `False` and be on your own. It's valid only for MC because it's also checking that the MC have similar values (such as simulated spectra...)

**Comment by vuillaut** [comment]
> > into issues where the filenames get too long
> 
> What does it mean, too long? don't the attributes support vlength strings?

There is a global size limit on the header in `_v_attrs`.
Maybe @garciagenrique can find the error message we got at some point?

**Comment by MaxNoe** [comment]
>  (In considering attributes and size, the HDF5 development team has considered attributes to be up to 16K, but this has never been set as a design or implementation limit.)

Using tables, I get an error when the size of the value is larger than 65504, which is awfully close to 2**16 bytes.

**Comment by garciagenrique** [comment]
> There is a global size limit on the header in `_v_attrs`.
> Maybe @garciagenrique can find the error message we got at some point?

The error while merging MC DL1 files from the last production:

`Traceback (most recent call last):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/bin/lstchain_merge_hdf5_files", line 11, in <module>
    load_entry_point('lstchain', 'console_scripts', 'lstchain_merge_hdf5_files')()
  File "/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/scripts/lstchain_merge_hdf5_files.py", line 77, in main
    smart_merge_h5files(file_list, args.outfile, node_keys=keys)
  File "/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/io/io.py", line 278, in smart_merge_h5files
    write_metadata(metadata0, output_filename)
  File "/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/io/io.py", line 489, in write_metadata
    file.root._v_attrs[k] = metadata[k]
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/attributeset.py", line 563, in __setitem__
    self.__setattr__(name, value)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/attributeset.py", line 483, in __setattr__
    self._g__setattr(name, value)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/attributeset.py", line 425, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)
  File "tables/hdf5extension.pyx", line 717, in tables.hdf5extension.AttributeSet._g_setattr
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5A.c", line 279, in H5Acreate2
    unable to create attribute
  File "H5Aint.c", line 275, in H5A__create
    unable to create attribute in object header
  File "H5Oattribute.c", line 335, in H5O__attr_create
    unable to create new attribute in header
  File "H5Omessage.c", line 222, in H5O__msg_append_real
    unable to create new message
  File "H5Omessage.c", line 1933, in H5O__msg_alloc
    unable to allocate space for message
  File "H5Oalloc.c", line 1312, in H5O__alloc
    object header message is too large

End of HDF5 error back trace

Can't set attribute 'SOURCE_FILENAMES' in node:
 / (RootGroup) ''.`
