### ISSUE TITLE
scaling MC intensity

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#433]
Discussed during LST analysis call, June 15th.

We need to scale the MC to match the real data (seems to be easier than the other way around).
Is it necessary to do it at R1/DL0 level or can it be done at DL1 level (on the charge images, before cleaning and parameters extraction)?
The former will be much more complicated.

Note: it might get even more complicated when going for ctapipe v0.8 and the DL1 writer tool which is not meant for these kinds of tweaks but we can leave that point for later.

tagging @moralejo @FrancaCassol for discussion

**Comment by MaxNoe** [comment]
> tweaks but we can leave that point for later. 

We could add an option for that, I think this will be usefull for all kinds of cases.

**Comment by FrancaCassol** [comment]
Hi @vuillaut,

if I am not missing something, it seems to me that it is enough to perform the scale at  the DL1 image level

**Comment by vuillaut** [comment]
> Hi @vuillaut,
> 
> if I am not missing something, it seems to me that it is enough to perform the scale at the DL1 image level

Hi Franca.
I thought so too but preferred to have confirmation before going that way.
Then the correction should not be complicated.
Thanks

**Comment by moralejo** [comment]
It should be done at DL1a level, so it is indeed easy. 
With this, no other modification will be needed, the remaining difference between MC and data will be of course the trigger threshold. The latter can be reduced in higher level analysis  through e.g. an intensity cut. Not so relevant for the _training_ of RFs, anyway, because intensity is always one of the features, so a cut on it before training should not change much (or at all) the performance.

**Comment by moralejo** [comment]
> Not so relevant for the _training_ of RFs, anyway, because intensity is always one of the features, so a cut on it before training should not change much (or at all) the performance.

I mean that the RF training can be done with a relatively low intensity cut, like >50, I do not think this will compromise the performance at, e.g. intensity>200. Hence the intensity cut for e.g. spectral calculation can be decided later, after DL2 is existing.

**Comment by MaxNoe** [comment]
Should we make a quick release v0.5.2 and so that we can have simulations processed with scaled intensity?

**Comment by rlopezcoto** [comment]
we discussed about it last Monday, but the outcome was unclear. 
v0.5.2 is anyways necessary to properly process the datachecks including #417, so if nobody is against it, I can leave until Monday in case other urgent things pop up and then make it.

**Comment by moralejo** [comment]
> Should we make a quick release v0.5.2 and so that we can have simulations processed with scaled intensity?

We agreed we anted also to get #431 and #432 in the new release. Can any of you have a look at them?
