### ISSUE TITLE
Torch module missing for gammalearn

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#45]
When I run any notebook I get:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bbd60dac6846> in <module>
      6 import sys
      7 sys.path.insert(0, '../')
----> 8 from lstchain.reco import reco_dl1_to_dl2
      9 from lstchain.visualization import plot_dl2
     10 from lstchain.reco import utils

~/Code/ctasoft/cta-lstchain/lstchain/__init__.py in <module>
      3 from . import visualization
      4 from . import calib
----> 5 from . import gammalearn

~/Code/ctasoft/cta-lstchain/lstchain/gammalearn/__init__.py in <module>
----> 1 from .gl_utils import load_camera_parameters, load_model
      2 
      3 all = [
      4     'load_camera_parameters',
      5     'load_model'

~/Code/ctasoft/cta-lstchain/lstchain/gammalearn/gl_utils.py in <module>
      2 import json
      3 import importlib
----> 4 import torch
      5 import indexedconv.utils as ic_utils
      6 
ModuleNotFoundError: No module named 'torch'

I guess it is missing from the installation. @mikael10j shall we include it or can we work without it?

**Comment by mikael10j** [comment]
With the last pr you've just merged, we don't need.

**Comment by rlopezcoto** [comment]
sorry, i tested too fast! thanks!
