### ISSUE TITLE
Extractor in ctapipe 0.8

### ISSUE THREAD

**Issue by pawel21** [cta-observatory/cta-lstchain#453]
Hi,

I have tried to use extractor with `ctapipe 0.8` on real data, which  require  `subarray` information.
Seems to me: readout field `readout` is missing from real data.

This is not working(real data)
```
input_url = get_dataset_path('LST-1.1.Run01625.0000.fits.fz')
source = event_source(input_url, max_events=49)
extractor = LocalPeakWindowSum(window_width=11, window_shift=4, subarray=source.subarray)
```
I got the following error: 
AttributeError                            Traceback (most recent call last)
<ipython-input-60-96efe33b3cfb> in <module>
      1 input_url = "/media/pawel1/ADATA HD330/20191124/LST-1.1.Run01625.0001.fits.fz"
      2 source = event_source(input_url, max_events=49)
----> 3 extractor = LocalPeakWindowSum(window_width=11, window_shift=4, subarray=source.subarray)

~/anaconda3/envs/ctapipe_0_8_lstchain/lib/python3.7/site-packages/ctapipe/image/extractor.py in __init__(self, subarray, config, parent, **kwargs)
    295         self.sampling_rate = {
    296             telid: telescope.camera.readout.sampling_rate.to_value("GHz")
--> 297             for telid, telescope in subarray.tel.items()
    298         }
    299 

~/anaconda3/envs/ctapipe_0_8_lstchain/lib/python3.7/site-packages/ctapipe/image/extractor.py in <dictcomp>(.0)
    295         self.sampling_rate = {
    296             telid: telescope.camera.readout.sampling_rate.to_value("GHz")
--> 297             for telid, telescope in subarray.tel.items()
    298         }
    299 

AttributeError: 'CameraGeometry' object has no attribute 'readout'

This is working (MC data)
```
input_url = get_dataset_path('gamma_test_large.simtel.gz')
source = event_source(input_url, max_events=49)
extractor = LocalPeakWindowSum(window_width=11, window_shift=4, subarray=source.subarray)
```

@FrancaCassol , @rlopezcoto do you have the same problem?

**Comment by pawel21** [comment]
I think, we can solve this issue in the following way:
```
subarray = SubarrayDescription(
    "LST-1",
    tel_positions={1: (0.0, 0.0, 0.0) * u.m},
    tel_descriptions={
        1: TelescopeDescription.from_name("LST", "LSTCam")
    },
)
```

**Comment by vuillaut** [comment]
This solves the issue. However, the subarray should be provided by the source (hence `ctapipe_io_lst`).
