### ISSUE TITLE
Outdated gl_utils and other gammalearn stuff into the utils folder

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#456]
The gammalearn stuff in the `utils` folder is quite outdated, shall we try to make it more up to date or just get rid of it @mikael10j, @vuillaut ?
Over there are some modules (`torch`, `indexedcov`) that I'm not sure we would like to include as dependencies of lstchain.

**Comment by MaxNoe** [comment]
As the deep learning mostly starts at dl1, and there is now a dl1 format defined, this should be not needed in lstchain. 

Lstchain should produce the dl1 in the correct format, an then there should be no lst specific things needed to apply deep learning.

**Comment by rlopezcoto** [comment]
so shall we completely eliminate the folder (together with [the gammalearn notebook](https://github.com/cta-observatory/cta-lstchain/blob/master/notebooks/tutorial_gammalearn.ipynb)) @mikael10j, @vuillaut ?

**Comment by vuillaut** [comment]
> As the deep learning mostly starts at dl1, and there is now a dl1 format defined, this should be not needed in lstchain.
> 
> Lstchain should produce the dl1 in the correct format, an then there should be no lst specific things needed to apply deep learning.

Well... I agree and disagree. We can do everything from DL1 completely independently, but the argument could hold for random forests too 😅 

However, I agree that `torch` might be too big a dependency for lstchain at the moment.

**Comment by vuillaut** [comment]
@rlopezcoto yes, let's remove the outdated stuff

**Comment by rlopezcoto** [comment]
Solved in #460

**Comment by MaxNoe** [comment]
>  but the argument could hold for random forests too sweat_smile

Indeed it does!

That's the reason we developed the aict-tools, which also predate the lstchain :wink:
