### ISSUE TITLE
Problems running RF-performance.ipynb

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#46]
After setting the correct paths (@misabelber):
PATH_EVENTS = "../../cta-lstchain-extra/reco/sample_data/dl1/"
gammafile = PATH_EVENTS+"gamma_events_point_tiny.h5"
protonfile = PATH_EVENTS+"proton_events_tiny.h5"

I get this:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-5095118de152> in <module>
      1 #Read the files into pandas dataframes:
      2 df_gammas = pd.read_hdf(gammafile,                                                                   
----> 3                         key="gamma_events")                                                               
      4 df_proton = pd.read_hdf(protonfile,                                                                  
      5                         key="proton_events")

/Users/rubenlopez/anaconda/envs/cta-dev2/lib/python3.6/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    392                                      'contains multiple datasets.')
    393             key = candidate_only_group._v_pathname
--> 394         return store.select(key, auto_close=auto_close, **kwargs)
    395     except:
    396         # if there is an error, close the store

/Users/rubenlopez/anaconda/envs/cta-dev2/lib/python3.6/site-packages/pandas/io/pytables.py in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
    721         group = self.get_node(key)
    722         if group is None:
--> 723             raise KeyError('No object named %s in the file' % key)
    724 
    725         # create the storer and axes

KeyError: 'No object named gamma_events in the file'

**Comment by misabelber** [comment]
Ah, sorry, the problem is the key when reading the hdf. Just remove it from the pd.read_hdf:
df_gammas = pd.read_hdf(gammafile)
df_proton = pd.read_hdf(protonfile)

I will correct it in the repo now.

**Comment by rlopezcoto** [comment]
Solved in #47
