### ISSUE TITLE
Pulse shapes, calibration correction depending on integral width and shift

### ISSUE THREAD

**Issue by calispac** [cta-observatory/cta-lstchain#484]
Hi all,

As you know the ADC/p.e. conversion factor depends on the way the waveforms are integrated. I have myself written a class,  some time ago, that takes care of handling a normalized reference pulse. This class allows to:

- Interpolate the pulse
- Compute the "charge to amplitude" ratio, as func. of window width and shift
- Plot the template
- Compute the time of max ( sometimes the time of max is defined as the arrival time of the pulse, useful to translate into a different reference time frame)
- Save and load templates from a file
- Compute integral of pulse

Let me know if this is wanted or can be useful. I have the code here : https://github.com/calispac/cta-lstchain/blob/91eb7fd0a81a34694bd5268b7a47f47c3f4bb415/lstchain/reco/reconstructor.py#L601

In principle it works for 1D array of pulse templates (1 per pixel)

Example of usage
```python
LST_low_gain_template = NormalizedPulseTemplate.load('low_gain_shape.txt')
t = np.linspace(0, 40, num=1000)
amplitudes = LST_low_gain_template(t)
plt.figure()
plt.plot(t, amplitudes)
```

**Comment by FrancaCassol** [comment]
Hi @calispac 
these class can be in general useful. Why not to put it in ctapipe?

**Comment by MaxNoe** [comment]
Isn't this exactly what the "integration correction" implemented in the ctapipe ImageExtractors does? @watsonjj

**Comment by calispac** [comment]
@MaxNoe It seems that this function https://github.com/cta-observatory/ctapipe/blob/eb571cfde4bd78ead2d9c04d7f8568476f8d976a/ctapipe/image/extractor.py#L194 (used by the ImageExtractor classes) is similar to what I have here: https://github.com/calispac/cta-lstchain/blob/91eb7fd0a81a34694bd5268b7a47f47c3f4bb415/lstchain/reco/reconstructor.py#L664 

Then for the rest of the features: plotting, interpolation, loading, saving it is not implemented in ctapipe as far as I know.

**Comment by MaxNoe** [comment]
Loading and saving the pulse shape should be implemented in the CameraElectronics class.
It should be written as part of the SubarrayDescription to the hdf5 files.

**Comment by rlopezcoto** [comment]
@calispac will you consider moving this implementation into `ctapipe`? If it would be urgently needed by LST we could reopen and have a temporary implementation here

**Comment by MaxNoe** [comment]
> loading, saving it is not implemented in ctapipe as far as I know.

Loading and saving is implemented by using astropy tables:

```
# saving:
camera.readout.to_table().write(...)

# loading
CameraReadout.from_table(Table.read(...))
```
