### ISSUE TITLE
Little typo in DL1ParametersContainer class

### ISSUE THREAD

**Issue by davidsudm** [cta-observatory/cta-lstchain#504]
There is a typo error I crossed in the DL1ParametersContainer class in the file :

[lstchain/io/lstcontainers.py](https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/io/lstcontainers.py)

Line 38 says **centroid x** :
`y = Field(None, 'centroid x coordinate', unit=u.m)`

and it should say **centroid y** :
`y = Field(None, 'centroid y coordinate', unit=u.m)`

I think it should be obvious to other users, however, since it is a field definition, it could be good to correct it.

**Comment by rlopezcoto** [comment]
thanks for reporting @davidsudm, would you like to have a look and try to correct it yourself? In principle, the guidelines for code development are the same ones as in [ctapipe](https://cta-observatory.github.io/ctapipe/getting_started/index.html), but I can give you a hand if you need it,
