### ISSUE TITLE
Pulse time values

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#507]
Hi
The pulse time values for the real data are roughly between -20 and 20 ns, while for MC, values are between 0 and 40ns.

I understand that this is due to the time calibration, but could not pinpoint the place where the shift happens.
If we want to do the correction to have comparable values between MC and real data, shall we apply a simple shift by 20ns or is it event dependent?

Thanks.

**Comment by FrancaCassol** [comment]
Hi @vuillaut, 
this should be not more true, it was fixed in PR [434](https://github.com/cta-observatory/cta-lstchain/pull/434/files)

**Comment by vuillaut** [comment]
Thanks @FrancaCassol.
I did not realise this had been corrected, most of the data have not been re-processed with this correction yet.
