### ISSUE TITLE
Uncertainties of Hillas Parameters in dl1 container

### ISSUE THREAD

**Issue by andres-baquero** [cta-observatory/cta-lstchain#537]
I'v already made a PR in ctapipe to includes the Hillas uncertainties of Length and Width that results from the poissonian fluctuations on the number of photons per pixel.

Some time ago we presented on an ASWG call an analysis using the Hillas’s uncertainties to train Random Forest models, here's the link [Hillas's uncertainties](https://indico.cta-observatory.org/event/2348/contributions/20708/attachments/15797/20243/Hillas_Uncertainties.pdf).

It would require introducing new variables for the uncertainties in dl1 container.

This PR was merged to the ctapipe v0.9.1, so we need to wait until lstchain use the ctapipe v0.9.1 ?

**Comment by andres-baquero** [comment]
Sorry, maybe we just have to transform from meters to deg like width and length in r0_to_dl1.py, but maybe with this [issue 1413](https://github.com/cta-observatory/ctapipe/issues/1413#issuecomment-707727020)  is not more necessary.

**Comment by vuillaut** [comment]
@maxnoe mixing repos ?

@andres-baquero Yes that is right, you will need to wait we update lstchain to use the output of the stage1 from ctapipe.

**Comment by maxnoe** [comment]
Oh, sorry, this is lstchain...

Nevermind my comment then, other than this is exactly the point I was making about going forward.

**Comment by maxnoe** [comment]
I then want to applaud @andres-baquero for actually making the contribution to ctapipe and not only to lstchain!

**Comment by andres-baquero** [comment]
Some time ago we introduce the Hillas uncertainties of Length and Width on ctapipe with the corresponding PR. It would require introducing new variables for the uncertainties in dl1 container for lstchain, at that time we had to wait until the lstchain update to ctapipe 0.9, is possible to do this now ?.

**Comment by maxnoe** [comment]
Yes, lstchain is using ctapipe 0.10.5 now, so the uncertainties are already calculated but then not filled into this monster dl1 container. 

So you could just update the method filling the hillas parameters into the dl1 container.

**Comment by andres-baquero** [comment]
I've already add the same fields in lstchain_dl1ab but it's failing:

 FAILED ***/scripts/tests/test_***_scripts.py::test_observed_dl1ab
416
ERROR ***/scripts/tests/test_***_scripts.py::test_dl1ab - ValueErro...
417
ERROR ***/scripts/tests/test_***_scripts.py::test_simulated_dl1ab_validity.

Maybe I have to change other dependencies ?.

**Comment by vuillaut** [comment]
> I've already add the same fields in lstchain_dl1ab but it's failing:
> 
> FAILED _**/scripts/tests/test_**__scripts.py::test_observed_dl1ab 416 ERROR ***/scripts/tests/test__**_scripts.py::test_dl1ab - ValueErro... 417 ERROR ***/scripts/tests/test_**__scripts.py::test_simulated_dl1ab_validity.
> 
> Maybe I have to change other dependencies ?.

Are you referring to PR #717 ?
You need to update the [`DL1ParametersContainer`](https://github.com/cta-observatory/cta-lstchain/blob/deabb5c3de058954028ead129d2368d2b70404ed/lstchain/io/lstcontainers.py#L31) to add the new parameters you want to fill.
See the [CI error in your PR](https://github.com/cta-observatory/cta-lstchain/pull/717/checks?check_run_id=2619622561#step:6:110)

**Comment by andres-baquero** [comment]
Yes, I'm referring to the PR  #717. I'm already add the new parameters in the PR #715, but it's not merged yet so maybe this is the reason that the changes of #717 is failing ?.

**Comment by maxnoe** [comment]
@andres-baquero probably, yes. I don't really see a reason to split this in two, since it is the same thing really. So maybe just add the changes in #717 also to #715?

**Comment by andres-baquero** [comment]
Ok, I have committed the changes in this PR for the  lstchain_dl1ab.py script
