### ISSUE TITLE
Wrong docstring in interpolate spikes

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#560]
The docstring of the interpolate spike functions say:

```
        Interpolate Spike A & B.
```

but in the code, only two cases of `interpolate_spike_A` are called and there is no `interpolate_spike_B` function

**Comment by jsitarek** [comment]
It used to be spikes A & B in the past, but it turned out that spikes B were caused by wrong updates of last reading time, and thus the code only has spikes A now. I updated the docstrings and made a small PR
