### ISSUE TITLE
Print out intial timestamps and counters in nsec instead of seconds

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#565]
Since `r0_to_dl1` uses timestamps and the corresponding counters in nsec (integers) as input, we should print out those same values in nsecs instead of seconds to avoid confusion.

**Comment by morcuended** [comment]
This is how it currently looks:
```
Using first event as time reference for counters, this will lead to wrong timestamps / trigger types for all but the first subrun
Using first event as time reference for dragon. UCTS timestamp: 1582059789516171575 dragon_counter: 2516171300
Using first event as time reference for TIB. UCTS timestamp: 1582059789516171575 tib_counter: 2516170900
```

**Comment by maxnoe** [comment]
This is now in `ctapipe_io_lst`, where a `log.critical` message has the timestamp values in ns.

However, I think we probably should make a dedicated tool to produce these night summary files, right?

**Comment by morcuended** [comment]
Closing this. Run summaries are produced now with the script made in #614.
