### ISSUE TITLE
Coding sprint for ctapipe 0.10?

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#576]
Dear all,

as soon as the ctapipe compatible reader will be approved, I plan to make the calibration tools (old and new) compatible with the new reader  and to start a migration of part of the code to ctapipe (the level B calibration is supposed to be performed in DPPS).
For this,  lstchain must be upgraded to ctapipe 0.10. I wonder on how we want to proceed, should we plan a coding sprint as for ctapipe 0.8? 

First wish for the new year ;-)

**Comment by rlopezcoto** [comment]
this is probably one of the things that we should start discussing as soon as the new reader is in place. We could start discussing this in one of the bi-weekly calls next year.

**Comment by maxnoe** [comment]
We upgraded to ctapipe 0.10 a long time ago
