### ISSUE TITLE
Bug in lstchain_mc_dl1ab script 

### ISSUE THREAD

**Issue by pawel21** [cta-observatory/cta-lstchain#577]
When I tried run script [`lstchain_mc_dl1ab.py`](https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/scripts/lstchain_mc_dl1ab.py) with different cleaning parameters, i realized that DL1 parameters are not updating, 
except the last event. 
I think problem is in  line 156-157, loop `for p in parameters_to_update`should iterate for each image. (so we should shift this part of code one tab to the right)

@vuillaut or @SeiyaNozaki Could you confirm? If yes, I can modified script and make PR.

**Comment by SeiyaNozaki** [comment]
Hi @pawel21 
I confirmed only the last event was updated and your idea seems reasonable.
I checked it was working without an error before, but at that time I used a default config file and didn't check the file itself...sorry!

**Comment by vuillaut** [comment]
Damn, PR #543 was fixing this issue but never got merged.
I will update the branch and maybe you can review it to solve this issue?

**Comment by morcuended** [comment]
After #543 and #585 the script `lstchain_dl1ab` should be ready now, @pawel21, to include the new cleaning method.
