### ISSUE TITLE
Concentration features are calculated on all pixels, not just the ones that survive cleaning

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#580]
I don't know if it's worth to change this before switching to ctapipe-stage1.

**Comment by rlopezcoto** [comment]
should be a very quick change in case we make another release before definitely moving to `ctapipe-stage1`, right?

**Comment by moralejo** [comment]
It is worth to fix it straightaway - let's see is some newcomer decides to take it.
Still, only concentration_pixel is affected, and even that one is affected only for events in which the brightest pixel in the camera did not survive the cleaning. So it will not make a large difference.

**Comment by maxnoe** [comment]
You are right, since concentration is using the hillas intensity internally. I thought it sums the image again.
