### ISSUE TITLE
Why importing lstchain takes so long?

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#583]
As compared with ctapipe for example:

```
In [2]: timeit.timeit("import lstchain", number=10000)
Out[2]: 4.323817577999762

In [3]: timeit.timeit("import ctapipe", number=10000)
Out[3]: 0.0010185620003539952
```

**Comment by maxnoe** [comment]
`import ctapipe` basically does nothing, since `ctapipe.__init__.py` is basically empty.

Try this:

```
import ctapipe.image
import ctapipe.calib
import ctapipe.core
```

**Comment by maxnoe** [comment]
I would not worry about this.

**Comment by morcuended** [comment]
Understood, not a problem at all as it is.

**Comment by vuillaut** [comment]
Though if you know a way to reduce that time, that'd be great ;-)

**Comment by maxnoe** [comment]
Like I said, It is a tradeoff between convenience (having all submodules directly imported) and import time.
