### ISSUE TITLE
Tool to create files with needed reference timestamps and counters

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#610]
As decided in today's call we need an own script that provides the initial timestamps/counters for a given module that is available. The file should also contain the ID of that module used. These counters and timestamps are used as the time references in the `r0_to_dl1` and other calibrations scripts.

Right now they are provided externally by Isidro Aguado.

**Comment by maxnoe** [comment]
Discussion from slack:

Snippet to convert `CameraConfiguration.date` to unix_tai in ns:

```python
int(round(Time(svc.date, format='unix').unix_tai)) * int(1e9)
```

Columns we want to have:

* run_number
* subruns
* type_of_run
* start_of_the_run  (already converted to unix TAI ns)
* dragon reference event_id (should be 1 to be safe no UCTS jumps happened)
* dragon reference ucts timestamp (-1 if no ucts available)
* dragon reference counter
* dragon reference module_id
