### ISSUE TITLE
lstchain_data_create_drs4_pedestal_file broken with ctapipe_io_lst=0.8  

### ISSUE THREAD

**Issue by Bultako** [cta-observatory/cta-lstchain#620]
I cannot produce pedestal files with the updated environment ctapipe_io_lst=0.8  
I have the error below.

```
lstchain_data_create_drs4_pedestal_file --input-file $LSTCHAIN_TEST_DATA/real/R0/20200218/LST-1.1.Run02008.0000_first50.fits.fz  -o pedestal.fits

--> Input file: /Users/jer/git/cta-observatory/cta-lstchain/test_data/real/R0/20200218/LST-1.1.Run02008.0000_first50.fits.fz
--> Number of events: 20000
/opt/miniconda3/envs/lst-dev/lib/python3.7/site-packages/traitlets/traitlets.py:604: UserWarning: Config option `fill_timestamp` not recognized by `LSTEventSource`.
  self.set(obj, value)
--> Number of files 4
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lst-dev/bin/lstchain_data_create_drs4_pedestal_file", line 33, in <module>
    sys.exit(load_entry_point('lstchain', 'console_scripts', 'lstchain_data_create_drs4_pedestal_file')())
  File "/Users/jer/git/cta-observatory/cta-lstchain/lstchain/scripts/lstchain_data_create_drs4_pedestal_file.py", line 79, in main
    for i, event in enumerate(reader):
  File "/opt/miniconda3/envs/lst-dev/lib/python3.7/site-packages/ctapipe/io/eventsource.py", line 274, in __iter__
    for event in self._generator():
  File "/opt/miniconda3/envs/lst-dev/lib/python3.7/site-packages/ctapipe_io_lst/__init__.py", line 328, in _generator
    self.fill_r0_container(array_event, zfits_event)
  File "/opt/miniconda3/envs/lst-dev/lib/python3.7/site-packages/ctapipe_io_lst/__init__.py", line 632, in fill_r0_container
    zfits_event
  File "/opt/miniconda3/envs/lst-dev/lib/python3.7/site-packages/ctapipe_io_lst/__init__.py", line 602, in fill_r0_camera_container
    reshaped_waveform = zfits_event.waveform.reshape(
AttributeError: reshape

```

**Comment by maxnoe** [comment]
can reproduce on mac, but not on linux.

**Comment by rlopezcoto** [comment]
@Bultako what about with `ctapipe_io_lst=0.7` before #618 was merged?

**Comment by maxnoe** [comment]
It is an issue with protozfits on mac somehow. It does not convert the protozfits `AnyArray` to a numpy array.

I am trying to figure out why. This is not an issue of `ctapipe_io_lst` but of `protozfits`.

**Comment by Bultako** [comment]
Yep, I can confirm
The script fails in envs with `protobuf` and `zeromq` installed, independently of the the version of `ctapipe_io_lst`. And it works in envs where these libraries have not been installed.

**Comment by maxnoe** [comment]
I could fix it with `if value.__class__.__name__ == 'AnyArray'` instead of `if isinstance(value, AnyArray)`, but I don't understand where the problem comes from and why it only shows on mac.

I will try a source install on linux

**Comment by maxnoe** [comment]
Ok, same error when using conda protobuf and a source install on linux.

**Comment by maxnoe** [comment]
Will be fixed in the 2.0.1 release, hope it gets merged soon.

**Comment by maxnoe** [comment]
>  And it works in envs where these libraries have not been installed.

I am a bit confused about this statement. If they are not installed, it shouldn't work *at all*

**Comment by Bultako** [comment]
> > And it works in envs where these libraries have not been installed.
> I am a bit confused about this statement. If they are not installed, it shouldn't work at all

I mean in envs created with an `environment.yml` file that do not have `protobuf` and `zeromq` listed as dependencies.

**Comment by maxnoe** [comment]
Yes, but then installing `protozfits` should just fail. Or do you have `protobuf` and `zeromq` also available in your system?

**Comment by Bultako** [comment]
You're right.
I've found these packages in my system as well.

```
# Name                    Version                   Build  Channel
zeromq                    4.3.2                h4a8c4bd_4    conda-forge
protobuf                  3.15.5                   pypi_0    pypi
```

**Comment by maxnoe** [comment]
These are also conda packages.

Not system packages.

**Comment by Bultako** [comment]
Yep
and they are available in my system as you said ;-)
I guess they are used anyway when I create the `lst-dev` env from the `base` conda env.

**Comment by maxnoe** [comment]
With system libs, I means someting installed in `/lib` or `/Library` not something in another conda env, but that could also be a problem. Still trying to figure it out why there are two different instances of the type `AnyArray`.

**Comment by rlopezcoto** [comment]
> Will be fixed in the 2.0.1 release, hope it gets merged soon.

great, thank you very much @maxnoe for the very quick fix. Let's wait until ~very~ early next week while we are still finishing with the other needed PRs before making the new release

**Comment by maxnoe** [comment]
Actually yes, we have a number of open PRs that make breaking changes

**Comment by maxnoe** [comment]
protozfits v2.0.1 is on pypi now, it should fix this issue.

Can you confirm?

**Comment by Bultako** [comment]
Thanks @maxnoe 
I confirm installing `protozfits v2.0.1` has fixed the issue.
