### ISSUE TITLE
Standard cleaning settings

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#628]
With #612 we can reduce the effect of stars by setting an additional cleaning threshold for each pixel, which depends on the standard deviation of its charge in interleaved pedestal events throughout a subrun.

We have to decide on the **standard settings** for the next reprocessing of LST data. There are 4 parameters to play with (default values used in previous processing in parentheses):

Picture threshold (6), boundary threshold (3), min_number_picture_neighbors (1), sigma (-)

sigma is the number of standard deviations above the mean pedestal charge so that a pixel can survive the cleaning (if it fulfills the rest of conditions). This is implemented in #612 and hence was not available in the previous processing.

Besides, one can set the parametrization to use all pixels surviving the cleaning, or just the main island. The previous processing used the main island as a means to reduce the effect of noisy pixels. In the next reprocessing we intend to **use all cleaning survivors**, because otherwise we may be losing parts of the image which may help in the reconstruction (e.g. by keeping just the main island we may be making all showers look more gamma-like).

To be considered:

- the "sigma" condition must be the dominant one only exceptionally, i.e. for pixels illuminated by stars, or noisy for whatever other reason. The bulk of the camera pixels at any given time must be cleaned according to the picture and boundary thresholds. If that is not the case, MC - data matching would become very complicated. The goal of the additional condition is just to avoid noisy pixels to survive too often (since that would affect the reconstruction of the actual shower images).
- Therefore,the typical values of mean_pedestal+sigma\*pedestal_rms should not be larger than the picture threshold. With our current LocalPeak integration, the mean_pedestal of camera pixels may vary between 1.7 and 2.5 p.e., with standard deviation between 1.6 and 2 p.e. With sigma=3 it would not make sense to use a picture threshold of 6, because all pixels would in practice have a higher threshold, given by sigma. We should actually have a warning for the case in which the cleaning of a large fraction of camera pixels have mean_pedestal+sigma\*pedestal_rms > picture_threshold
- we could also use timing constraints. e.g. using ctapipe.image.apply_time_delta_cleaning within lstchain's dl1ab script
- since the goal is to reduce the effect of stars and other noisy pixels, these cleaning settings cannot be optimized on MC (at least not with the standard one). So we have to find the best settings (or at least reasonable ones) looking at the real data. We can check e.g. the number of surviving images in real pedestal events (this will tell us the rate of spurious islands in shower images), and also the uniformity of the distribution of the images' c.o.g.'s for the evaluation.

**Comment by rlopezcoto** [comment]
I am in favor of:
- Not using only the main island. This is very likely giving trouble at the lowest energies where events have very few pixels.
- `min_number_picture_neighbors` we could increase to 2, so we do not have islands only with a couple of pixels.
- if I'm not wrong, `sigma` =~ 3 has already shown to be a bit problematic and left very noisy images that @pawel21 shared on slack, maybe he could comment further on that. 
- the usage of time constraints sounds like a good idea, but they need to be optimized before implemented some settings for the default analysis.
 
> * since the goal is to reduce the effect of stars and other noisy pixels, these cleaning settings cannot be optimized on MC (at least not with the standard one). So we have to find the best settings (or at least reasonable ones) looking at the real data. We can check e.g. the number of surviving images in real pedestal events (this will tell us the rate of spurious islands in shower images), and also the uniformity of the distribution of the images' c.o.g.'s for the evaluation.

this sounds like an optimization for the future, and also the outcome that needs to come out of a more detailed analysis, but for the default values of the input card included in the next release, we should probably select some safe values based on the preliminary results shown by @pawel21 in (please share if you have any updates):
https://indico.cta-observatory.org/event/3048/contributions/26326/attachments/18300/24793/2020_10_30_LST_GM_Improvement_of_the_image_cleaning_strategy.pdf
Maybe from the table on S.15, I would choose as a compromise the method I am highlighting:
![Screenshot 2021-03-09 at 08 47 10](https://user-images.githubusercontent.com/17042312/110436212-3f55fa80-80b4-11eb-84d6-98cc1f404742.png)
but with the 8-4 cleaning.

**Comment by maxnoe** [comment]
Let me just comment that I think this study can be made very well using the dl1 notebook I presented for the DL1 reference dataset here: https://indico.cta-observatory.org/event/3244/

You extract DL1a only once and you can very quickly redo the cleaning for many events to optimize the thresholds without running the `r0_to_dl1` tool again.

**Comment by pawel21** [comment]
Hi,
From my study I think, the best solution for first reprocessing will be try use the following parameters:
1) picture threshold = 8, boundary threshold = 4, sigma = 3. If no time delta cleaning
or 
2) picture threshold = 6, boundary threshold = 3, sigma = 2.5 + time delta cleaning = 2.

To find better parameters dl1 notebook for Max will be very useful.

**Comment by rlopezcoto** [comment]
hi @pawel21, it seems that the two options you are describing are not in the above mentioned table, right?

**Comment by rlopezcoto** [comment]
both of them with `time delta cleaning = 2` as it is written in the slides or only the second one as described [here](https://github.com/cta-observatory/cta-lstchain/issues/628#issuecomment-793738226)?

**Comment by maxnoe** [comment]
Please note this bug @moralejo  just found: https://github.com/cta-observatory/ctapipe/issues/1653

**Comment by rlopezcoto** [comment]
thanks @pawel21, then I would propose to go for:
`picture threshold = 6, boundary threshold = 3, sigma = 2.5, time delta cleaning = 2 pedestal survived percent = 15 %`

any opinions?

**Comment by moralejo** [comment]
Does not sound bad in principle, but wait, I am looking into it, trying to cross-check Pawel's results on a different run, making sure it works with current code, etc.

**Comment by moralejo** [comment]
Some comments:

- I'd like to avoid 8-4 p.e. thresholds because it would obviously mean a higher threshold, and I think we can reduce the effect of stars without having to do that.

> thanks @pawel21, then I would propose to go for:
> `picture threshold = 6, boundary threshold = 3, sigma = 2.5, time delta cleaning = 2 pedestal survived percent = 15 %`
> 

- I tried these settings on subrun Run02291.0000 which also has a few stars / noisy pixels. I get higher efficiencies, 40% for pedestals and 90% for cosmics. Good news is that the fraction of pixels which have a minimum allowed charge (through the "sigma=2.5" setting) larger than the nominal picture threshold of 6 p.e. is just 0.036. This is ok from the point of view of data/MC agreement.
- I think 40%, or even 15%, are too high fractions of surviving pedestals, they mean we would have the same fraction of actual shower images with additional spurious islands. The number of islands in cosmics peaks at 3 (with ~90% having more than 1). So I think we should use the additional condition min_number_picture_neighbors:2 (we use this e.g. in MAGIC).
- Proposal: with `picture threshold = 6, boundary threshold = 3, sigma = 2.5, time delta cleaning = 2, min_number_picture_neighbors = 2`  just 2% of pedestals survive,  while 72% of cosmics do. Number of islands peaks at 1 for cosmics (only ~20% have >1)
- Image CoG distribution is below. Left: our previous default cleaning (6_3, only main island), right: the proposed one, with the 2-neighboring-picture-pixels condition.

![image](https://user-images.githubusercontent.com/14164282/110550825-a915e900-8134-11eb-96ba-bd84d9af7e93.png)

- x-projections (orange is the proposed cleaning):

![image](https://user-images.githubusercontent.com/14164282/110550939-e37f8600-8134-11eb-9bdf-6fca1ad1a276.png)

- Distribution of the brightest pixel in an image (concentration_pixel*intensity, same color code as above): this allows to compare two cleanings since a given event which survives both cleanings will have the same value of this in the two analyses. The reduction in the number of events (relative to the 6_3_main_island) occurs mostly in the range below 50 p.e. The majority of these events had CoG around the star positions, so they were not usable showers anyway.

![image](https://user-images.githubusercontent.com/14164282/110551517-f6468a80-8135-11eb-89b4-c25f6b7e5f8f.png)

- Of course we will not know really how this performs until we test on a few hours of Crab data, so I propose to move forward with those settings and eventually try looser cleaning.

**Comment by rlopezcoto** [comment]
> * Image CoG distribution is below. Left: our previous default cleaning (6_3, only main island), right: the proposed one, with the 2-neighboring-picture-pixels condition.

This looks better, although there is still some clustering at the right of the camera.

> * Proposal: with `picture threshold = 6, boundary threshold = 3, sigma = 2.5, time delta cleaning = 2, min_number_picture_neighbors = 2`  just 2% of pedestals survive,  while 72% of cosmics do. Number of islands peaks at 1 for cosmics (only ~20% have >1)

I agree to start with settings that are removing many of the surviving pedestals, but we need to investigate the full performance using different cleaning levels in the future to try to get the lowest possible threshold.

**Comment by moralejo** [comment]
> This looks better, although there is still some clustering at the right of the camera.
> 
Yes, but comparing to what we had with the previous cleaning (look at the projection plot) I'd say this was a pretty difficult case, and the improvement is large.

> 
> I agree to start with settings that are removing many of the surviving pedestals, but we need to investigate the full performance using different cleaning levels in the future to try to get the lowest possible threshold.
>
Sure, we just want a starting point for the standard processing.

**Comment by moralejo** [comment]
Checked another run, 2988 from November 2020. Similar conclusions.

![image](https://user-images.githubusercontent.com/14164282/110662465-d363b700-81c5-11eb-839b-b94eb7c0f62d.png)
![image](https://user-images.githubusercontent.com/14164282/110662573-ed04fe80-81c5-11eb-9535-80789132c582.png)
![image](https://user-images.githubusercontent.com/14164282/110662644-fbebb100-81c5-11eb-9f4c-a1c2b99ffd69.png)

**Comment by rlopezcoto** [comment]
are the 1D histogram plots included in the datacheck?

**Comment by moralejo** [comment]
> are the 1D histogram plots included in the datacheck?

No, but 2D image COG position is there, for all events and for intensity>200 pe

**Comment by moralejo** [comment]
Tests are not passing, I think we need to upload new reference MC and data DL1 files, can you have a look?

**Comment by maxnoe** [comment]
@moralejo Upload DL1 files?

**Comment by moralejo** [comment]
> @moralejo Upload DL1 files?

I have some real data ones straightaway, but not MC. How can one upload real data files to the private area?

**Comment by moralejo** [comment]
Ok,the problems with the tests were fixe.  We'll try the settings proposed above and see how that works with the full LST1 dataset.
