### ISSUE TITLE
Append events from several simtel files with HDF5TableWriter?

### ISSUE THREAD

**Issue by misabelber** [cta-observatory/cta-lstchain#63]
Hi, 
This is mainly a question for @vuillaut, who implemented the usage of ctapipe.io.HDF5TableWriter into lstchain (but anyone can help!).
I want to create a script to read a bunch of simtel files, extract dl1 data with reco.dl0_to_dl1 and store all the events in the same .h5 output file (and in the same dataframe), but I'm not sure on what is the best way to manage this.
The writting of data into .h5 is inside the function r0_to_dl1(), where the mode of HDF5TableWritter is set to "overwrite". I thought that maybe it could work just by changing it to "append" mode, , but I see that this won't work, because it won't write the data in the same dataframe, which is what I would prefer. The other solution I'm thinking of is to write a .h5 file for each simtel file and then put all of them together concatenating the dataframes using pandas. 
What do you think would be the smartest way to do this? 
Thank you very much!

**Comment by vuillaut** [comment]
Hi @misabelber 
I think my first question will be how do you want to do that on a bunch of simtels?
- if you go in series, you can open the HDF5 file first then loop on the simtels and it will work directly:
```
with HDF5TableReader('container.h5', mode=mode) as h5_table:
    for file in list_simtel_files:
        source = event_source(file)
        ...
```
- if you want to parallelize, you won't be able to write in the same file in parallel so you have to wait for your parallel jobs to finish then concatenate the HDF5 files. As you say, you may use pandas for that, it's quite efficient.

I personnaly combine both, lunching parallel jobs each working on a number of simtels then merging everything.

**Comment by misabelber** [comment]
Great! I think the best thing is as you say, the second option, so I will be able to paralellize. Thank you very much!
