### ISSUE TITLE
post dl2 analysis config files in the wrong directory?

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#634]
I guess this version needs to be updated.
https://github.com/cta-observatory/cta-lstchain/blob/1c993cf6a8cde273bb1cab5b576e48b4600ac330/docs/examples/post_dl2_analysis/config_on_off.toml#L2

But the thing is why are these `toml` files placed in the [docs](https://github.com/cta-observatory/cta-lstchain/tree/master/docs) folder where the documentation should be located, right? Was this intended?

**Comment by mexanick** [comment]
As path suggests, these are example files. Intention is to include them in documentation when it will be available. Actually we are preparing an update of this toolkit to include a bit more sophisticated treatment of data, @gabemery will follow this up. We will update the tag in the example at the same time.
