### ISSUE TITLE
DL1 files from dl1ab scripts are bulkier than original ones

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#635]
For files containing images, original ones are ~730 MB, vs. 900 MB for those from dl1ab. Anyone knows where's the difference?

**Comment by moralejo** [comment]
Seems to be a compression issue.

**Comment by rlopezcoto** [comment]
?
we have the same format for both file outputs, are we writing any different data types inside any of the containers?

**Comment by rlopezcoto** [comment]
images should be the same (or are we storing only pixels surviving the cleaning?). In any case, those analyzed with `dl1ab` should in that case be smaller...

**Comment by moralejo** [comment]
I think it is because auto_merge_h5files  uses no compression, can you have a look?

**Comment by maxnoe** [comment]
I think it is because https://github.com/cta-observatory/cta-lstchain/blob/a2b76b4f89b1a566b9fb12da65b11bd5ff79b6d0/lstchain/io/io.py#L186

does not use any compression.

**Comment by maxnoe** [comment]
@moralejo was faster

**Comment by moralejo** [comment]
Solved in #639, thanks @maxnoe
