### ISSUE TITLE
Output of merging stage not tested if it can be read (and merging compression error)

### ISSUE THREAD

**Issue by garciagenrique** [cta-observatory/cta-lstchain#657]
Hi,

Testing the lstchain version 0.7.0 on the MC production pipeline I'd found couple of problems. (`cta` conda environment of lstanalyzer with the last lstchain 0.7.0 version installed.)

1. On one hand the resulting output coming from the merging of various dl1 files it is not tested within lstchain ([line 160-161](https://github.com/cta-observatory/cta-lstchain/blob/04b5b9b5a1bd7c214f0ba369b059735070db2b1e/lstchain/scripts/tests/test_lstchain_scripts.py#L161) of test_lstchain_scripts)
2. The merged dl1 file cannot be read (`ValueError: invalid compression library id: 10` full log below), while single 'sub-dl1' files do not cause any problem. Pinging @maxnoe - last changes were done by you, maybe you have any clue of what's going on.

 - For 1. I think I can incorporate a test testing if the parameters table - images are not stored, I think - can be read correctly.
 - When trying to read the merged dl1 file I obtain;

Thanks in advance !

 ```
In [5]: pd.read_hdf(filename, key=dl1_params_lstcam_key)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-38b90f6e311f> in <module>
----> 1 pd.read_hdf(filename, key=dl1_params_lstcam_key)

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    397             raise FileNotFoundError(f"File {path_or_buf} does not exist")
    398 
--> 399         store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
    400         # can't auto open/close if we are using an iterator
    401         # so delegate to the iterator

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    559         self._fletcher32 = fletcher32
    560         self._filters = None
--> 561         self.open(mode=mode, **kwargs)
    562 
    563     def __fspath__(self):

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    708             raise ValueError(msg)
    709 
--> 710         self._handle = tables.open_file(self._path, self._mode, **kwargs)
    711 
    712     def close(self):

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    313 
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 
    317 

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    811         # Complete the creation of the root node
    812         # (see the explanation in ``RootGroup.__init__()``.
--> 813         root._g_post_init_hook()
    814         self._node_manager.node_factory = self.root._g_load_child
    815 

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/group.py in _g_post_init_hook(self)
    257         else:
    258             # If the file has PyTables format, get the VERSION attr
--> 259             if 'VERSION' in self._v_attrs._v_attrnamessys:
    260                 self._v_version = self._v_attrs.VERSION
    261             else:

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/utils.py in newfget(self)
    238         if name in mydict:
    239             return mydict[name]
--> 240         mydict[name] = value = fget(self)
    241         return value
    242 

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/node.py in _v_attrs(self)
    171         """
    172 
--> 173         return self._AttributeSet(self)
    174 
    175     # '_v_title' is a direct read-write shorthand for the 'TITLE' attribute

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/attributeset.py in __init__(self, node)
    246             # put the attributes on the local dictionary to allow
    247             # tab-completion
--> 248             self.__getattr__(attr)
    249             if issysattrname(attr):
    250                 self._v_attrnamessys.append(attr)

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/attributeset.py in __getattr__(self, name)
    371                 retval = numpy.array(retval)[()]
    372         elif name == 'FILTERS' and format_version is not None and format_version >= (2, 0):
--> 373             retval = Filters._unpack(value)
    374         elif name == 'TITLE' and not isinstance(value, str):
    375             retval = value.decode('utf-8')

/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/filters.py in _unpack(class_, packed)
    258             if not (0 < complib_id <= len(all_complibs)):
    259                 raise ValueError("invalid compression library id: %d"
--> 260                                  % complib_id)
    261             kwargs['complib'] = all_complibs[complib_id - 1]
    262         packed >>= 8

ValueError: invalid compression library id: 10

**Comment by garciagenrique** [comment]
I precise a bit more the issue.
The reading of the merged files is indeed tested by the function in [line 165](https://github.com/cta-observatory/cta-lstchain/blob/04b5b9b5a1bd7c214f0ba369b059735070db2b1e/lstchain/scripts/tests/test_lstchain_scripts.py#L165), although this doesn't happen for MC files as we are testing on real

**Comment by maxnoe** [comment]
>     The merged dl1 file cannot be read (ValueError: invalid compression library id: 10 full log below), while single 'sub-dl1' files do not cause any problem. Pinging @maxnoe - last changes were done by you, maybe you have any clue of what's going on.



This is a known issue with pytables that should be fixed in the latest release 3.6.1, do you have that?

**Comment by maxnoe** [comment]
The error is caused when the file was created with different compressors available at creation and reading time. Did you change anything in the environment after the creating the files?

**Comment by garciagenrique** [comment]
All the stages (`r0_to_dl1`, `merging`...) are run with the same environment (`cta` at la Palma cluster), so nothing changed.

**Comment by maxnoe** [comment]
Milestone for the next release: https://github.com/PyTables/PyTables/milestone/21
PR with the fix for that issue: https://github.com/PyTables/PyTables/pull/812

**Comment by maxnoe** [comment]
> All the stages (r0_to_dl1, merging...) are run with the same environment (cta at la Palma cluster), so nothing changed.

Are you sure, that issue is only triggered when writing and reading environment are not identical.

**Comment by mexanick** [comment]
I've made private MC reprocessing from R0 to DL2 step for few different samples and didn't face this issue (though my env was 100% stable and the same)

**Comment by garciagenrique** [comment]
> > All the stages (r0_to_dl1, merging...) are run with the same environment (cta at la Palma cluster), so nothing changed.
> 
> Are you sure? That issue is only triggered when writing and reading environment are not identical.

Will double check again, but the full pipeline should be run with the same env.

**Comment by garciagenrique** [comment]
OK, thanks @maxnoe.
When batching jobs, I use the same environment to create and read dl1 files, although when merging files no environment is defined - and thus the one in which it was launched it is used. I will then declare the same environment for the merging stage too. 

The weird thing that I found is that the env from where I was launching jobs is my local lstchain v0.7.0, with exactly the same installation as the cta one and also the same pytables version.

**Comment by maxnoe** [comment]
> The weird thing that I found is that the env from where I was launching jobs is my local lstchain v0.7.0, with exactly the same installation as the cta one and also the same pytables version.

It does not depend on the pytables *version* but on the compiler flags used to build it. E.g. it could be different from pip to conda-forge to conda default, even if the python package has the same version.

**Comment by garciagenrique** [comment]
Thanks @maxnoe for the tips, it worked adding the environment to the merging stage !
