### ISSUE TITLE
Error in dl1ab in `pedestal_thresh`

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#676]
Got this error while running the **dl1ab** step for runs from 2020-12-19. TIB FW was upgraded during these days and we had the problem with the `trigger_type==42` for most of the events.

```
lstchain_dl1ab --input-file=/fefs/aswg/data/real/running_analysis/20201219/v0.7.1/dl1_LST-1.Run03350.0103.h5 --output-file=/fefs/aswg/data/real/running_analysis/20201219/v0.7.1/tailcut84/dl1_LST-1.Run03350.0103.h5 --pedestal-cleaning=True --config=/fefs/aswg/lstosa/config_files_lstchain/lstchain_standard_config_tailcut84.json
```

```python
Pedestal cleaning
Traceback (most recent call last):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/bin/lstchain_dl1ab", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/scripts/lstchain_dl1ab.py", line 89, in main
    pedestal_thresh = get_threshold_from_dl1_file(args.input_file, sigma)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 53, in get_threshold_from_dl1_file
    ped_mean_pe, ped_std_pe = get_bias_and_std(dl1_path)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 25, in get_bias_and_std
    ped_charge_mean_pe = ped_charge_mean * dc_to_pe
ValueError: operands could not be broadcast together with shapes (4,2,1855) (2,2,1855) 
```

In the previous step (**r0 to dl1**) I got the following message very often:
```
Event with UCTS trigger_type 42 found. Probably means unreliable or shifted UCTS data. Consider switching to TIB using `default_trigger_type="tib"`
```
but the job finished properly.

There are some runs as for example `03345` that did not have this problem for any of their subruns and some other runs as for example `03341` which has some subruns with the same problem (`03341.0075`) and some others that could be processed up to DL2 (`03341.0018`).

The problem is no longer present on 2020-12-22 when the TIB FW was reverted to its previous version.

**Comment by maxnoe** [comment]
4 gains? How does that happen?

**Comment by moralejo** [comment]
Not gains, but "versions" of calibration I think

**Comment by moralejo** [comment]
Similar to #669

**Comment by moralejo** [comment]
Probably, with the wrong event tags, many "presumed" pedestals were processed, which resulted in 4 versions of the interleaved pedestal

**Comment by moralejo** [comment]
We should try to process with default_trigger_type="tib". But anyway these are just 4 nights in December, right?

**Comment by maxnoe** [comment]
Is there a maximum to the number of pedestals when a new calibration is added?

**Comment by moralejo** [comment]
> Is there a maximum to the number of pedestals when a new calibration is added?

That is a question for @FrancaCassol. I think a new one is probably added after a certain number of interleaveds.

**Comment by morcuended** [comment]
> We should try to process with default_trigger_type="tib". But anyway these are just 4 nights in December, right?

Right, there are 4 nights in Dec with this problem.

**Comment by morcuended** [comment]
Something similar seen in `Run03950.0121` from 2021-03-10:

```
lstchain_dl1ab \
  --input-file=/fefs/aswg/data/real/running_analysis/20210310/v0.7.1/dl1_LST-1.Run03950.0121.h5 \
  --output-file=/fefs/aswg/data/real/running_analysis/20210310/v0.7.1/tailcut84/dl1_LST-1.Run03950.0121.h5 \
  --pedestal-cleaning=True \
  --config=/fefs/aswg/lstosa/config_files_lstchain/lstchain_standard_config_tailcut84.json
```

```python
Pedestal cleaning
Traceback (most recent call last):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/bin/lstchain_dl1ab", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/scripts/lstchain_dl1ab.py", line 89, in main
    pedestal_thresh = get_threshold_from_dl1_file(args.input_file, sigma)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 53, in get_threshold_from_dl1_file
    ped_mean_pe, ped_std_pe = get_bias_and_std(dl1_path)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 25, in get_bias_and_std
    ped_charge_mean_pe = ped_charge_mean * dc_to_pe
ValueError: operands could not be broadcast together with shapes (3,2,1855) (2,2,1855) 
```

**Comment by FrancaCassol** [comment]
Hi,
sorry for my late reaction. In order to be consistent with the cosmic events one should here calibrate the pedestal events using the calibration event number 0 (corresponding to the beginning of night run) as we do for the cosmics. This will also eliminate the error. 
In fact, one can have a different number of ped and FF/calib (depending on the relative rate). In principle, if one wants to use the interleaved events, one should look at the calib event time range to use the correct one, but, as said, I thinks one should used the calib event 0 here.

**Comment by moralejo** [comment]
@FrancaCassol ok, thanks, can you implement that? We need to make a new release as soon as possible...

**Comment by FrancaCassol** [comment]
Hi @moralejo,
yes, I can do it

**Comment by morcuended** [comment]
The errors reported in this issue:

`ValueError: operands could not be broadcast together with shapes (3,2,1855) (2,2,1855) `

`ValueError: operands could not be broadcast together with shapes (4,2,1855) (2,2,1855) `

still happen with the current master version.

**Comment by moralejo** [comment]
If as @FrancaCassol  suggests, we should use the conversion factors from the original calibration, there is no need to make those products of arrays, so it should be easy to solve.
