### ISSUE TITLE
shower info not written in files anymore

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#692]
The MC shower info is not written in DL1 files anymore.

The dataset `dl1/event/subarray/mc_shower` only contains the columns `obs_id` and `event_id`, missing:
```
mc_energy": Float64Col(shape=(), dflt=0.0, pos=0),
  "mc_alt": Float64Col(shape=(), dflt=0.0, pos=1),
  "mc_az": Float64Col(shape=(), dflt=0.0, pos=2),
  "mc_core_x": Float64Col(shape=(), dflt=0.0, pos=3),
  "mc_core_y": Float64Col(shape=(), dflt=0.0, pos=4),
  "mc_h_first_int": Float64Col(shape=(), dflt=0.0, pos=5),
  "mc_x_max": Float64Col(shape=(), dflt=0.0, pos=6),
  "mc_shower_primary_id
```

**Comment by maxnoe** [comment]
All of these are in the dl1 container, right? https://github.com/cta-observatory/cta-lstchain/blob/cda685c7409f8a51f0aa76c05b475094e142c7d3/lstchain/io/lstcontainers.py#L31

**Comment by maxnoe** [comment]
The information is in the current files and we anyways want to switch to the ctapipe DL1 format
