### ISSUE TITLE
To compare Zen pointing of an event list and IRF before combining them to make a DL3 file

### ISSUE THREAD

**Issue by chaimain** [cta-observatory/cta-lstchain#696]
Currently, we are using IRFs made from Zen 20deg MC only, but in the near future, we would have 40deg as well as [interpolated IRFs](https://github.com/cta-observatory/pyirf/pull/141) so that we can combine a more appropriate IRF with a given event list (observed data).
I propose we add a check on the event list, to check the Zenith pointing information and compare the same from IRF (this metadata is not currently there, but can be easily added), and once their difference satisfies some safe conditions, we append them together to create the final DL3 file.

This can be done by either 
1. creating a separate script (or Tool) or,
2. updating the current DL3 Tool.

As discussed in the lst-onsite Slack channel, we currently can have at least a **standard** event list file and then add such script or code, as a check before combining with a given IRF file, to make it a DL3 file (not standard yet).

Adding to the current DL3 Tool can have a small issue - recreating an existing event list and overwriting the file.
This process probably should be left for the 'final' version of the DL3 Tool, once we have appropriate IRFs ready.

Please provide any enhancement to this plan of action or suggestions/feedback.

**Comment by maxnoe** [comment]
I think the approach should be that the create_dl3_file gets all availabe irfs and does the interpolation to the conditions of the run.
