### ISSUE TITLE
Can't read astropy table from hdf5 files

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#718]
Opening this issue for future reference.
Not strictly tightened to lstchain but I know it will happen again and to other users.

If you have an hdf5 error when trying to read astropy table from HDF5 files of this type `OSError: Can't read data` `lib/hdf5/plugin`).

```
In [1]: from astropy.table import Table
In [2]: Table.read('/fefs/aswg/data/real/DL1/20201120/v0.7.3/tailcut84/dl1_LST-1
   ...: .Run02965.0000.h5', path='dl1/event/telescope/parameters/LST_LSTCam')
OSError: Can't read data (can't open directory: /fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/hdf5/plugin)
```

You have to import `tables`  before to load the blosc extension.

So:

```
import tables
from astropy.table import Table
Table.read(filename, path=path)
```

**Comment by vuillaut** [comment]
And closing 🚀  🎉

**Comment by maxnoe** [comment]
And just to note further, it is anyway better to load tables written by the `HDF5TableWriter` such as the one mentioned in the issue using `ctapipe.io.read_table` since that will correctly handle units and column transformations.
