### ISSUE TITLE
Negative value of source coordinate when producing DL3 files 

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/cta-lstchain#727]
When input value of source coordinate for `lstchain_create_dl3_file ` is negative (e.g.  ` --source-dec -28.0595deg`) , those inputs are not recognized as input.
```
lstchain_create_dl3_file: error: argument --DataReductionFITSWriter.source_dec: expected one argument
```

Is there any solutions...?

**Comment by maxnoe** [comment]
`--source-dec=-28.0595deg` should work

**Comment by SeiyaNozaki** [comment]
ah, I see, solved it! Thank you for your quick answer!

**Comment by maxnoe** [comment]
I remember this came up before, but I cannot find the issue. Also possible is this: `--source-dec "-2.80595 deg"` (Quoting and space important.
