### ISSUE TITLE
Update to matplotlib 3.5 when released

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#754]
After #749 and #750 we pinned `pyparsing==2.4` to solve a conflict in `matplotlib` https://github.com/matplotlib/matplotlib/issues/21463 that should be solved in the next release. So whenever `matplotlib==3.5` is available, we can remove the explicit dependency to an old `pyparsing` version

**Comment by maxnoe** [comment]
This was done, but it turns out 3.5 is incompatible with gammapy due to removed deprecated keyword args.

So probably the easiest is to go back to the `pyparsing==2.4` fix?

**Comment by moralejo** [comment]
How shall we proceed with this? Would be good to have a working release tomorrow latest.

**Comment by maxnoe** [comment]
The fix is already merged: #857

**Comment by maxnoe** [comment]
This is still open, as we still want to update. But the current environment should work again.
