### ISSUE TITLE
Update to ctapipe v0.11

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#762]
Any major breaking changes in the new ctapipe [version](https://github.com/cta-observatory/ctapipe/releases/tag/v0.11.0) that prevents us to update to it? It has been out for half a year already and it would be great to get it before a major lstchain release

**Comment by maxnoe** [comment]
This would first require an update of ctapipe_io_lst, will look into it

**Comment by maxnoe** [comment]
See https://github.com/cta-observatory/ctapipe_io_lst/pull/113

Seems no changes required, all tests are passing also with ctapipe 0.11
