### ISSUE TITLE
Class DL1ParametersContainer not compliant with ctapipe

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#77]
Hi,

the class DL1ParametersContainer (in containers.py) is not compliant with ctapipe:
- it contains Fields already included in other ctapipe Containers (e.g. )
- it contains functions filling the container data, which is not supposed to be

In order to keep a clear distinction between ctapipe compliant modules (which are foreseen to be
pulled to ctapipe as soon they are ready) and local LST1 specifics modules, I suggest to rename the present containers.py to an other name (lstcontainers.py ?) and keep the containers.py module only for ctapipe compliant containers (e.g. the calibration data containers that we plan to rapidly PR to ctapipe).

If there are not objections on this point (and no other volunteer),  I can do the change. 
In a second phase, we could also try to make this class compliant with ctapipe.

Franca

**Comment by rlopezcoto** [comment]
I have no objections for the proposed refactoring, anybody has any opinion
against it?
This should in principle not affect any functionality but we may have to
redefine some calls in the existing functions. All these changes should be
included in the PR

**Comment by misabelber** [comment]
For me sounds ok, the more compliant with ctapipe, the better.

**Comment by vuillaut** [comment]
Hi.
The container was not intended to be compliant with ctapipe but rather give quick prototyping and functionality. However, I agree with the proposition to move in this direction.
Please, @FrancaCassol go forward with the proposed refactoring.

**Comment by rlopezcoto** [comment]
solved in #78
