### ISSUE TITLE
Remove 2>&1 from onsite_create_drs4_time_file

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#774]
lstchain_data_create_time_calibration_file: error: unrecognized arguments: 2>&1

`2>&1` has to be removed from:

https://github.com/cta-observatory/cta-lstchain/blob/b2a9917c6b2edf665bac9898ee87610159803b8a/lstchain/scripts/onsite/onsite_create_drs4_time_file.py#L119

**Comment by maxnoe** [comment]
If you want to have the behaviour of `2>&`, you need to add `stderr=sp.STDOUT` to the `sp.run` call
