### ISSUE TITLE
Set up Travis to keep track of new refactoring

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#79]
Hi @kosack, we would like to set up Travis to keep track of all the changes in the code that are being performed at the moment, specially the ones including the calibration by @FrancaCassol.
According to https://docs.travis-ci.com/user/tutorial/ one needs to be owner of the repository to do it, and the owner of this repository is you, could you please set up Travis for cta-lstchain? Thanks

**Comment by FrancaCassol** [comment]
Hi @kosack ,
lstchain code starts to have several developers  working in parallel, at this point the run of automatic tools like travis becomes necessity for an easy work together. Could you please take into account the above request of Ruben or do you perhaps suggest other solutions? 

Thanks

**Comment by kosack** [comment]
I don't htink I need to do anything here - travis already says it is running on all projects. You just need to configure it with a .travis.yml, or am I misunderstanding what needs to be done?

**Comment by kosack** [comment]
Never mind, it's done now.

**Comment by rlopezcoto** [comment]
Great, thanks @kosack!!
