### ISSUE TITLE
Fix coordinate calls after coordinate refactoring

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/cta-lstchain#80]
After the big coordinate refactoring in ctapipe, the modules calling ctapipe coordinates are not working anymore.

**Comment by vuillaut** [comment]
working on it asap

**Comment by misabelber** [comment]
Hi @vuillaut ! How is this going? I don't know if you have started to take a look at this but yesterday I did a couple changes following the ctapipe/examples/coordinates_transformations.py examples and I think I came out with something working. Maybe you already have it also but if not, I can do a PR as soon as I check that it works properly.

**Comment by vuillaut** [comment]
Hi @misabelber 
Unfortunately, I couldn't find the time to work on it.
If you have a working version, please make a PR and we'll review this together.

**Comment by misabelber** [comment]
Perfect, I'll go for it :)

**Comment by FrancaCassol** [comment]
Dear all,
this problem is blocking also my test of the calibration code. This is because in the __init__.py files there are too many default imports that are not necessary for all the modules. For example:

"from .lstcontainers import DL1ParametersContainer"

inside the io/__init__.py module 

I would suggest to clean a bit these imports (I had to do it in order to be able to run my code, which 
do not need them).

**Comment by vuillaut** [comment]
Hi @FrancaCassol 
No problem to make some cleaning (cleaning is always good and I think the current code needs some), but why are these import problematic?
Is that because you are working with the master branch of ctapipe?

**Comment by FrancaCassol** [comment]
Yes, I am updating the calibration code to be compatible with the ctapipe master: no Factories anymore and no LSTEventSource.

**Comment by rlopezcoto** [comment]
Ok, this is being solved now in #87, I hope to receive the new code from @FrancaCassol solving the incompatibilities with LSTEventSource that was moved to a different repo (and please also update the environment.yml file to include this repo when needed). We can then discuss about ctapipe versions...

**Comment by rlopezcoto** [comment]
Solved in #87
