### ISSUE TITLE
SubarrayDescription.from_hdf does not work on DL1ab outputs (neither on merged DL1 files)

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#837]
This problem prevents merging of DL1ab outputs.

ctapipe.instrument.SubarrayDescription works well with DL1 files produced with the current lstchain master, e.g.:

> SubarrayDescription.from_hdf("/fefs/aswg/workspace/abelardo.moralejo/Crab_tuned_MC_20211231/MC/DL1/gamma-diffuse/dl1_gamma_20deg_180deg_run1000___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono_cone6.h5")
> SubarrayDescription(name='MonteCarloArray_1-4', num_tels=4)

With the corresponding DL1 file obtained after running DL1ab (for MC tuning), however, I get the following error: 

> SubarrayDescription.from_hdf("/fefs/aswg/workspace/abelardo.moralejo/Crab_tuned_MC_20211231/MC/DL1b_tuned/gamma-diffuse/dl1_gamma_20deg_180deg_run1000___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono_cone6.h5")
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe/instrument/subarray.py", line 462, in from_hdf
>     layout = Table.read(path, path="/configuration/instrument/subarray/layout")
>   File "/fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/table/connect.py", line 61, in __call__
>     out = registry.read(cls, *args, **kwargs)
>   File "/fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/registry.py", line 527, in read
>     data = reader(*args, **kwargs)
>   File "/fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/misc/hdf5.py", line 142, in read_table_hdf5
>     return read_table_hdf5(f, path=path, character_as_bytes=character_as_bytes)
>   File "/fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/misc/hdf5.py", line 152, in read_table_hdf5
>     table = Table(np.array(input))
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 1015, in __array__
>     self.read_direct(arr)
>   File "/fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 976, in read_direct
>     self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
>   File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
> OSError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)

The configuration/instrument group exists, and seems to be the same in both files, but perhaps I am doing something wrong. Any help is welcome.

**Comment by maxnoe** [comment]
I only saw this problem before when h5py (used by astropy) and pytables (used directly by ctapipe and lstchain) are not using the same libhdf5 in a conda environment.

Can you check if either pytables or h5py are installed from pip wheels instead of conda packages?

`conda list h5py`, `conda list pytables`.

If any of them is shows to be from pypi, `pip uninstall` and then `mamba install -c conda-forge` the package(s) shows to be from pypi. Note that the pip package is called tables and the conda package is called pytables.

**Comment by morcuended** [comment]
Having both `h5py` and `pytables` installed from conda I'm getting the name `Unknown` for both DL1b MC data and DL1b observed data. Is this expected?

```python
In [3]: SubarrayDescription.from_hdf("/fefs/aswg/workspace/abelardo.moralejo/Crab_tuned_MC_20211231/MC/DL1b_tuned/gamma-diffuse/dl1_gamma_20deg_180deg_run1000___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono_cone6.h5")
Out[3]: SubarrayDescription(name='Unknown', num_tels=4)

In [4]: SubarrayDescription.from_hdf("/fefs/aswg/data/real/DL1/20210808/v0.8.2.post1/tailcut84/dl1_LST-1.Run05550.0004.h5")
Out[4]: SubarrayDescription(name='Unknown', num_tels=1)
```

**Comment by maxnoe** [comment]
I think it should be `MonteCarlo Array` since they come from simtel files. Will have a look tomorrow.

**Comment by maxnoe** [comment]
This one is also already `"Unknown"`: 

```
In [3]: SubarrayDescription.from_hdf("/fefs/aswg/data/real/DL1/20201120/v0.8.2.post1/tailcut84/dl1_LST-1.Run02965.0000.h5")
Out[3]: SubarrayDescription(name='Unknown', num_tels=1)
```

But the `EventSource` has this: 

```
In [8]: s = LSTEventSource("/fefs/aswg/data/real/R0/20201120/LST-1.1.Run02965.0000.fits.fz")

In [9]: s
Out[9]: <ctapipe_io_lst.LSTEventSource at 0x7fe3c4519610>

In [10]: s.subarray
Out[10]: SubarrayDescription(name='LST-1 subarray', num_tels=1)
```

**Comment by moralejo** [comment]
> I only saw this problem before when h5py (used by astropy) and pytables (used directly by ctapipe and lstchain) are not using the same libhdf5 in a conda environment.
> 
> Can you check if either pytables or h5py are installed from pip wheels instead of conda packages?
> 
> `conda list h5py`, `conda list pytables`.
> 
> If any of them is shows to be from pypi, `pip uninstall` and then `mamba install -c conda-forge` the package(s) shows to be from pypi. Note that the pip package is called tables and the conda package is called pytables.


Seems to be the case, will re-install...

```
$ conda list h5py
# packages in environment at /fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev:
#
# Name                    Version                   Build  Channel
h5py                      3.6.0                    pypi_0    pypi

$ conda list pytables
# packages in environment at /fefs/aswg/workspace/abelardo.moralejo/miniconda3/envs/lst-dev:
#
# Name                    Version                   Build  Channel
pytables                  3.6.1            py38hc386592_3    conda-forge
```

**Comment by moralejo** [comment]
I just uninstalled h5py as you said, and then updated my lst-dev conda environment - hence the right h5py from conda-forge was installed. It works now, thanks a lot!
