### ISSUE TITLE
`lstchain.io.io.auto_merge_h5files` does not include group attributes.

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#838]
Having both `h5py` and `pytables` installed from conda I'm getting the name `Unknown` for both DL1b MC data and DL1b observed data. Is this expected?

```python
In [3]: SubarrayDescription.from_hdf("/fefs/aswg/workspace/abelardo.moralejo/Crab_tuned_MC_20211231/MC/DL1b_tuned/gamma-diffuse/dl1_gamma_20deg_180deg_run1000___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono_cone6.h5")
Out[3]: SubarrayDescription(name='Unknown', num_tels=4)

In [4]: SubarrayDescription.from_hdf("/fefs/aswg/data/real/DL1/20210808/v0.8.2.post1/tailcut84/dl1_LST-1.Run05550.0004.h5")
Out[4]: SubarrayDescription(name='Unknown', num_tels=1)
```

_Originally posted by @morcuended in https://github.com/cta-observatory/cta-lstchain/issues/837#issuecomment-1003762850_

**Comment by maxnoe** [comment]
This one is also already `"Unknown"`: 

```
In [3]: SubarrayDescription.from_hdf("/fefs/aswg/data/real/DL1/20201120/v0.8.2.post1/tailcut84/dl1_LST-1.Run02965.0000.h5")
Out[3]: SubarrayDescription(name='Unknown', num_tels=1)
```

But the `EventSource` has this: 

```
In [8]: s = LSTEventSource("/fefs/aswg/data/real/R0/20201120/LST-1.1.Run02965.0000.fits.fz")

In [9]: s
Out[9]: <ctapipe_io_lst.LSTEventSource at 0x7fe3c4519610>

In [10]: s.subarray
Out[10]: SubarrayDescription(name='LST-1 subarray', num_tels=1)
```


So the correct subarray name is lost somewhere on the way in r0_to_dl1.

**Comment by maxnoe** [comment]
I just ran r0 to dl1 on a data file and get:

```
In [9]: s = SubarrayDescription.from_hdf('./dl1_LST-1.Run02965.0000.h5')

In [10]: s
Out[10]: SubarrayDescription(name='LST-1 subarray', num_tels=1)
```

So why does the the osa file with the same version have "Unknown"?

**Comment by morcuended** [comment]
Those files are post dl1ab script. The original ones from r0 to dl1 are not kept

**Comment by maxnoe** [comment]
Ah, so it probably is lost in the dl1ab step, checking....

**Comment by maxnoe** [comment]
`auto_merge_h5files` does not copy group metadata, which is where e.g. the subarray name is stored.
