### ISSUE TITLE
which ctapipe version for lstchain?

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#84]
Hi, 

I would like to make a PR with part of the flat field code but I  see that the master of ctapipe 
has several changes related to some core components (like Factories), that concern also the
calibration code. Then before doing the PR I must update it if we want to be able to use ctapipe master.
So, I wonder, which is the politic of lstchain with respect to the ctapipe versions?

Thanks

**Comment by vuillaut** [comment]
Related to issue #74

**Comment by rlopezcoto** [comment]
we would like to keep this repo in synchronization with the development version of ctapipe, therefore we decided not to fix any ctapipe version to run with cta-lstchain.
I am very afraid that if we fix a ctapipe version, we will soon diverge from ctapipe master branch and will require a lot of effort to merge later. 
I know this is specially problematic now that ctapipe is undergoing so many changes and if you feel strongly against this, we can open this discussion again

**Comment by kosack** [comment]
If it helps, I'm just in the process of releasing packages for ctapipe 0.6.2 which is pretty close to the master version (minus a few major refactorings). The next version will be 0.7, since some API changes have occurred, though mostly they shouldn't effect lstchain I think (though I haven't looked in detail). I'd suggest generally keeping with the latest release version, rather than the master, which might move too fast for your development. Though if you have the manpower, you can of course keep in sync with the master.  We'll try to do releases more often as well.

**Comment by vuillaut** [comment]
So following our discussion with Franca:
- we set a travis build with the master of ctapipe (I'll investigate how to do that)
- we wait for PR #92 to be merged (it should pass with the ctapipe master build)
- when ctapipe 0.7 is released, we'll move to the following politics:
    - having lstchain master following a fixed release of ctapipe
    - set a new lstchain branch to follow ctapipe master developments as closely as possible

**Comment by rlopezcoto** [comment]
right, so I propose to leave this open until we include the ctapipe release into the requirements of the master branch

**Comment by rlopezcoto** [comment]
I guess we should retake this Issue now:
https://github.com/cta-observatory/ctapipe/releases/tag/v0.7.0

and fix the cta-lstchain `master` to ctapipe version 0.7.0

**Comment by vuillaut** [comment]
> I guess we should retake this Issue now:
> https://github.com/cta-observatory/ctapipe/releases/tag/v0.7.0
> 
> and fix the cta-lstchain `master` to ctapipe version 0.7.0

Yep.

For those who might have missed the last lst-reco call, see [the information slides](https://indico.cta-observatory.org/event/2379/contributions/20975/attachments/15994/20604/20190730_lstchain_branches_workflow_vuillaume.pdf) about the workflow.

I guess we can already fix ctapipe version to 0.7 in master as everything is currently up and running with v0.7.

I have already created the branch `ctapipe_master` in agreement with the workflow.

**Comment by rlopezcoto** [comment]
Thanks. 
I would wait for the cta-lstchain release until we have solved the latest PRs, since now many people are on holidays...

**Comment by vuillaut** [comment]
lstchain release is independent from fixing ctapipe version.
A lstchain release will come afterwards (and yes probably after current pending PRs).

**Comment by vuillaut** [comment]
Closing, as this has been fixed in #163
