### ISSUE TITLE
Error when using gammapy v0.18.2 and matplotlib>3.5

### ISSUE THREAD

**Issue by alvmas** [cta-observatory/cta-lstchain#855]
Hi,
After installing the latest version of lstchain and trying to plot spectrum with gammapy this error appears:

ax_spectrum, ax_residuals= flux_points_dataset_crab.plot_fit()
**TypeError: __init__() got an unexpected keyword argument 'nonposx'**

It seems that gammapy is not compatible with the latest version of matplotlib that we use in lstchain. I realized that using matplotlib<3.5 solved the problem. Indeed when using this previous version it works but shows a DeprecationWarning:

_MatplotlibDeprecationWarning: The 'nonposx' parameter of __init__() has been renamed 'nonpositive' since Matplotlib 3.3; support for the old name will be dropped two minor releases later.
  ax.set_xscale("log", nonposx="clip")_

**Comment by chaimain** [comment]
To be more clear, gammapy v0.19 has the issue resolved https://github.com/gammapy/gammapy/pull/3284 but not in v0.18.2. They however have not updated their matplotlib dependency. Maybe updating the gammapy dependency solves the issue for us.

**Comment by maxnoe** [comment]
We just released a new version of pyirf with compatibility for gammapy 0.19. So we could try to just update both.

**Comment by alvmas** [comment]
I updated gammapy to v0.19 and the problem with the 'nonposx' is solved, but instead the fitting fails since gammapy uses imunit>2.8

**Comment by chaimain** [comment]
For this to be resolved, we would need updated iminuit, which is done in ctapipe 0.12, and I think to update the dependency to ctapipe 0.12 as mentioned here https://github.com/cta-observatory/cta-lstchain/pull/802, we need to merge this https://github.com/cta-observatory/ctapipe_io_lst/pull/128 first.

Without this, we won't be able to use gammapy functions. Unless someone can provide an easier alternative.

**Comment by maxnoe** [comment]
Then we also require updating to ctapipe 0.12, which also updates to imiuit 2.x.  

I will prepare PRs in ctapipe_io_lst and here updating all of that together.

**Comment by maxnoe** [comment]
Necessarily, I won't be able to do it before

**Comment by chaimain** [comment]
We have to rollback matplotlib then, or use a separate environment for gammapy based analyses...
