### ISSUE TITLE
lstchain_dl1b.py  --no-image option is no longer working

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#858]
The image data is written out regardless of the value of --no-image

**Comment by moralejo** [comment]
The reason is the changes here:
https://github.com/cta-observatory/cta-lstchain/commit/59d74bb43b61d6e909edd5282ff779a89ea7a6a5

The nodes are read again from the file, while the noimage option simply removed the image one from nodes_keys

**Comment by moralejo** [comment]
I think it is here that it copies all nodes in the file:
https://github.com/cta-observatory/cta-lstchain/blob/59d74bb43b61d6e909edd5282ff779a89ea7a6a5/lstchain/io/io.py#L312

**Comment by moralejo** [comment]
Will open a PR

**Comment by maxnoe** [comment]
But `automerge_h5_files` is not used anymore in dl1ab and the call to `copy_h5_nodes` in dl1ab includes the `node_keys` option.

**Comment by moralejo** [comment]
It is still used, right?

**Comment by maxnoe** [comment]
Only in `lstchain_merge_h5files`, not in dl1ab
