### ISSUE TITLE
Update core dependencies

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#884]
We should update to

* ctapipe 0.12
* gammapy 0.19

This requires https://github.com/cta-observatory/ctapipe_io_lst/pull/128 and also updating:
* iminuit 2.x
* pyirf 0.6

Because of ctapipe 0.11 and gammapy requiring iminuit 1.x and ctapipe 0.12 and gammapy 0.19 requiring iminuit 2.x we need to update both gammapy and ctapipe at the same time.

**Comment by rlopezcoto** [comment]
reviewing and merging #802 would solve this, right?

**Comment by maxnoe** [comment]
Yes
