### ISSUE TITLE
Problem reading hdf5 files with latest version of ctapipe

### ISSUE THREAD

**Issue by misabelber** [cta-observatory/cta-lstchain#89]
Hi!
I just noticed a problem after updating to ctapipe 0.6.2 release when using pandas to read a h5 file. 
Usually we were able to open an h5 file that only had 1 dataset simply doing:
df = pandas.read_hdf('filename')
but now it is complaining when I try to read the results file from dl0_to_dl1.r0_to_dl1 which is written with a key='events/LSTCam'. If I read the hdf including the key  df = pandas.read_hdf('filename', key='events/LSTCam') the problem dissapears. Are you having the same problem? We should take this into account, for example in the function "build_models" from dl1_to_dl2 which reads hdf5 files. I think we should include a way to read the key names of the datasets. Have you noticed this issue?

**Comment by vuillaut** [comment]
Hey.

I was actually noticing this exactly at the same time.
I guess the new version of `pandas` does not allow to read hdf5 files without giving the key to the dataset event if there is only one.

**Comment by misabelber** [comment]
Do you know if there is an easy way to get the key names? Maybe using h5py module. I solved the problem in my repo just writing the "key='events/LSTCam' " arg, but I think it would be better to have a more general way of reading the files which may have a different key name.

**Comment by vuillaut** [comment]
Two options here:
- imposing the dataset `events/cam_id` so in our case `events/LSTCam`
- trying to guess the dataset name with `h5py` - there is already a function `get_dataset_keys` doing that in `scripts/merge_hdf5_files`

Going with the second option still supposes that the user does what we expect him to do: creating hdf5 files with only one dataset containing the events.
Versatility vs robustness...

**Comment by misabelber** [comment]
Well, since r0_to_dl1 creates a file with only one dataset named automatically events/cam_id, we can assume that the user will use it to create the files and then there will be always 1 dataset. I guess for now we can go with the second option and if any problem shows up, think for an alternative.

**Comment by rlopezcoto** [comment]
I agree that we can go with the second solution. In principle I cannot think by now on any usage that does not come from what @misabelber is mentioning. In case we find that this turns out to be problematic for any users, we can always change it.

**Comment by misabelber** [comment]
Good, then I'll do a PR with this change as soon as possible.

**Comment by kosack** [comment]
its' a bug in pandas - I found the same problem and had to update all the examples in ctapipe. The "guessing" of the dataset if you don't specify one doesn't work in the latest pandas version. I suspect it may be fixed at some point - there is an issue open I think, but generally it's good to specify the dataset in any case, especially if we expect to ever merge multiple datasets into one file.

**Comment by rlopezcoto** [comment]
solved in #97
@misabelber if you want to give it another thought to the solution, I can reopen
