### ISSUE TITLE
Writing DL0 data files for level B camera calibration 

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/cta-lstchain#901]
This  issue refines an issue started with  #801 

Level B calibration is planed to be performed in DPPS starting from DL0 data that contains waveforms. 

In CTA, data production will be from R1 to DL0 in ACADA and from DL0 to DL3 in DPPS, but at present  LST is  storing directly DL1, where waveforms are discarded.

In order to develop the calibration code as close as possible to future DPPS, I propose to write DL0 files only for FF and pedestal events (~2% of the events). The files will be in h5 format, similar to DL1. They will contain the R1 waveforms and the columns of the parameter table with R1 info. They will include also the first row of the monitoring table that is used to calibrate the R1 waveform.

The DL0 file will be written by the  r0_to_dl1 script.

The calibration code will then process the DL0 data over all subruns and produce a  DL1 calibration file with several /dl1/event/telescope/monitoring/ rows as function of the time interval and/or sample statistics. This calibration DL1 file can then be read to create "cat-B" DL1 physics data, calibrated with the interleaved calibration results including azimuth gain correction, flatfielding, noise estimation, bad pixels monitoring and correction. 

Comments are welcome

**Comment by maxnoe** [comment]
> In order to develop the calibration code as close as possible to future DPPS

I don't really see why you need DL0 files for that. Why can this code not be developed using the LSTEventSource producing R1?

R1 is the same as DL0 for calibration events, since we we won't apply data volume reduction on calibration events.

**Comment by FrancaCassol** [comment]
Hi @maxnoe,

yes, this could be also an option, I thought to the r0_to_dl1 script in order to recycle part of the parameter table but it is probably not a strong argument. And, what concerning the format? Do you agree on the h5 "DL1 type" format?

I call them DL0 because they will correspond to the DL0 step (data for DPPS not for ACADA) and we should slowly start to use the correct terminology.

**Comment by maxnoe** [comment]
> I call them DL0 because they will correspond to the DL0 step

Yes, it was just to point out that there is no additional step to be made for calibration events

> And, what concerning the format? Do you agree on the h5 "DL1 type" format?

I think at this point, as you mentioned basically already, this is not LST specific, thus discussion should happen in ctapipe / DPPS, not in lstchain. But yes, it should fit with the current DL1 format of ctapipe and can then be evolved together.

> yes, this could be also an option, I thought to the r0_to_dl1 script in order to recycle part of the parameter table but it is probably not a strong argument. 

@kosack just added support for writing out R0 / R1 waveforms into the HDF5 files which can be interpreted as a DL0 HDF5 format to the ctpaipe datawriter here:

https://github.com/cta-observatory/ctapipe/pull/1799

So *if* we wanted to, we can use the current ctapipe master to write out R1 waveforms into HDF5, but again, I think won't actually need this just to prototype the calibration system.

**Comment by FrancaCassol** [comment]
> @kosack just added support for writing out R0 / R1 waveforms into the HDF5 files which can be interpreted as a DL0 HDF5 format to the ctpaipe datawriter here:
> 
> [cta-observatory/ctapipe#1799](https://github.com/cta-observatory/ctapipe/pull/1799)
> 
> So _if_ we wanted to, we can use the current ctapipe master to write out R1 waveforms into HDF5, but again, I think won't actually need this just to prototype the calibration system.

Wonderfull, then let's go for it. 

@moralejo, @rlopezcoto any strong opinion on where to do it:  r0_to_dl1 or LSTEventSource?

**Comment by maxnoe** [comment]
> @moralejo, @rlopezcoto any strong opinion on where to do it: r0_to_dl1 or LSTEventSource?

I don't understand. You have to use `ctapipe-process` on the current ctapipe master together with the `LSTEventSource` to write out R1 waveforms.

**Comment by FrancaCassol** [comment]
No, I want to do it during the LST1 DL1 processing in order not to go through all the data again

**Comment by maxnoe** [comment]
@FrancaCassol I really don't see how that is necessary for developing the code. 

For doing the development, it would be enough to do it for a handful of runs, right?

**Comment by FrancaCassol** [comment]
I think I explained this in the top of this issue. The reason is that we want to apply the level B calibration to LST1 data and develop the code at most compliant with the future  DPPS code (hopefully the code could shortly go in ctapipe). 

Looking the DataWriter class, it seems just what we want. I think we can simply use it for writing the data.

**Comment by maxnoe** [comment]
> . The reason is that we want to apply the level B calibration to LST1 data and develop the code at most compliant with the future DPPS code (hopefully the code could shortly go in ctapipe).

Yes, but why is that not possible using ctapipe directly with the `LSTEventSource`? That would be the "DPPS" way, not implement something in lstchain.

**Comment by FrancaCassol** [comment]
I did not say that is not possible, this seems indeed a good option

**Comment by moralejo** [comment]
I think that, to start with this level-B calibration development, a separate script that reads in LST .fz files, produces the (double-gain) R1 waveforms, and writes them out as h5 file seems the way to go. Eventually, if from the study we conclude it is worth to use this for the standard processing of LST1 data before we move to using ctapipe stage1, we could just add the writing lines to the r0_to_dl1 script.

The only advantage I see to including that straightaway is that we would start having all those "DL0-calib" files produced automatically, rather than needing to launch a dedicated script. But it seems like a very little advantage.

**Comment by FrancaCassol** [comment]
Hi @moralejo,

yes,  the idea is to automatically produced the files only after that the code is fully developed and tested. 

Here the main point was to accept the  idea of writing the DL0 interleaved data in future.

**Comment by maxnoe** [comment]
Just to note that this is possible using the current ctapipe master now and I did it already for a calibration run here:

```
 /fefs/aswg/workspace/maximilian.noethe/calib_r1/
```
