### ISSUE TITLE
"Metadata does not match" message

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#951]
Encountered this while merging files:

./dl1_theta_30.390_az_93.640_merged.h5 cannot be merged '¯\_(ツ)_/¯: Metadata does not match for key {k}:  {v1!r} / {v2!r}'

Regardless of the reason for the mismatch (which may be my fault), the message is not actually telling the mismatching key.

**Comment by maxnoe** [comment]
Fix for missing f-strings here: https://github.com/cta-observatory/cta-lstchain/pull/952

**Comment by maxnoe** [comment]
@chaimain Why close this issue? Is it clear why the metadata was not matching?

**Comment by chaimain** [comment]
Sorry, I assumed that the only issue was the missing f-strings. @moralejo Can you confirm either case?

**Comment by moralejo** [comment]
The reason was nothing relevant, just one file which had not been properly generated. So we can close this.
