### ISSUE TITLE
Value error when downloading buggy IERS A

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/cta-lstchain#958]
When I use `sky_to_camera` function, which is also used inside `get_expected_source_pos` for source-dependent analysis, I got the following ValueError:
`ValueError: Column year failed to convert: invalid literal for int() with base 10: '<!'`

This was also reported in astropy issue:
https://github.com/astropy/astropy/issues/13007
and already fixed in a dev version with the update of URL:
https://github.com/astropy/astropy/pull/13004

This issue also can be fixed as @mireianievas introduced in https://github.com/cta-observatory/cta-lstchain/pull/957.

It would be better to introduce a patch for `sky_to_camera` function too? Any comments are welcome.

**Comment by maxnoe** [comment]
Hi, this is due to a server being offline and the fallback behaving strangely (it seems only on macos?).

However, the file is available to download from a backup mirror (which is now also re-introduced in astropy 5.0.4, but which we unfortunately cannot just update to as ctapipe 0.12 is not compatible yet with astropy 5.


However, a better solution would be to download the file from the backup mirror into astropy's cache:

```python
from astropy.utils import iers
from astropy.utils.data import import_file_to_cache, download_file


WORKING_IERS_A_URL = "https://maia.usno.navy.mil/ser7/finals2000A.all"

path = download_file(WORKING_IERS_A_URL)
import_file_to_cache(iers.IERS_A_URL, path, replace=True)

```

**Comment by SeiyaNozaki** [comment]
Hi @maxnoe, thanks for the suggestion.
But I got an error with these lines when launching sbatch jobs...
(It seemed it didn't manage to download the file from sbatch environment if I remember correctly, I will check the actual error again later)

Instead of that, the following patches from #957 work fine.
```
from astropy.utils import iers
iers.conf.auto_download = False
```
So it would be better to use this to solve the issue without astropy5?

This value error is annoying since I also got the same error when creating DL3 files...

**Comment by SeiyaNozaki** [comment]
It seems it works well now without any modification. (The server is back again?)
So there is no need to add a patch for this issue now.

**Comment by maxnoe** [comment]
> It seems it works well now without any modification. (The server is back again?)

No, server is still down: https://datacenter.iers.org/

> But I got an error with these lines when launching sbatch jobs...

You should run this code *once* (or rather regularly) on the gateway, so that the file is available for astropy and the batch jobs should then see that the file is up-to-date and not try to download it.

**Comment by maxnoe** [comment]
Testing this (clearing the astropy cache `rm -r ~/.astropy/cache`, I get this warning on the node:

```
WARNING: failed to download ftp://anonymous:mail%40astropy.org@gdc.cddis.eosdis.nasa.gov/pub/products/iers/finals2000A.all and https://datacenter.iers.org/data/9/finals2000A.all, using local IERS-B: <urlopen error Unable to open any source! Exceptions were {'ftp://anonymous:mail%40astropy.org@gdc.cddis.eosdis.nasa.gov/pub/products/iers/finals2000A.all': URLError("ftp error: timeout('timed out')"), 'https://datacenter.iers.org/data/9/finals2000A.all': URLError(timeout('timed out'))}> [astropy.utils.iers.iers]
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the arcsec level [astropy.coordinates.builtin_frames.utils]
```

Running the script above on the gateway makes the warning on the node go away.

**Comment by maxnoe** [comment]
Just an update, now that the server in astropy is working correctly again, it is enough to run:

```
from astropy.utils import iers
from astropy.utils.data import clear_download_cache

clear_download_cache()

iers.IERS_Auto.open()
```

once a week on the gateway.
