### ISSUE TITLE
CI tests import lstchain from the working directory and not the install directory

### ISSUE THREAD

**Issue by gabemery** [cta-observatory/cta-lstchain#994]
I realised that (at least this is my main guess) during tests imports are done in priority relative to ./ instead of the installation directory. This in particular affects lstchain imports. This is an issue if the installation creates/modify files as for the AOT compilation of numba code in #904  where lstchain/reco/log_pdf_CC.cpython-38-x86_64-linux-gnu.so is produced from numba functions definition in lstchain/reco/reconstructorCC.py.

The CI perform 'pip install .' before calling pytest. This pip install installs lstchain in the site-package of the selected python lib. (tested in local) and creates there the compiled module. Then during tests imports of functions from the compiled module fails.
In local I also tried importing after such an installation and it failed only from the installation folder (as it contains the lstchain folder but not the compiled file in lstchain/reco/)

**Comment by maxnoe** [comment]
This kind of confusion is the reason why some consider the layout of having a `src` or `lib` directory superior (`src/lstchain` instead of just `lstchain`).

An alternative is to run the tests from not inside the source directory using `pytest --pyargs lstchain` or doing the `-e` install instead.

**Comment by gabemery** [comment]
If we want a quick fix, using `-e` would be the easiest.  Changing the work directory should also be doable but would probably be a bit more modification (create/ go to the directory, change linking to the test data, +?) It would have the advantage of testing the non-developer version of the installation.

I don't know how much work would be needed to change to go to the sub_directory structure but the change would be larger on the code structure compared to only changing the CI. I guess we would first need to gather the view of lstchain developers before doing the change ( and for uniformity maybe also see what are the ideas of developers of for other CTA code like ctapipe)

**Comment by maxnoe** [comment]
I have that on my list since a long time... 

We are planning to setup a recommended project structure for dpps and I think that we'll use the `src/` layout there.

**Comment by gabemery** [comment]
In this case can I add the `-e` to my PR as a temporary fix while this is being decided on? An remove it later when the new structure is here. 

To do it I can simply modify .github/workflows/ci.yml right?

**Comment by maxnoe** [comment]
Yes
