### ISSUE TITLE
Allow a list of files as input to dl1 to dl2

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#996]
Then allowing the models to be loaded only once and applied iteratively on files without loading them all the time.
This would save a lot of computing when applied to many small files (e.g. subruns).

Follow-up to #979 and #985

**Comment by gabemery** [comment]
It looks challenging if we want one file at a time in memory. In particular I don't see how to process one file at a time without adding (large?) io when reading dl1 parameters and adding the new dl2 parameter. The way I see it, it would require to do the following:
- load dl1 file -> create dl2 file without dl2 parameters (loop)
- load first RF
- load dl1 parameters from the dl2 file -> write 1st dl2 parameter to file (loop)
- load second RF
- load dl1 parameters from the dl2 file -> write 2nd dl2 parameter to file (loop)
- load third RF
- load dl1 parameters from the dl2 file -> write 3rd dl2 parameter to file (loop)

Or alternatively load all files together and apply each RF one by one while keeping the files in memory. This should be relatively easy using loops over loaded dataframes in e.g. a dictionary.

**Comment by vuillaut** [comment]
In this use-case, I don't intend to delete the models from memory at inference.
Both use-cases are necessary, either you are running on  low-memory and apply them one-by-one and one file at a time.
Or you can afford to request enough memory and then we should avoid loading models constantly.

**Comment by gabemery** [comment]
Ok in this case it is definitively doable. I wonder if the preferred approached should be:
- load all model, then iterate on files (which the apply model version in #985 can already be used for)
- load all files then do one model at a time

I kind of prefer the first one, especially because implementation in a script should be easy after merging of the ongoing PR.

**Comment by maxnoe** [comment]
Yes, option  1)
